import sys; sys.path.insert(0,'.c9')
from mk import mk
mk({
"id":"dar_guia_humilde_tres_tecnicas",
"titulo":"Dar elogio y critica con humildad, con las tres tecnicas que el texto nombra y atribuye una a una",
"denominaciones":{"nombre_largo":"La humildad como primera condicion de la guia: situacion, comportamiento e impacto; la columna de la izquierda; y la humildad ontologica","otros_idiomas":[{"idioma":"ingles","termino":"be humble"},{"idioma":"ingles","termino":"situation, behavior, impact"},{"idioma":"ingles","termino":"left-hand column"}],"sigla":"SBI"},
"condiciones_activacion":"Cuando vas a dar elogio o critica a alguien y quieres que no suene arrogante ni condescendiente, que es lo que levanta la resistencia natural a lo que dices.",
"entregable_esperado":"Guia dicha describiendo lo que viste y no juzgando a la persona, con tu propio juicio puesto en duda antes de salir por tu boca.",
"pasos_accionables":[
 "Empieza por la humildad, que es lo que el texto pone como absolutamente esencial tanto al dar critica como al dar elogio: la critica dicha con humildad rompe la resistencia natural a lo que dices, y el elogio sin humildad suena condescendiente o deshonesto.",
 "Cuenta con la respuesta que el texto da a la preocupacion mas comun, la de y si me equivoco: puede que te equivoques perfectamente, y decirle a alguien lo que piensas le da la oportunidad de decirte si es asi. El texto pone como gran parte del valor de dar guia justamente que se corrigen las percepciones equivocadas de los dos lados.",
 "Usa la tecnica de situacion, comportamiento e impacto, que el texto atribuye al Center for Creative Leadership: describe las tres cosas cada vez que des guia, primero la situacion que viste, segundo el comportamiento, es decir lo que la persona hizo, sea bueno o malo, y tercero el impacto que observaste.",
 "Evita asi hacer juicios sobre la inteligencia de la persona, su sentido comun, su bondad innata u otros atributos personales, porque cuando pasas juicios generales tu guia suena arrogante.",
 "Aplica lo mismo al elogio y no solo a la critica, porque el texto dice que el elogio puede sonar igual de arrogante: en vez de eres un genio o estoy muy orgulloso de ti, que segun el texto invitan a preguntar quien eres tu para juzgar mi inteligencia o para estar orgulloso de mi, di la situacion, el comportamiento y el impacto, como en el ejemplo del texto sobre una presentacion de esa maniana.",
 "Usa el ejercicio de la columna de la izquierda, que el texto atribuye a Chris Argyris, profesor de la Harvard Business School, y a Donald Schon, profesor de filosofia y planificacion urbana.",
 "Piensa en una conversacion que tuviste y que fue frustrante.",
 "Coge una hoja limpia y traza una linea por la mitad.",
 "Escribe en la columna de la derecha lo que dijiste de verdad.",
 "Escribe en la columna de la izquierda lo que pensaste.",
 "Piensa entonces en que momento se torcio la conversacion, y si lo que pensabas se te escapo hacia lo que dijiste.",
 "Cuenta con lo que el texto dice que es y no es el objetivo del ejercicio: no se trata de decir sin mas lo que haya en tu columna izquierda, sino de tener la humildad de poner en duda lo que estas pensando, del estilo de preguntarte si esa persona esta de verdad acaparando informacion o simplemente se le olvido contartelo, o si es de verdad poco fiable o eres tu quien no definio bien los requisitos.",
 "Practica la humildad ontologica, que el texto toma del capitulo asi titulado del libro Conscious Business de Fred Kofman: no confundas la realidad objetiva con tu experiencia subjetiva.",
 "Cuenta con el ejemplar que el texto usa para explicarlo, la nina que dice que el brocoli es asqueroso y que por eso no le gusta: tiene gracia en alguien de tres anios, y en un adulto que dice que ese es un idiota y que por eso se equivoca es arrogancia.",
 "Ten presente que tu experiencia subjetiva no es verdad objetiva, que es lo que segun el texto te deja desafiar a otros de una forma que invita al desafio reciproco."
],
"resumen_teorico":"UNIDAD DE ORIGEN: fuentes/scott_radical_candor/cap_09.md, unidad Cap. 6, Guidance. Sale de las lineas 77 a 95, bajo el rotulo Be humble, dentro de la seccion GIVING IMPROMPTU GUIDANCE. ES LA PIEZA P8 DE LA FRONTERA DE ESTA VUELTA. POR QUE ES PROCEDIMIENTO Y NO POSTURA, con D.27 delante: la linea 81 dice literalmente Here are some techniques I have found helpful to make sure I am being humble when giving praise and criticism, y detras van TRES tecnicas rotuladas y atribuidas una a una, cada una con su mecanica escrita. La de la columna de la izquierda es la mas literal de las tres: el texto pone los cinco actos del ejercicio en orden, coger la hoja, trazar la linea, escribir a la derecha, escribir a la izquierda y buscar el momento en que se torcio, y por eso van de P7 a P11 uno por acto y no fundidos. Es inventario de MEDIOS, no de metas ni de fines, y no hay adjetivo de adecuacion en el sitio del criterio. RELECTURA DE FIDELIDAD D.30 EN EL ACTO: 15 pasos, 15 TRANSCRIPCION, 0 PUENTE. P1 y P2 salen de la linea 79; P3, P4 y P5 de las lineas 83, 85, 87 y 89; P6 a P12 de las lineas 91 y 93; P13, P14 y P15 de la linea 95. LAS TRES ATRIBUCIONES VAN COMO EL TEXTO LAS PONE y no como autoridad anadida por mi: el Center for Creative Leadership en el P3, Argyris y Schon en el P6, Kofman y su libro en el P13. No van al campo atribuciones porque ninguna es una cifra: el principio 5 pide fecha de corte para una cifra del autor, y aqui no hay ni una. EL EJEMPLO DEL APARCAMIENTO DE LA LINEA 85 NO VA DE PASO: es el ejemplo cotidiano con el que el texto ilustra la tecnica, y meterlo como paso seria hacer del caso la casa, que es lo que el manual 3.5 prohibe. Lo que si va, en el P5, es la version de esa misma tecnica aplicada al elogio, porque ahi el texto si escribe el acto. LO QUE EL TEXTO NO DICE Y POR ESO NO ESTA AQUI: cada cuanto se hace el ejercicio de la columna de la izquierda, que se hace con la hoja despues, ni quien mas la ve."
})
