import sys; sys.path.insert(0,'.c9')
from mk import mk
mk({
"id":"elegir_medio_dar_guia_jerarquia_modos",
"titulo":"Dar la guia en persona siempre que se pueda, y cuando no, elegir el medio por la jerarquia de modos que el texto ordena",
"denominaciones":{"nombre_largo":"El medio como cuarta condicion de la guia: en persona primero, y si no, inmediatez contra presencia, videollamada, telefono, y el correo con copia a todos prohibido para la critica","otros_idiomas":[{"idioma":"ingles","termino":"in person (if possible)"},{"idioma":"ingles","termino":"hierarchy of modes"},{"idioma":"ingles","termino":"Reply All do's and don'ts"}],"sigla":""},
"condiciones_activacion":"Cuando tienes que dar guia y la persona no esta delante, o la tienes delante y te tienta escribirle en vez de decirselo.",
"entregable_esperado":"La guia entregada por el medio mas alto de la jerarquia que las circunstancias permiten, y nunca una critica con copia a todos.",
"pasos_accionables":[
 "Da la guia en persona siempre que puedas, y cuenta con el motivo que el texto pone: la claridad de tu guia se mide en el oido del otro y no en tu boca, y si no puedes ver la reaccion no vas a saber de verdad si la otra persona entendio lo que decias.",
 "Mira el lenguaje corporal y la expresion de la cara para ajustar como estas entregando el mensaje, que segun el texto es mucho mas facil cuando puedes mirarle a los ojos y notar si se remueve o cruza los brazos.",
 "No evites la reaccion emocional del otro, que es lo que el texto identifica como el motivo habitual de la tentacion de no darla en persona: si alguien se disgusta, eso te da la oportunidad de mostrar compasion y de subir en la dimension de cuidar personalmente.",
 "Lee la reaccion emocional como senial de por donde ajustar: si te estan despachando, el texto dice que tienes que ir mas lejos en la dimension de desafiar directamente; y si alguien esta disgustado o enfadado, centrate en mostrar que te importa y no dejes que la emocion te tire de tu buena intencion de desafiar directamente.",
 "Cuando en persona no sea posible, decide primero entre inmediatez y presencia con la regla que el texto da: si la persona esta en otra ciudad y darsela en persona significa esperar mas de unos pocos dias, optimiza por la inmediatez, salvo que lo que tengas que hablar sea algo gordo. El texto pone su propio limite entre parentesis: no despidas a nadie por mensaje.",
 "Y si la persona esta al final del pasillo, y hacerlo en persona es solo dar un paseo, levantate.",
 "Baja por la jerarquia de modos en el orden que el texto la ordena: la videollamada es la segunda mejor si tienes conexion rapida; si la conexion es mala, usa el telefono para la voz y el video como extra, silenciando el ordenador; el telefono es el tercero; y el correo y el mensaje se evitan siempre que sea posible.",
 "Cuenta con lo que el texto contesta a la sensacion de que escribir es mas rapido: pensando en todas las veces que tuvo que pasar horas deshaciendo un malentendido nacido de un correo mal entendido, sale mas rapido andar por el pasillo o coger el telefono.",
 "Combina modos cuando el asunto lo pida, como el texto lo reparte: elogiar en una reunion general es buena via para compartir logros importantes, seguirlo en persona en una reunion uno a uno pesa mas emocionalmente, y seguirlo con un correo a todo el equipo pesa mas de forma duradera.",
 "Si tienes que criticar o corregir a alguien por correo, no respondas a todos. Nunca.",
 "Aunque haya un error de hecho pequenio que haya salido a mucha gente, responde solo a la persona que lo cometio y pidele que responda ella a todos.",
 "Para el elogio de cosas pequenias si vale un correo rapido con copia a todos, que segun el texto cuesta un momento y demuestra que estas notando y apreciando lo que pasa a tu alrededor. Y si te acuerdas de mencionarlo en persona al cruzarte con la persona, mejor.",
 "Si estas en una oficina remota, o gestionas gente en oficinas remotas, ten interacciones rapidas y frecuentes, que es lo que segun el texto te deja captar las seniales emocionales mas sutiles. El texto lo atribuye a Maurice Tempelsman, su jefe cuando vivia en Rusia, que se marcaba llamarla cada dia desde Nueva York aunque fuera una llamada de tres minutos."
],
"resumen_teorico":"UNIDAD DE ORIGEN: fuentes/scott_radical_candor/cap_09.md, unidad Cap. 6, Guidance. Sale de las lineas 137 a 153, bajo el rotulo In person (if possible), dentro de la seccion GIVING IMPROMPTU GUIDANCE. ES LA PIEZA P11 DE LA FRONTERA DE ESTA VUELTA. POR QUE ES PROCEDIMIENTO Y NO POSTURA, con D.27 delante: la linea 143 dice literalmente When that is the case, here are some things to keep in mind, y detras van CINCO consejos rotulados uno a uno. Y lo que lo hace inequivoco es que el segundo, Hierarchy of modes, pone un ORDEN de medios de trabajo con su condicion cada uno, que es inventario de MEDIOS en el sentido mas literal de D.27: primero en persona, segundo videollamada con conexion rapida, y telefono con video de extra si la conexion es mala, tercero telefono, y correo y mensaje evitados. RELECTURA DE FIDELIDAD D.30 EN EL ACTO: 13 pasos, 13 TRANSCRIPCION, 0 PUENTE. P1 y P2 salen de la linea 139; P3 y P4 de la 141; P5 y P6 de la 145; P7 y P8 de la 147; P9 de la 149; P10, P11 y P12 de la 151; P13 de la 153. EL LIMITE QUE EL TEXTO PONE A SU PROPIA REGLA VA DE PASO Y NO SE CALLA: la linea 145 escribe entre parentesis no despidas a nadie por mensaje, y esa es la frontera de la regla de optimizar por inmediatez. LA CIFRA DE LOS TRES MINUTOS DEL P13 ES DEL TEXTO, en la linea 153, y va dicha como lo que aquel jefe hacia y no como periodo que yo recomiende: el periodo diario tambien es del texto, he made a point of calling me every day. LO QUE NO ESCRIBO: ningun destinatario, ningun responsable y ningun periodo propio. LO QUE EL TEXTO NO DICE Y POR ESO NO ESTA AQUI: cuantos dias son unos pocos dias, que cuenta como algo gordo, ni que hacer cuando no hay ningun modo disponible."
})
