import sys; sys.path.insert(0,'.c9')
from mk import mk
mk({
"id":"elogiar_publico_criticar_privado_sus_tres_matices",
"titulo":"Elogiar en publico y criticar en privado, con las tres cosas que el texto dice que hay que pensar antes de aplicarlo",
"denominaciones":{"nombre_largo":"La regla general del elogio publico y la critica privada, la frontera entre correccion y critica, la adaptacion al gusto de cada uno, y el elogio publico explicado como aprendizaje del grupo","otros_idiomas":[{"idioma":"ingles","termino":"praise in public, criticize in private"},{"idioma":"ingles","termino":"group learning"}],"sigla":""},
"condiciones_activacion":"Cuando vas a decir algo delante de mas gente y tienes que decidir si eso es una correccion que puede ir en publico o una critica que tiene que ir en privado.",
"entregable_esperado":"El elogio dicho en publico de la forma en que a esa persona le sienta mejor y explicado como aprendizaje para todos, y la critica a la persona dicha en privado.",
"pasos_accionables":[
 "Usa como regla general elogiar en publico y criticar en privado, y cuenta con los dos motivos que el texto da: la critica en publico tiende a disparar una reaccion defensiva y le pone mucho mas dificil a la persona aceptar que se ha equivocado y aprender de ello, y el elogio en publico tiende a dar mas peso al elogio y anima a los demas a imitar lo que estuvo bien.",
 "Tratala como regla general y no como regla dura, que es como el texto la presenta antes de poner las tres cosas que hay que pensar.",
 "Distingue la correccion, la observacion de un hecho, el desacuerdo y el debate, que segun el texto son distintos de la critica: es vital poder corregir el trabajo de alguien, hacer una observacion de hecho o tener un debate en publico.",
 "Cuenta con los ejemplares que el texto pone del lado de lo que SI puede ir por correo o en una reunion publica: hay una errata en la diapositiva seis; hay muchas erratas en esta presentacion y por la naturaleza de nuestro trabajo necesitamos ser exactos al cien por cien; hay un monton de erratas aqui pero a estas alturas no importan mucho; te has quedado un cinco por ciento por debajo de tu numero; no estoy de acuerdo con lo que acabas de decir.",
 "Y cuenta con el ejemplar que el texto pone del otro lado, el de criticar a la persona, que tiene que ser conversacion privada: cuando das varias presentaciones importantes plagadas de erratas que un corrector ortografico habria pillado, empiezo a preguntarme que esta pasando, me lo puedes explicar.",
 "Adaptate al gusto de cada persona: aunque a la mayoria le gusta que la elogien en publico, el texto dice que para algunos cualquier mencion publica es un castigo cruel.",
 "Ten claro cual es tu meta al elogiar, que segun el texto es que la persona sepa lo que hizo bien de la forma mas clara posible y de la manera que mejor le haga sentir a ELLA, y no de la manera en que a ti te gustaria oirlo.",
 "Cuando elogies en publico, explica que no lo haces porque la persona quiera elogio publico sino para que todo el mundo aprenda de lo que paso. El texto da la frase: no para avergonzar a fulana, sino para asegurarme de que todos aprendeis de lo que hizo, os voy a contar lo que acaba de conseguir y como lo hizo.",
 "Y cuando quieras fomentar la critica publica para que todos aprendan de los errores de los demas, deja que sea la propia persona quien lo cuente de si misma."
],
"resumen_teorico":"UNIDAD DE ORIGEN: fuentes/scott_radical_candor/cap_09.md, unidad Cap. 6, Guidance. Sale de las lineas 155 a 163, bajo el rotulo Praise in public, criticize in private, dentro de la seccion GIVING IMPROMPTU GUIDANCE. ES LA PIEZA P12 DE LA FRONTERA DE ESTA VUELTA. POR QUE ES PROCEDIMIENTO Y NO POSTURA, con D.27 delante: la linea 157 cierra diciendo Here are some things to think about, y detras van DOS consejos rotulados. Pero lo que de verdad lo saca de la postura no son los dos rotulos sino la linea 159, que pone CINCO frases literales del lado de lo que puede ir en publico y UNA del lado de lo que no: eso es un inventario de objetos de trabajo, y transcribirlo es lo que hace el P4 y el P5. Una regla enunciada sin esa frontera seria una postura con dos palabras clave. RELECTURA DE FIDELIDAD D.30 EN EL ACTO: 9 pasos, 9 TRANSCRIPCION, 0 PUENTE. P1 y P2 salen de la linea 157; P3, P4 y P5 de la 159; P6 y P7 de la 161; P8 y P9 de la 163. LAS SEIS FRASES DEL P4 Y DEL P5 SON LAS DEL LIBRO, traducidas y no reescritas, y van en el orden en que la linea 159 las pone. EL REMITENTE DEL P9 es del texto, que en la linea 163 remite a Whoops-a-Daisy mas adelante en el mismo capitulo: NO declaro esa arista aqui porque el hijo todavia no esta escrito, y va a la cola de aristas del cierre. LO QUE EL TEXTO NO DICE Y POR ESO NO ESTA AQUI: como se averigua el gusto de cada uno antes de la primera vez, ni que se hace cuando una correccion de hecho ya ha salido en publico y la persona se lo toma como critica."
})
