import sys; sys.path.insert(0,'.c9')
from mk import mk
mk({
"id":"evitar_personalizar_guia_aceptar_personal",
"titulo":"Evitar personalizar la guia y aceptar a la vez que para quien la recibe es personal, con la frase que se retira del vocabulario",
"denominaciones":{"nombre_largo":"La diferencia entre cuidar personalmente y personalizar: el error fundamental de atribucion, decir eso esta mal en vez de tu estas mal, y por que no te lo tomes como algo personal es peor que inutil","otros_idiomas":[{"idioma":"ingles","termino":"don't personalize"},{"idioma":"ingles","termino":"fundamental attribution error"}],"sigla":""},
"condiciones_activacion":"Cuando vas a dar elogio o critica y la explicacion que te sale es un rasgo de caracter de la otra persona, o cuando quien la recibe se la toma como algo personal.",
"entregable_esperado":"La guia dicha sobre lo que se hizo y no sobre quien es la persona, y la reaccion emocional de quien la recibe reconocida en vez de negada.",
"pasos_accionables":[
 "Distingue cuidar personalmente de personalizar, que es la distincion con la que el texto abre: cuidar personalmente es bueno, personalizar es malo.",
 "Cuenta con lo que es el error fundamental de atribucion, que el texto atribuye a Lee Ross, psicologo social de Stanford: usar atributos de personalidad percibidos, del estilo de eres tonto, vago, avaricioso, hipocrita o un imbecil, para explicar el comportamiento de otro, en vez de considerar tu propio comportamiento o los factores de la situacion, que probablemente fueron la causa real.",
 "Cuenta con los dos motivos por los que el texto dice que eso es un problema: primero, que suele ser inexacto; y segundo, que convierte un problema por lo demas resoluble en algo muy dificil de arreglar, porque cambiar atributos centrales de personalidad es muy dificil y lleva muchisimo tiempo.",
 "Pillate a ti mismo cuando pienses o digas tu eres, seguido de lo que sea.",
 "Usa entonces las tecnicas de situacion, comportamiento e impacto, o la de la columna de la izquierda, para ser humilde y evitar personalizar.",
 "Di eso esta mal y no tu estas mal. El texto cuenta que a un colega suyo con fama injusta de imbecil le dio la vuelta a su reputacion con ese solo cambio: dejo de decir tu estas mal y aprendio a decir creo que eso esta mal.",
 "Cuenta con el desglose que el texto hace de por que ese cambio funciona: el creo que es mas humilde, y decir eso en vez de tu no personaliza.",
 "Cuando una discusion sea sobre un asunto, mantenla sobre el asunto. El texto avisa de que las discusiones sobre algo simple, del estilo de si vamos a la izquierda o a la derecha, o si el boton va arriba o abajo, se convierten demasiado a menudo en un concurso de egos, y de que personalizar sin necesidad solo hace mas dificil resolver el asunto.",
 "Elimina de tu vocabulario la frase no te lo tomes como algo personal, que el texto llama peor que inutil.",
 "Cuenta con el motivo que el texto da: aunque des todos los pasos anteriores y no personalices, la guia SI es personal para quien la recibe, porque la mayoria volcamos mas tiempo y energia en nuestro trabajo que en ninguna otra cosa, y el trabajo es parte de quienes somos. Decir no te lo tomes como algo personal es negar esos sentimientos, como decir no estes triste o no te enfades.",
 "Trata como parte de tu trabajo reconocer y manejar las respuestas emocionales, y no descartarlas ni evitarlas.",
 "Cuando lo que tengas que decir sea de verdad personal y no sobre el trabajo, haz lo que el texto describe que hizo: lleva la conversacion al efecto sobre los demas y no a la persona, no seas prescriptivo sobre la solucion porque puede haber una causa que no conoces, y deja claro a la vez que la situacion tal como esta le esta minando un desempenio que por lo demas es fuerte."
],
"resumen_teorico":"UNIDAD DE ORIGEN: fuentes/scott_radical_candor/cap_09.md, unidad Cap. 6, Guidance. Sale de las lineas 165 a 177, bajo el rotulo Don't personalize, dentro de la seccion GIVING IMPROMPTU GUIDANCE. ES LA PIEZA P13 DE LA FRONTERA DE ESTA VUELTA, y la ultima de las seis condiciones que la seccion pone a la guia. POR QUE ES PROCEDIMIENTO Y NO POSTURA, con D.27 delante: la linea 167 dice Here are some tips that can help you avoid personalizing but accept it when people take what you say personally, y detras van CUATRO consejos rotulados uno a uno. Y el inventario es de MEDIOS con su acto: pillarse diciendo tu eres, usar las dos tecnicas del rotulo Be humble, cambiar tu estas mal por creo que eso esta mal, y retirar una frase concreta del vocabulario. RELECTURA DE FIDELIDAD D.30 EN EL ACTO: 12 pasos, 12 TRANSCRIPCION, 0 PUENTE. P1 sale de la linea 167; P2, P3, P4 y P5 de la 169; P6 y P7 de la 171; P8 de la 173; P9, P10 y P11 de la 175; P12 de la 177. EL P5 REMITE A DOS TECNICAS QUE VIVEN EN OTRA PIEZA de este mismo capitulo, y eso lo escribe la linea 169 literalmente: no es un puente mio, es el propio libro remitiendo a su rotulo Be humble. La arista a dar_guia_humilde_tres_tecnicas va a la cola del cierre, porque los dos extremos viven hoy en cuarentena. EL CASO DEL OLOR CORPORAL DE LA LINEA 177 NO VA DE CASO SINO DESTILADO EN EL P12, y lo digo porque es la decision mas discutible de este candidato: el rotulo es imperativo, How not to personalize even when it really is personal, y lo que el caso ensenia son tres actos que el texto escribe uno a uno, llevar la conversacion a las narices de los colegas y no a sus axilas, no ser prescriptivo sobre la solucion, y dejar claro que el statu quo le mina el desempenio. El P12 transcribe esos tres actos sin el dato del caso, que es justo la senial barata que el manual 3.5 da para saber si se hizo mal. LO QUE EL TEXTO NO DICE Y POR ESO NO ESTA AQUI: que hacer si la persona niega el problema personal, ni cuanto se espera antes de volver sobre el."
})
