import sys; sys.path.insert(0,'.c9')
from mk import mk
mk({
"id":"medir_guia_propia_pegatinas_marco",
"titulo":"Medir tu propia guia con el marco y las pegatinas de colores, coger la linea base y seguir tus mejoras",
"denominaciones":{"nombre_largo":"La guia sobre tu guia: el marco impreso junto a tu mesa, una pegatina por color y por cuadrante, la cuenta semanal, y que hacer segun donde caigan","otros_idiomas":[{"idioma":"ingles","termino":"gauge your impromptu guidance, get a baseline, track your improvements"}],"sigla":""},
"condiciones_activacion":"Cuando ya estas dando guia y no sabes como esta cayendo, que es lo que el texto plantea como el problema de medir en el oido del oyente y no en la boca del hablante.",
"entregable_esperado":"Una linea base de donde cae tu guia segun tu propio equipo, seguida en el tiempo, y la correccion de rumbo que esa lectura indique.",
"pasos_accionables":[
 "Acepta lo que el texto contesta a la pregunta de si de verdad hace falta recibir guia sobre tu guia: si. Y cuenta con lo que aniade, que puede costar quince segundos.",
 "Explica el marco a tu equipo y pideles que midan tu guia cada semana.",
 "Sigue tu progreso en el tiempo, preguntandote si te estas moviendo hacia la franqueza radical o alejandote de ella.",
 "Pon una copia del marco cerca de tu mesa, que es la via de baja tecnologia que el texto describe.",
 "Deja pegatinas al lado, de un color para el elogio y de otro para la critica.",
 "Pide a la gente que ponga pegatinas en el cuadrante que mejor describa vuestras interacciones mas recientes.",
 "Cuenta con los cuatro casos que el texto nombra uno a uno: si alguien siente que fuiste innecesariamente duro, pone una pegatina de critica en el cuadrante de la agresion odiosa; si siente que te contuviste, la pone en el de la empatia ruinosa; si siente que repartiste demasiados buen trabajo o que orgulloso estoy de ti vacios solo para que se sintiera mejor, pone una pegatina de elogio en la empatia ruinosa; y si siente que le dijiste que lo hizo bien y a otro le dijiste que lo hizo mal, pone una pegatina de elogio en la insinceridad manipuladora.",
 "Cuenta con las cuatro cosas que el texto dice que pedir esa medicion consigue, numeradas por el mismo: uno, expone a la gente a diario al marco, lo que les ayuda a entender que cuando los desafias lo haces porque te importan; dos, con un vocabulario compartido los colegas tienden a pedirte que seas radicalmente franco, lo que hace mucho mas facil superar el sindrome de si no tienes nada bueno que decir no digas nada; tres, la senial visual es un recordatorio que te empuja a ser radicalmente franco cuando el calor del momento tira de ti en otra direccion; y cuatro, si se lo pides y no lo hacen, o si mandan las puntuaciones de forma anonima, tienes una buena senial de que no se fian de como vas a reaccionar.",
 "Si te sale esa cuarta senial, vuelve atras y trabaja en pedir guia radicalmente franca, demostrandole a tu equipo que no los vas a castigar por criticarte.",
 "Lee la medicion para decidir que corregir, como el texto lo ejemplifica: si ves que varias personas etiquetan tanto tu elogio como tu critica en el cuadrante de la empatia ruinosa, sabes que no estas desafiando a la gente lo bastante directamente ni con el elogio ni con la critica, y entonces tienes que centrarte en dar elogio mas especifico y mas sincero y en simplemente decirlo cuando critiques.",
 "Cuenta con que el camino desde la empatia ruinosa puede no ser directo: el texto dice que a veces hay que sobrecorregir y pasar por el cuadrante que mas se teme, el de la agresion odiosa, antes de llegar a la franqueza radical, y que si ese es tu caso vas en la direccion correcta y no debes pararte ahi.",
 "Cuenta con que vas a tener semanas buenas y semanas malas, y con lo que el texto concluye de eso: no puedes arreglarte de una vez por todas, tienes que gestionarte a ti mismo a diario, y recibir de otros una senial de si te acercas o te alejas ayuda de verdad.",
 "Escucha como se sienten con la guia que les estas dando, que es lo que el texto pone como lo mas importante, y ayudales a entender que cuando los desafias es porque te importa no solo su crecimiento profesional sino ellos como personas."
],
"resumen_teorico":"UNIDAD DE ORIGEN: fuentes/scott_radical_candor/cap_09.md, unidad Cap. 6, Guidance. Sale de las lineas 179 a 203, bajo el rotulo de seccion GAUGE YOUR IMPROMPTU GUIDANCE, GET A BASELINE, TRACK YOUR IMPROVEMENTS. ES LA PIEZA P14 DE LA FRONTERA DE ESTA VUELTA. POR QUE ES PROCEDIMIENTO Y NO POSTURA, con D.27 delante: la linea 185 pone el montaje entero con sus objetos de trabajo nombrados uno a uno, la copia del marco junto a la mesa, las pegatinas, un color para el elogio y otro para la critica, y los CUATRO casos de que pegatina va en que cuadrante. Eso es inventario de MEDIOS y de OBJETOS en el sentido mas literal de D.27, y escribir los pasos es transcribirlo. La linea 189 aniade una segunda enumeracion que el propio texto numera con One, Two, Three, Four. RELECTURA DE FIDELIDAD D.30 EN EL ACTO: 13 pasos, 13 TRANSCRIPCION, 0 PUENTE. P1 sale de la linea 181; P2 y P3 de la 183; P4, P5, P6 y P7 de la 185; P8 y P9 de la 189; P10 de la 191; P11 de las lineas 193 y 195; P12 de la 197; P13 de la 203. EL PERIODO SEMANAL DEL P2 ES DEL TEXTO, linea 183, ask them to gauge your guidance each week, y el diario del P12 tambien, you have to manage yourself, daily. No pongo ningun otro. LA CUENTA DE CUATRO DEL P8 LA HACE EL PROPIO LIBRO con One, Two, Three, Four, asi que la transcribo con su cuenta; la de cuatro del P7 la cuento yo sobre cuatro casos que el texto pone sin numerar, y por eso el paso dice los cuatro casos que el texto nombra uno a uno y no que el texto diga cuatro. ES LA MISMA DISTINCION DE D.37 aplicada dentro de un paso: una cuenta es del libro solo si el libro la escribe. EL CASO DE APPLE de la linea 187 va como ejemplo nombrado y no de paso. LA REMISION AL EPILOGO de la linea 203 no se convierte en paso ni en arista: el epilogo no esta minado y no existe el otro extremo. LO QUE EL TEXTO NO DICE Y POR ESO NO ESTA AQUI: cuanto tiempo se deja el marco puesto antes de leer la linea base, ni que se hace con las pegatinas viejas."
})
