import sys; sys.path.insert(0,'.c9')
from mk import mk
mk({
"id":"organizar_sistema_recoger_quejas_equipo",
"titulo":"Organizar un sistema para que el equipo te haga llegar sugerencias y quejas, en vez de anunciar que se sientan libres",
"denominaciones":{"nombre_largo":"Hacer que criticarte no solo sea seguro sino natural: un sistema organizado y no elaborado, con la caja naranja de Michael Dearing como ejemplar","otros_idiomas":[{"idioma":"ingles","termino":"make it not just safe but natural to criticize you"},{"idioma":"ingles","termino":"orange box"}],"sigla":""},
"condiciones_activacion":"Cuando quieres que tu equipo te haga llegar sugerencias y quejas y lo unico que has hecho es decir que se sientan libres de hacerlo.",
"entregable_esperado":"Un sistema organizado y sencillo por el que las preguntas y las quejas llegan y se contestan a la vista de todos, hasta que deja de hacer falta.",
"pasos_accionables":[
 "Cuenta con la diferencia que el texto marca entre las dos redacciones del credo original de Johnson and Johnson: la primera decia que los empleados deben tener un sistema organizado para sugerencias y quejas, y al reescribirlo se aguo en la afirmacion mucho mas vaga de que los empleados deben sentirse libres de hacer sugerencias y quejas.",
 "No te quedes en anunciar como deben sentirse tus empleados: el texto dice que si eres el jefe tienes que hacerlo mucho mejor que eso.",
 "Toma acciones concretas que aseguren que hacer sugerencias y quejas no solo es seguro sino esperado, porque segun el texto la gente no se va a sentir libre si no las tomas.",
 "Organiza un sistema. Y cuenta con el limite que el texto pone en la frase siguiente: no hace falta que sea elaborado.",
 "Copia la mecanica del ejemplar que el texto da, la caja naranja de Michael Dearing: pon una caja con una ranura en la tapa en una zona de mucho paso, para que la gente pueda echar dentro preguntas o comentarios.",
 "En tu reunion general, mete la mano en la caja y contesta sobre la marcha.",
 "Trata cada pregunta con respeto y a fondo por banal que sea, que es lo que el texto destaca de como aquel lo hacia, y no te muestres molesto ni impaciente.",
 "Demuestrale al equipo que vas a arreglar los problemas cuando te los senialen, en vez de matar al mensajero, que es lo que segun el texto acabo construyendo una cultura donde la gente le desafiaba directamente.",
 "Cuenta con lo que el texto dice que pasa entonces, y que es la senial de que el sistema ha hecho su trabajo: con el tiempo la caja se vacio, y cuando alguien tenia un asunto se levantaba y preguntaba directamente, o se pasaba por su sitio."
],
"resumen_teorico":"UNIDAD DE ORIGEN: fuentes/scott_radical_candor/cap_09.md, unidad Cap. 6, Guidance. Sale de las lineas 55 a 63, bajo el rotulo ORANGE BOX y su titulo Make it not just safe but natural to criticize you, dentro de la seccion SOLICITING IMPROMPTU GUIDANCE. ES LA PIEZA P5 DE LA FRONTERA DE ESTA VUELTA Y ES MI DISCUTIBLE 2, y lo marco antes de saber si acierto. POR QUE LO EXTRAIGO, con el manual 3.5 delante: la linea 59 pone la doctrina en imperativo y sin caso ninguno, You have to organize a system. But it needn't be elaborate, mas la contraposicion entera de las dos redacciones del credo. El caso de Michael Dearing y su caja naranja viene DESPUES, en las lineas 61 y 63, y entra aqui como EJEMPLO NOMBRADO DENTRO de la doctrina, que es exactamente lo que el manual 3.5 manda. LA SENIAL BARATA DE QUE SE HIZO MAL, que el propio manual da, es que el entregable lleve un dato del caso: el entregable de este nodo no nombra ni la caja, ni el color naranja, ni a Dearing, ni a eBay. POR QUE ES DISCUTIBLE DE TODAS FORMAS: los pasos P5 a P9 SI llevan la mecanica del caso, y alguien puede leer que la casa es el caso y no la doctrina. Lo que me decide es que la linea 59 ordena organizar un sistema y declara que no necesita ser elaborado, y sin una mecanica concreta detras ese mandato es exactamente el adjetivo de adecuacion que D.27 restriccion 2 tumba: un sistema adecuado. El caso es lo unico que lo convierte en procedimentable, y por eso va dentro y no fuera. RELECTURA DE FIDELIDAD D.30 EN EL ACTO: 9 pasos, 9 TRANSCRIPCION, 0 PUENTE. P1, P2, P3 y P4 salen de la linea 59; P5, P6, P7 y P8 de la 61; P9 de la 63. NO ESCRIBO PERIODO: el texto no dice cada cuanto se vacia la caja ni cada cuanto se contesta, y la unica cadencia que aparece es la de la reunion general, que es la que el texto nombra. NO ESCRIBO RESPONSABLE: el texto no dice quien lee la caja. LO QUE EL TEXTO NO DICE Y POR ESO NO ESTA AQUI: que se hace con una pregunta que no se puede contestar en publico, ni cuanto se tarda en que la caja se vacie."
})
