import sys; sys.path.insert(0,'.c9')
from mk import mk
mk({
"id":"fomentar_guia_entre_pares_equipo",
"titulo":"Fomentar la guia entre pares con el premio nominado y la metedura de pata contada por uno mismo, y no con una herramienta que la sustituya",
"denominaciones":{"nombre_largo":"La guia entre companieros: la conversacion en persona antes que la herramienta, el premio que nomina el ganador anterior, la metedura de pata auto nominada con perdon automatico, y la medicion entre pares","otros_idiomas":[{"idioma":"ingles","termino":"peer guidance"},{"idioma":"ingles","termino":"Whoops-a-Daisy"},{"idioma":"ingles","termino":"peer gauging"}],"sigla":""},
"condiciones_activacion":"Cuando quieres que la gente de tu equipo se de guia entre si, y la salida facil es comprar una herramienta que recoja textos y los reparta.",
"entregable_esperado":"Companieros que se cuentan en voz alta el trabajo extraordinario del otro y los errores propios, con perdon automatico, y un vocabulario compartido para medir la guia entre pares.",
"pasos_accionables":[
 "Recuerda que la buena guia tiene que pasar en una conversacion y en persona, que es con lo que el texto abre esta seccion.",
 "No sustituyas esa conversacion por una herramienta de las que piden a los usuarios escribir trocitos de texto que despues se reparten y se registran con una capa de analitica encima. El texto dice que parecen pulidas pero que al final son un paso de gigante en la direccion equivocada para las relaciones, un poco como cortar con alguien por mensaje.",
 "Anima tu, como responsable, a que tu equipo se tome el tiempo de hablar entre si.",
 "Copia la mecanica del sistema que el texto atribuye a Dan Woods, y que describe como el mas barato, de menos tecnologia y mas eficaz que ha visto: dos peluches, una ballena y un mono.",
 "En cada reunion general, invita a la gente a nominarse unos a otros para ganar la ballena durante una semana.",
 "Cuenta con lo que ese premio busca, que es lo que el texto pone como la idea: conseguir que gente del equipo se levante y hable de algun trabajo extraordinario que le haya visto hacer a otro.",
 "Deja que quien gano la ballena la semana anterior decida quien la merece esta semana.",
 "Y despues, pide que la gente se nomine a si misma para el peluche de la metedura de pata: quien la haya liado esa semana puede levantarse, contar la historia, recibir perdon automatico y ayudar a evitar que otro cometa el mismo error.",
 "Cuenta con lo que el texto avisa que pasa la primera vez: silencio. Y con lo que el hizo para romperlo, que fue poner veinte dolares sobre la cabeza del peluche, para que la gente pudiera fingir que no se sumaba al peluche sino que iba por el dinero.",
 "Cuenta con las dos cosas que esa practica consigue segun el texto: hace seguro equivocarse, y por tanto innovar; y acelera la resolucion de problemas que si no se habrian enquistado.",
 "Comprueba antes si esa practica encaja donde estas, que es el limite que el texto pone a su propio ejemplo: en un sitio de medir dos veces y cortar una habria sido publicidad enganiosa, y en sectores como la aviacion bromear sobre las meteduras de pata seria sencillamente inapropiado.",
 "Explica el marco de la franqueza radical a tu equipo como segunda via para que hablen entre ellos, contandoles como les pides a ellos que midan la guia que tu das para poder mejorarla.",
 "Animalos a medir la guia que se dan entre pares, porque segun el texto tener un vocabulario compartido ayuda a que tu cultura se mueva hacia la franqueza radical."
],
"resumen_teorico":"UNIDAD DE ORIGEN: fuentes/scott_radical_candor/cap_09.md, unidad Cap. 6, Guidance. Sale de las lineas 369 a 381, bajo el rotulo de seccion PEER GUIDANCE. ES LA PIEZA P26 DE LA FRONTERA DE ESTA VUELTA. POR QUE ES PROCEDIMIENTO Y NO POSTURA, con D.27 delante: son DOS consejos rotulados por el libro, Whoops-a-Daisy y Peer gauging, y el primero trae la mecanica entera con sus objetos de trabajo nombrados uno a uno, los dos peluches, la nominacion cruzada en la reunion general, el ganador anterior decidiendo el siguiente, la auto nominacion con perdon automatico, y hasta el remedio para el silencio inicial. Eso es inventario de MEDIOS y de OBJETOS, no de metas. EL CASO NO ES LA CASA Y EL PROPIO TEXTO LO AYUDA: las lineas 375 y 377 ponen el LIMITE de su propio ejemplo, que en un sitio de medir dos veces y cortar una habria sido publicidad enganiosa y que en aviacion seria inapropiado, y ese limite va de paso, el P11, porque una mecanica copiada sin su limite queda mas ancha que el libro. RELECTURA DE FIDELIDAD D.30 EN EL ACTO: 13 pasos, 13 TRANSCRIPCION, 0 PUENTE. P1, P2 y P3 salen de la linea 371; P4 a P10 de la 373; P11 de las lineas 375 y 377; P12 y P13 de la 381. EL SISTEMA DE NOTIFICACION DE SEGURIDAD DE LA AVIACION de la linea 377 y el sistema medico imaginado de la linea 379 NO VAN DE PASO: el primero es el ejemplar con el que el texto explica por que en aviacion no se bromea con esto, y lo que de el va al P11 es solo ese limite; el segundo es una hipotesis que el propio texto plantea en condicional, What if, y una hipotesis no es un acto. Convertirla en paso habria sido el puente mas grande que este capitulo me ofrecia. EL PERIODO SEMANAL DEL P5 Y DEL P7 ES DEL TEXTO, to win the Killer Whale for a week y who deserved the whale this week. LA CIFRA DE LOS VEINTE DOLARES DEL P9 ES DEL TEXTO. LO QUE EL TEXTO NO DICE Y POR ESO NO ESTA AQUI: que se hace cuando nadie nomina a nadie varias semanas seguidas, ni quien decide que un error merece perdon automatico."
})
