#!/bin/sh
# CADENA 2 de la vuelta 38: candidatos 2 y 3 de cap_13, en el orden del libro,
# con la arista de P03 del plan cableada en el mismo acto en que su hijo entra.
. /c/Users/AlexDesk/Documents/forja-nodos/.v38/correr.sh

echo "cadena 2 arrancada (candidatos 2 y 3)" >> .v38/informes/_cadena.txt

corre i02_contar_cuatro.txt contar_cuatro_historias_propias_ver_hueco_intencion \
 --veredicto "contar_historias_propias_explicar_franqueza_radical|CONTINUA|madre=contar_historias_propias_explicar_franqueza_radical|ARISTA D.29 QUE ESPERABA EN COLA DESDE LA LINEA 473 DE LA BITACORA, Y LA DECLARA EL PROPIO LIBRO: cap_13 L43 escribe There's a brief paragraph about this in the final Getting Started section, but we have been asked for more detail about how to do this and why it works, y ese brief paragraph es la madre. El paso 4 de la madre manda buscar cual es TU version de la historia del um o de la de Bob y ahi se acaba; este pone las CUATRO historias con su pregunta de arranque escrita, la de franqueza radical en L45, la de agresion odiosa en L49, la de empatia ruinosa en L51 y la de insinceridad manipuladora en L53, en 17 pasos que la madre no tiene. Es la fila 42 de la deuda declarada en la vuelta 23. Cuando la madre entro, en la vuelta 37, este candidato seguia en la bandeja: la cola se cierra hoy." \
 --veredicto "mejorar_consciencia_propia_relacional_dos_practicas|CONTINUA|madre=mejorar_consciencia_propia_relacional_dos_practicas|ARISTA D.37 Y LA CUENTA ESTA ESCRITA, que es la condicion literal de la regla: cap_13 L39 dice We have developed TWO practices, storytelling and role plays, o sea que dice CUANTAS partes tiene Y LAS NOMBRA. El paso 11 de la madre es Haz la primera, contar historias, que el texto despliega bajo el rotulo cual es tu historia, y ahi se acaba. Este es esa primera y la despliega en 17 pasos que la madre no tiene. La madre entro hace un momento en esta misma vuelta, asi que la arista se cablea en el acto y no espera a que ninguna senial la levante, que es lo que D.37 manda. Es la fila 43 de la deuda declarada en la vuelta 23." \
 --veredicto "evitar_presion_social_actos_equipo|SANO|OTRA VEZ UNA FORMULA MIA Y NO UN OBJETO COMPARTIDO: lo que la senial cruza es que mi paso 16 y su paso 6 empiezan los dos por Y cuenta con lo que el texto dice. Abriendo los dos: aquel evita que un acto divertido no obligatorio se sienta obligatorio y entrega el acto al que va quien quiere ir, sin nadie arrastrado por la presion social; este desentierra tus cuatro historias del marco de la franqueza radical y entrega el hueco entre tus intenciones y tu impacto puesto a la vista. Ni la misma activacion, ni el mismo entregable, ni un solo acto en comun, y ninguno de los dos nombra el procedimiento del otro en ninguna linea." \
 --censo "serie=las dos practicas que el texto desarrolla;papel=paso;cabeza=mejorar_consciencia_propia_relacional_dos_practicas" $COMUN

arista ar_p03_historias.txt desplegar_plan_orden_operaciones_franqueza_radical contar_cuatro_historias_propias_ver_hueco_intencion 3 \
"ARISTA D.29 ADJUDICADA POR LA ACTA 36 PUNTO 3.6, CABLEADA EN EL ACTO EN QUE SU HIJO ENTRA. Mi paso 3 remite al epilogo nombrando cuatro cosas, y es cap_12 L13: So for more detailed advice on sharing your stories, soliciting criticism, giving praise, and gauging your criticism see the Afterword. La primera de las cuatro, compartir tus historias, tiene destino UNICO dentro del epilogo: la seccion Practice: What's your story? de cap_13 L41, que es este hijo. Mi paso 3 la nombra y manda al capitulo, y ahi se acaba: no dice ni cuales son las cuatro historias, ni su pregunta de arranque, ni el hueco entre intencion e impacto. LA RAZON DE FONDO ES LA DE LA ACTA 36: esta misma figura, un paso que nombra y remite a otro capitulo, ya cableo cuatro aristas de este mismo nodo en la vuelta 37 (P30, P32 y las dos de P33), y una vara no puede dar dos respuestas a la misma figura. Las otras dos de este paso 3, dar elogio y medir tu critica, NO se cablean en esta vuelta porque sus hijos siguen en la bandeja, y quedan escritas aqui para que no se pierdan, que es lo que D.29 pide de una arista que espera."

corre i03_triangulo.txt practicar_triangulo_critica_tres_papeles \
 --veredicto "mejorar_consciencia_propia_relacional_dos_practicas|CONTINUA|madre=mejorar_consciencia_propia_relacional_dos_practicas|ARISTA D.37 Y LA CUENTA ESTA ESCRITA: cap_13 L39 dice We have developed TWO practices, storytelling and role plays. El paso 12 de la madre es Haz la segunda, el juego de papeles, que el texto despliega bajo el rotulo el triangulo de la critica, y ahi se acaba. Este es esa segunda y la despliega en 15 pasos de L59 a L72 que la madre no tiene: el grupo de tres, quien describe la critica que no dio, quien hace de destinatario exagerando la respuesta defensiva, quien observa con el marco de dos por dos, y los cuatro desplomes de conversacion que hay que cazar. Con este cable la serie de dos queda completa en la misma vuelta que sus dos partes, que es lo que D.37 manda. Es la fila 44 de la deuda declarada en la vuelta 23." \
 --veredicto "abrazar_incomodidad_silencio_contar_seis|SANO|LO QUE LA SENIAL VE ES QUE LOS DOS SON EJERCICIOS CON OTRA PERSONA, y el objeto es otro. Aquel aguanta EL SILENCIO despues de que TU hayas pedido critica, contando hasta seis en tu cabeza, y entrega el silencio aguantado hasta el final con la respuesta del otro salida de el; este monta un TRIANGULO DE TRES PAPELES para que TU DES una critica que no diste y entrega el recorrido de esa conversacion dibujado sobre el marco de dos por dos por un observador. Son dos personas contra tres, es recibir contra dar, y ninguno de los dos sirve para lo del otro. El vecino sigue en la bandeja de este mismo capitulo, asi que el par lo levanta la poblacion de D.38.5, grafo mas bandejas." \
 --veredicto "escuchar_entender_critica_dominar_defensa|SANO|MISMA FAMILIA DE CAPITULO Y NI UN ACTO COMPARTIDO. Aquel domina TU PROPIA DEFENSA cuando la critica te llega a ti, con el ejercicio de escuchar tres minutos sin interrumpir, y entrega la critica escuchada entera sin respuesta defensiva; este te pone a DAR una critica que no diste y a que otros dos vean como aterriza, y entrega el impacto real de tus palabras devuelto por quien la recibio. Comparten que se practican con otra gente, que es forma y no objeto. El vecino sigue en la bandeja, asi que el par lo levanta la poblacion de D.38.5." \
 --censo "serie=las dos practicas que el texto desarrolla;papel=paso;cabeza=mejorar_consciencia_propia_relacional_dos_practicas" $COMUN

echo "cadena 2 terminada" >> .v38/informes/_cadena.txt
