#!/bin/sh
# CADENA 1 de la vuelta 38: las dos aristas cuyos DOS extremos ya viven en el grafo,
# que no esperan a ningun candidato, y el candidato 1 de 6 de cap_13.
. /c/Users/AlexDesk/Documents/forja-nodos/.v38/correr.sh

echo "cadena 1 arrancada (las dos aristas de extremos dentro, y el candidato 1)" >> .v38/informes/_cadena.txt

arista ar_marco.txt desplegar_plan_orden_operaciones_franqueza_radical desplegar_marco_franqueza_radical 8 \
"ARISTA D.29 QUE EL ENCARGO DE LA VUELTA 38 ME MANDA DECIDIR LEYENDO LOS PASOS, Y LA DIRECCION ES ESTA. Mi paso 8 es cap_12 L21 y dice: si quieres, copia el marco de la franqueza radical del capitulo dos y lleva ahi la cuenta de quien te dice que. La primera mitad de ese paso, copia el marco, nombra el procedimiento del hijo y ahi se acaba. Los pasos 2 a 5 del hijo son literalmente como se copia: recorta el marco del propio libro, haz fotocopias, ponlas en tu nevera o encima de tu mesa, comparte copias con tus colegas. NOMBRAR NO ES PROCEDIMENTAR, y el que nombra es la madre. LO QUE TUMBA LA DIRECCION CONTRARIA: para que el hijo fuera la madre, alguno de sus nueve pasos tendria que nombrar el plan del orden de operaciones, y ninguno lo hace. Y LO QUE ESTA ARISTA NO RESUELVE, que lo digo yo: la SEGUNDA mitad de mi paso 8, lleva ahi la cuenta de quien te dice que, choca con el paso 8 del hijo, No escribas nombres en las casillas. Esa contradiccion es del propio libro en dos sitios distintos, sube a la cola de doctrina de esta vuelta y NO la toca este cable, que cuelga solo de la primera mitad. El par fue juzgado SANO en la vuelta 37 y la ACTA 36 lo sostuvo con la formula clase SI, arista NO: esto es la arista que aquella adjudicacion dejo encargada."

arista ar_empezar.txt empezar_cultura_franqueza_radical contar_historias_propias_explicar_franqueza_radical 2 \
"ARISTA D.29 QUE LA ACTA 36 PUNTO 4 DEJA ENCARGADA Y CUYOS DOS EXTREMOS YA VIVEN EN EL GRAFO. Mi paso 2 es Empieza explicando la idea, y ahi se acaba: la frase entera del paso son cinco palabras y no dice ni con que se explica ni como. El hijo pone los seis medios de explicarla en ocho pasos de cap_12 L17: explicarla con tus propias palabras, pedirles que lean el libro, ensenarles los videos de la web de la franqueza radical, buscar tu version de la historia del um, buscar tu version de la de Bob, y mostrar algo de vulnerabilidad. NINGUNA SENIAL LA LEVANTA y la caza la lectura, que es EXTRACTOR.md 11. El par ya fue juzgado SANO al insertar el hijo en la vuelta 37, con la razon de que comparten un solo acto y los dos tienen procedimiento fuera de el; esto no reabre aquel veredicto de CLASE, declara la arista que aquella lectura dejo sin cablear, que es lo que D.29 llama un hueco de declaracion y no una contradiccion."

corre i01_mejorar_consciencia.txt mejorar_consciencia_propia_relacional_dos_practicas \
 --veredicto "desplegar_plan_orden_operaciones_franqueza_radical|SANO|LO QUE LOS JUNTA ES UNA FORMULA MIA Y NO SU OBJETO: la senial cruza mi paso 11 con su paso 4 porque los dos nombran LA PRIMERA PARTE por su rotulo. Pero la primera de cada uno es otra cosa, y eso se ve abriendo las dos lineas. La del plan es cap_12 L15, SHARE YOUR STORIES, que es la etapa de explicar la franqueza radical AL EQUIPO. La mia es cap_13 L41, Practice: What's your story?, que es el ejercicio de desenterrar TUS CUATRO HISTORIAS. Aquel ordena las etapas de un despliegue sobre el equipo y entrega el plan recorrido; este ordena DOS PRACTICAS SOBRE TI MISMO y entrega tus dos consciencias distinguidas y trabajadas, que es justo lo que su L21 anuncia, there is one common thread every time: you. Ninguno de los dos despliega al otro, y ninguno lo nombra en una linea." \
 --censo "serie=las dos practicas que el texto desarrolla;papel=cabeza;nota=la cuenta esta escrita en cap_13 L39, We have developed two practices, storytelling and role plays" $COMUN

echo "cadena 1 terminada" >> .v38/informes/_cadena.txt
