#!/bin/sh
# CADENA 3 de la vuelta 38: el candidato 4, que es cabeza de DOS series, con la arista
# de P03 del plan y la arista 50 que yo adjudico en esta vuelta, las dos en el mismo acto.
. /c/Users/AlexDesk/Documents/forja-nodos/.v38/correr.sh

echo "cadena 3 arrancada (candidato 4)" >> .v38/informes/_cadena.txt

corre i04_pedir_critica_primero.txt pedir_critica_primero_crear_seguridad_psicologica \
 --veredicto "empezar_cultura_franqueza_radical|CONTINUA|madre=empezar_cultura_franqueza_radical|ESTE ES EL PAR MAS CARO DEL CAPITULO Y VENIA MARCADO COMO DISCUTIBLE DESDE LA VUELTA 37: la ACTA 36 punto 3.5 lo dejo sostenido en su lectura y con su dato sin existir, porque el candidato seguia en la bandeja. Hoy existe y lo juzgo yo. MI VEREDICTO ES CONTINUA Y NO REPITE, y la razon la escribe el propio libro: cap_13 L87 dice The first edition describes this order of operations, o sea que reconoce que las dos listas son LA MISMA, y aun asi escribe el capitulo entero porque la primera no bastaba. QUE ANIADE EL HIJO A LA MADRE, medido paso a paso: la madre tiene el orden EN PROSA y solo hasta su tercera etapa (explica la idea, pide que te critiquen, empieza por el elogio y no por la critica, entiende la frontera peligrosa); el hijo trae la lista NUMERADA POR EL PROPIO TEXTO de L77 a L85, y con ella los pasos CUATRO y CINCO que la madre no tiene en ninguna forma, mide la critica y ajusta y fomenta el elogio y la critica entre los demas. Y trae ademas todo el porque medido que la madre no tiene ni insinuado: la definicion de seguridad psicologica de Amy Edmondson en L105, la medicion de Google de L107 con sus cinco dinamicas clave, y el circulo virtuoso de L109. LA MADRE ES LA DE cap_05 PORQUE ES LA QUE NOMBRA Y SE ACABA, y el hijo es el que despliega, que es la vara de siempre." \
 --veredicto "fomentar_guia_reciproca_companieros|CONTINUA|madre=pedir_critica_primero_crear_seguridad_psicologica|ARISTA D.29, QUE ES LA 52 DE LA DEUDA DECLARADA EN LA VUELTA 23. Mi paso 5 es el quinto del orden de operaciones y dice Cinco, fomenta el elogio y la critica entre los demas, que es cap_13 L85 entera, encourage praise and criticism between others, y ahi se acaba: mi paso son ocho palabras. El hijo lo despliega en 13 pasos de cap_09 con lo que yo no tengo: la conversacion en persona que no se sustituye por una herramienta, la mecanica de los dos peluches de Dan Woods, la ballena que se nomina en cada reunion general, el peluche de la metedura de pata con su perdon automatico, los veinte dolares para romper el primer silencio, y el limite de donde esa practica NO encaja. ES D.29 Y NO D.37, y lo digo porque decide como se cita: el texto NUMERA los cinco pasos de L77 a L85 pero NO escribe la palabra cinco, asi que no dice CUANTAS partes tiene y la regla que aplica es la que pide razon escrita." \
 --veredicto "integrar_peticion_critica_rutina_existente|SANO|SON VECINOS DE LINEA Y NO DE OBJETO, y la frontera la escribi yo antes de que la senial dijera nada: mi propia ficha declara que el habito regular de cap_13 L111 NO viaja a mis pasos y que su sede es este vecino, por P.19, porque es el mismo objeto que L239 y lo que P.19 manda es fundirlo en un solo procedimiento en vez de mandarlo a nodo propio. Por eso las dos fichas se tocan en la linea y no en el acto. QUE ENTREGA CADA UNO: yo entrego EL ORDEN DE OPERACIONES RECORRIDO DESDE SU PRIMER PASO, con la critica pedida y respondida bien; aquel entrega LA PETICION METIDA AL FINAL DE TUS REUNIONES A SOLAS ya programadas, anunciada al equipo con la pregunta que vas a hacer. Y SU ACTIVACION LO SEPARA SOLO: aquel arranca cuando YA HAS PRACTICADO LOS CUATRO ELEMENTOS por separado y quieres juntarlos, o sea AGUAS ABAJO de los cuatro que mi paso 17 nombra, no aguas abajo de mi. Aquel no es ninguno de los cuatro y yo no soy su cabeza: el par es SANO. El vecino sigue en la bandeja, asi que lo levanta la poblacion de D.38.5." \
 --censo "serie=los cuatro elementos de pedir critica;papel=cabeza;nota=la cuenta esta escrita en cap_13 L113, each of the four tips for soliciting criticism. Este nodo encabeza ADEMAS una segunda serie, el orden de operaciones de cinco pasos de L77 a L85, que NO es D.37 porque el texto numera sin escribir cuantas son, y por eso ni el id ni el titulo llevan cifra" $COMUN

arista ar_p03_pedir.txt desplegar_plan_orden_operaciones_franqueza_radical pedir_critica_primero_crear_seguridad_psicologica 3 \
"ARISTA D.29 ADJUDICADA POR LA ACTA 36 PUNTO 3.6, CABLEADA EN EL ACTO EN QUE SU HIJO ENTRA. Mi paso 3 remite al epilogo nombrando cuatro cosas, y es cap_12 L13: So for more detailed advice on sharing your stories, soliciting criticism, giving praise, and gauging your criticism see the Afterword. La segunda de las cuatro, pedir critica, tiene destino UNICO dentro del epilogo: la seccion SOLICIT CRITICISM FIRST de cap_13 L73, que es este hijo. Mi paso 3 la nombra y manda al capitulo, y ahi se acaba. Es la segunda de las cuatro aristas que la ACTA 36 adjudico de esta linea; la primera, compartir tus historias, la cablee hace un momento en esta misma vuelta. Las otras dos, dar elogio y medir tu critica, NO se cablean aqui porque sus hijos siguen en la bandeja, y quedan escritas para que no se pierdan."

arista ar_50_criticar.txt pedir_critica_primero_crear_seguridad_psicologica criticar_trabajo_evitar_desanimo 3 \
"LA ARISTA 50 DE LA DEUDA DE LA VUELTA 23, QUE LA VUELTA 37 MARCO COMO DISCUTIBLE 3 SIN LLEGAR A ESCRIBIR SU RAZON, Y QUE LA ACTA 36 PUNTO 3.3 PASO CON DUENO A LA VUELTA QUE INSERTARA ESTE NODO. ADJUDICO QUE SI SE CABLEA. Mi paso 3 es el tercero del orden de operaciones y dice Tres, da critica, que es cap_13 L81 entera, give criticism, y ahi se acaba: mi paso son cuatro palabras. El hijo despliega la etapa en 14 pasos de cap_05 con lo que yo no tengo: criticar el trabajo y no a la persona, el error de atribucion fundamental, averiguar por que el otro hace lo que hace antes de mandar nada, ser humilde y util, darla en persona e inmediatamente, elogiar en publico y criticar en privado, y las dos carpetas del responsable veterano. LA RAZON QUE DECIDE ES LA DE LA ACTA 36 PUNTO 3.6 APLICADA CONTRA MI MISMO: una vara no puede dar dos respuestas a la misma figura dentro de la misma vuelta. Los cinco pasos del orden son la misma figura cinco veces, un paso que nombra la etapa por su rotulo y un hijo que la despliega; si cablear Cinco, fomenta el elogio y la critica entre los demas a fomentar_guia_reciproca_companieros esta bien, cablear Tres, da critica a este hijo esta bien. Y EL REPARO LO ESCRIBO YO PARA QUE SE VEA: este hijo YA TIENE MADRE, empezar_cultura_franqueza_radical, que es la version en prosa del MISMO orden en cap_05, asi que le doy una segunda madre que dice lo mismo. Lo hago igual porque la ACTA 36 punto 3.7 sostuvo una TERCERA madre para abrazar_incomodidad_silencio_contar_seis, o sea que en esta casa un hijo con varias madres no es defecto, y porque L87 dice expresamente que las dos listas son la misma: la duplicidad esta en el libro y no la invento yo. VA MARCADO COMO DISCUTIBLE 2 EN MI REPORTE, y me aparto AL ALZA de lo que la vuelta 37 marco."

echo "cadena 3 terminada" >> .v38/informes/_cadena.txt
