#!/bin/sh
# CADENA 4 de la vuelta 38: los candidatos 5 y 6, que cierran el tramo de seis.
. /c/Users/AlexDesk/Documents/forja-nodos/.v38/correr.sh

echo "cadena 4 arrancada (candidatos 5 y 6)" >> .v38/informes/_cadena.txt

corre i05_elegir_pregunta.txt elegir_pregunta_recurrente_pedir_critica \
 --veredicto "pedir_critica_primero_crear_seguridad_psicologica|CONTINUA|madre=pedir_critica_primero_crear_seguridad_psicologica|ARISTA D.37 Y LA CUENTA ESTA ESCRITA, que es la condicion literal de la regla: cap_13 L113 escribe each of the four tips for soliciting criticism offered in the book, o sea que dice CUANTAS. El paso 17 de la madre las nombra una a una, dar con una pregunta recurrente, abrazar la incomodidad, escuchar con intencion de entender, y hacer tangible la escucha premiando la franqueza, y ahi se acaba. Este es LA PRIMERA de las cuatro y la despliega en 24 pasos de L119 a L165 que la madre no tiene: los cuatro atributos con su rotulo propio, sincera, que no se conteste con un si o un no, concreta contra abierta, y la frecuencia; la correccion que el propio texto hace a la pregunta que recomendaba la primera edicion; nueve preguntas literales; y el ejercicio de probarlas con un companiero de confianza. La madre entro hace un momento en esta misma vuelta, asi que la arista se cablea en el acto, que es lo que D.37 manda. Las otras tres partes de la serie siguen en la bandeja y sus aristas esperan a que entren." \
 --veredicto "abrazar_incomodidad_arrancar_critica_equipo|SANO|COMPARTEN EL ACTO DE PEDIR CRITICA Y NI UN OBJETO. Aquel sale de cap_09, tiene 20 pasos y entrega CRITICA DICHA EN VOZ ALTA POR TU EQUIPO, recibida sin defenderte y premiada de forma visible, con la cuenta semanal de cuanta recibes: su problema es un equipo que no habla. Este entrega TRES O CUATRO PREGUNTAS RECURRENTES TUYAS ESCRITAS Y PROBADAS con un companiero de confianza, evaluadas por si sacaron critica util y por si sonaron naturales: su problema es que no sabes que pregunta hacer. Ninguno de los dos nombra el procedimiento del otro en una linea, y los cuatro atributos de una buena pregunta no estan en aquel." \
 --veredicto "exigir_critica_jefe_reticente|SANO|LA DIRECCION DE LA PETICION ES LA CONTRARIA, y eso los separa solo. Aquel le exige la critica A TU JEFE, que es quien duda en darte una opinion franca, y entrega una valoracion sacada de tu jefe. Este elige las preguntas con las que TU pides critica A TU EQUIPO, y entrega tus preguntas escritas y probadas. Uno mira hacia arriba y otro hacia abajo, y los ejemplares de pregunta de cada uno son distintos: aquel trae las tres frases del texto para un jefe reticente, este los cuatro atributos y las nueve preguntas de cap_13 L141 a L157." \
 --veredicto "pedir_critica_equipo_premiarla|SANO|SON LAS DOS MITADES DISTINTAS DEL MISMO MOMENTO Y NINGUNA DESPLIEGA A LA OTRA. Aquel sale de cap_05 y entrega LA CRITICA PEDIDA ACTIVAMENTE Y NO SOLO CONSENTIDA, recibida sin defenderte, premiada cuando llega por pequenia que sea y con el equipo enterado de que la queja se atendio: su objeto es la CONDUCTA de quien pide. Este entrega LAS PREGUNTAS con las que se pide, escritas, probadas y evaluadas por dos varas: su objeto es la HERRAMIENTA. Aquel no trae ni un atributo de pregunta y este no trae ni una regla de como recibir la respuesta. Comparten el acto de pedir critica y ahi se acaba el parecido." \
 --censo "serie=los cuatro elementos de pedir critica;papel=paso;cabeza=pedir_critica_primero_crear_seguridad_psicologica" $COMUN

corre i06_resolver_dudas.txt resolver_dudas_frecuentes_pedir_critica \
 --veredicto "resolver_dudas_frecuentes_reuniones_salto_nivel|SANO|MISMA FIGURA Y CERO OBJETO COMPARTIDO, y la figura es lo unico que la senial puede ver. Los dos son un bloque de preguntas frecuentes que el libro contesta una a una, y esta casa ya trato el otro como nodo, asi que la forma esta juzgada. Pero aquel contesta las cuatro dudas de UNA REUNION DE SALTO DE NIVEL, el equipo que ya no cree en su jefe, los que no hablan, los que no callan y el equilibrio, y entrega la reunion sacada adelante. Este contesta las dudas de PEDIR CRITICA, la pregunta que se queda rancia, la respuesta sobre algo que no puedes arreglar, el jefe nuevo con gente mayor que el, y el miedo a recibir critica, y entrega cada duda resuelta con la accion que su respuesta encarga. Ni una de las dudas de uno aparece en el otro." \
 --veredicto "despedir_persona_franqueza_radical|SANO|LO QUE LOS CRUZA ES UNA FORMULA Y NO UN OBJETO. Aquel prepara y tiene la conversacion de UN DESPIDO ya decidido, sin distanciarte de la persona, con el problema reformulado en el puesto y con un trabajo siguiente imaginado antes de la reunion. Este resuelve las dudas frecuentes de PEDIR CRITICA, que es la etapa en que todavia no has dado ninguna. Ni la misma activacion, ni el mismo entregable, ni un acto compartido, y ninguno nombra al otro en ninguna linea." \
 --censo "serie=no" $COMUN

echo "cadena 4 terminada" >> .v38/informes/_cadena.txt
