#!/bin/sh
# CANDIDATO 2 de la vuelta 42: premiar_franqueza_hacer_escucha_tangible, pieza 9 de
# cap_13 y CUARTO de los cuatro elementos de pedir critica. CUATRO veredictos: el UNICO
# que levanta la senial, las DOS madres por lectura (la cola 495, D.37, y la arista 57
# de la ACTA 24, D.29) y el par de cap_09 que el candidato trae marcado como discutible.
cd /c/Users/AlexDesk/Documents/forja-nodos
COMUN="--sin-preguntas --censo caso=no --censo marco_pais=no --censo vigencia=no --censo herramienta=no"
{
echo "\$ python forja.py insertar cuarentena/scott_radical_candor/premiar_franqueza_hacer_escucha_tangible.json [4 veredictos y censos]"
python forja.py insertar cuarentena/scott_radical_candor/premiar_franqueza_hacer_escucha_tangible.json \
 --veredicto "escuchar_entender_critica_dominar_defensa|SANO|EL UNICO VECINO QUE LEVANTA LA SENIAL, Y ES MI HERMANO DE SERIE: similitud_texto 0.375, familia_id 0.000, paso_contra_nodo 0.465. LO QUE MIRA ES MI PASO 8 CONTRA SU PASO 5, y las dos lineas abren con practicalo asi, que es el rotulo con el que este capitulo abre todos sus ejercicios: es forma compartida y no objeto compartido. EL PAR YA SE JUZGO HOY DESDE EL OTRO LADO, hace una hora, cuando el entro y yo estaba en la bandeja, y la clase es la misma. Y DIGO LA ASIMETRIA EN VEZ DE CALLARLA: desde su lado la senial dio 0.363 y desde el mio da 0.375, que es la asimetria de difflib que D.29 tiene escrita con sus dos cifras. Los dos somos partes hermanas de la misma cabeza pedir_critica_primero_crear_seguridad_psicologica, nombrados por separado en su paso 17, el tercero y el cuarto de una lista de cuatro, y EXTRACTOR.md 15.6 escribe que un vecino que no es tu parte es hermano y su veredicto es SANO. LO QUE NOS SEPARA: el trabaja TU PROPIA DEFENSA en el instante en que la critica te esta entrando, y entrega la critica escuchada entera sin respuesta defensiva con el ejercicio de los tres minutos hecho. Yo trabajo LO QUE PASA DESPUES de que la critica ya se recibio: arreglar el problema deprisa o explicar por que no puedes, y contarlo en publico con lo que aprendiste. Mi entregable lleva la lista de las tres o cuatro criticas recientes y el relato en una reunion de equipo; el suyo no tiene ni lista ni publico." \
 --veredicto "pedir_critica_primero_crear_seguridad_psicologica|CONTINUA|madre=pedir_critica_primero_crear_seguridad_psicologica|LA ARISTA D.37 QUE LA LINEA 495 DE LA BITACORA DEJO EN COLA PORQUE YO SEGUIA EN LA BANDEJA, Y QUE SE CABLEA HOY EN EL ACTO EN QUE ENTRO. CON ESTA ENTRADA LA SERIE QUEDA COMPLETA: 4 DE 4 PARTES EN EL GRAFO, y era la unica que faltaba. LA CUENTA ESTA ESCRITA, que es la condicion literal de D.37: cap_13 L113 escribe each of the four tips for soliciting criticism offered in the book, y L237 las nombra una a una. EL PASO DE LA MADRE ES EL 17, impreso del grafo en esta vuelta: pasa a los cuatro elementos con los que el texto despliega como se pide critica, dar con una pregunta recurrente, abrazar la incomodidad, escuchar con intencion de entender, y hacer tangible la escucha premiando la franqueza. Son cuatro nombres en una linea y ahi se acaba. YO SOY EL CUARTO, hacer tangible la escucha premiando la franqueza, y lo despliego en 20 pasos de cap_13 L215 a L233 bajo el rotulo MAKE LISTENING TANGIBLE: REWARD THE CANDOR de la linea 215, con DOS ejercicios rotulados que la madre no tiene en ninguna forma: el sesgo de negatividad con la frase de Rick Hanson, el ejemplar de Sara Blakely y su cancion en Spanx, la lista de las tres o cuatro criticas recientes con la pesca cuando la lista sale vacia, el relato en la reunion de equipo con lo aprendido y lo que vas a hacer, las dos cosas que eso consigue, y el protocolo entero de la critica con la que NO estas de acuerdo." \
 --veredicto "abrazar_incomodidad_arrancar_critica_equipo|CONTINUA|madre=abrazar_incomodidad_arrancar_critica_equipo|LA ARISTA 57 DE LA DEUDA DE LA ACTA 24, LA ULTIMA DE LAS CUATRO DE SU SECCION 3.3, Y CON ELLA LAS CUATRO QUEDAN PAGADAS. ES D.29 Y NO D.37, por la misma medida que la 54 y la 56: cap_09 no escribe en ningun sitio cuantas partes tiene esta secuencia, asi que la arista la sostiene mi lectura y va con razon escrita. EL PASO DE LA MADRE ES EL 14, impreso del grafo en esta vuelta: premia la critica para conseguir mas, si estas de acuerdo con ella haz el cambio cuanto antes, y si el cambio necesario va a llevar tiempo haz algo visible que demuestre que lo estas intentando, con la goma elastica que la autora se puso en la muneca. Es UNA linea mas su ejemplar dentro de un procedimiento de 20 pasos cuyo objeto es otro: arrancarle la critica a un equipo entero siendo el jefe. Y DIGO LOS OTROS DOS PASOS SUYOS QUE ME ROZAN EN VEZ DE CALLARLOS, porque la ACTA 24 los nombra: su paso 15 pone el orden de que hacer cuando NO estas de acuerdo con la critica, y su paso 17 manda llevar la cuenta de cuantas veces por semana te critican. Los dos nombran y ninguno despliega: el 15 pone cuatro movimientos en una linea y yo pongo cinco pasos con la zona de acuerdo compartida, la pregunta de si esta dispuesta a una conversacion mas larga, la articulacion de por que no estas de acuerdo y lo peor que puedes hacerle a una relacion; el 17 cuenta veces y yo no cuento ninguna. LO QUE YO TRAIGO Y SUS 20 PASOS NO TIENEN EN NINGUNA FORMA: el sesgo de negatividad y la frase del velcro y el teflon, el ejemplar de Sara Blakely, la lista de las tres o cuatro criticas recientes, la pesca cuando la lista sale vacia, el relato en la reunion de equipo, y las dos cosas que ese relato consigue. LA MADRE TIENE LA LINEA Y EL HIJO TIENE EL PROCEDIMIENTO." \
 --veredicto "pedir_critica_equipo_premiarla|SANO|NINGUNA SENIAL LO LEVANTA Y LO LEO IGUAL, porque mi propia ficha lo trae marcado como el par mas caro de fallar de este capitulo y porque EXTRACTOR.md 11 dice que la jerarquia la busca la lectura y no la senial. LO LEO Y MI VEREDICTO ES SANO, con los dos lados medidos en sus pasos. EL SUYO ES DE cap_09 Y SU OBJETO ES LA PRIMERA FASE DE UNA CULTURA: pedir activamente que te critiquen, aguantar el silencio de un equipo que no habla, y premiar la PRIMERA franqueza por pequenia que sea a la vista de todos. Sus once pasos traen las cuatro razones de empezar por ti, la distincion entre estar abierto y pedir activamente, no criticar la critica, el caso de Tokio con la cuenta hasta diez y la queja del te, y el cuadrado rojo de Toyota. MI OBJETO ES OTRO Y MI ENTREGABLE TAMBIEN: yo no pido nada ni aguanto ningun silencio. Yo entro cuando la critica YA ESTA DADA y trabajo lo que haces con ella: arreglarla deprisa o explicar por que no puedes, la lista de las tres o cuatro criticas recientes, la pesca cuando sale vacia, el relato en publico con lo aprendido y lo que vas a hacer, y el protocolo de la critica con la que no estas de acuerdo. DONDE SE TOCAN Y POR QUE NO BASTA: su paso 10 premia la primera franqueza y su paso 5 dice escuchar con intencion de entender y despues premiar la franqueza. Son dos lineas suyas, con su caso pegado, dentro de un procedimiento cuyo entregable es la critica pedida y el equipo enterado de que la queja se atendio. LO QUE ME HACE DUDAR Y LO ESCRIBO: esas dos lineas son el mismo verbo que mi titulo, y quien lea solo los titulos leera dos veces premiar la franqueza. LO QUE ME DECIDE: el suyo premia PARA QUE EMPIECE A HABER CRITICA y el mio premia PARA QUE LA ESCUCHA SE VEA, y ninguno de los dos entregables se puede producir con los pasos del otro. VA MARCADO COMO DISCUTIBLE EN MI REPORTE, y lo marco antes de saber si acierto." \
 --censo "serie=los cuatro elementos de pedir critica;papel=parte;cabeza=pedir_critica_primero_crear_seguridad_psicologica;nota=la cuenta esta escrita en cap_13 L113, each of the four tips for soliciting criticism offered in the book, y L237 los nombra uno a uno. Esta es la CUARTA y ultima, make listening tangible reward the candor. Con ella la serie queda COMPLETA en 4 de 4 partes en el grafo" $COMUN
echo "CODIGO DE SALIDA: $?"
} > .v42/informes/n02_premiar_franqueza.txt 2>&1 < /dev/null
date '+%H:%M:%S termina insercion candidato 2' >> .v42/informes/_tiempos.txt
