#!/bin/sh
# CANDIDATO 3 de la vuelta 42: integrar_peticion_critica_rutina_existente, pieza 10 de
# cap_13. NO es una de las cuatro partes de la serie: es lo que L237 manda hacer DESPUES
# de practicar las cuatro, y por eso su censo de serie va en no y su veredicto con la
# cabeza es SANO y no CONTINUA, igual que la linea 488 de la bitacora ya lo adjudico
# desde el otro lado. SEIS veredictos.
cd /c/Users/AlexDesk/Documents/forja-nodos
COMUN="--sin-preguntas --censo serie=no --censo caso=no --censo marco_pais=no --censo vigencia=no --censo herramienta=no"
{
echo "\$ python forja.py insertar cuarentena/scott_radical_candor/integrar_peticion_critica_rutina_existente.json [6 veredictos y censos]"
python forja.py insertar cuarentena/scott_radical_candor/integrar_peticion_critica_rutina_existente.json \
 --veredicto "pedir_critica_primero_crear_seguridad_psicologica|SANO|EL MISMO PAR QUE LA LINEA 488 DE LA BITACORA YA ADJUDICO DESDE EL OTRO LADO, Y LO SOSTENGO DESDE EL MIO CON SUS 17 PASOS IMPRESOS DEL GRAFO EN ESTA VUELTA. DIGO PRIMERO POR QUE NO ES CONTINUA, que es la lectura que tentaria: su paso 17 nombra LOS CUATRO ELEMENTOS de pedir critica, dar con una pregunta recurrente, abrazar la incomodidad, escuchar con intencion de entender y hacer tangible la escucha premiando la franqueza, Y YO NO SOY NINGUNO DE LOS CUATRO. La cuenta de cap_13 L113 dice four y las cuatro estan nombradas en L237 una a una: yo soy lo que esa misma L237 manda hacer DESPUES de practicarlas, now that you have practiced the four elements you are ready to put the four things together and make soliciting feedback a habit. EXTRACTOR.md 15.6 escribe que un vecino que no es ninguna de las partes que la cabeza enumera es hermano, y que su veredicto es SANO. LO QUE NOS SEPARA EN OBJETO: el entrega el orden de operaciones recorrido desde su primer paso con la critica pedida y respondida bien, y sus pasos son el por que, la seguridad psicologica de Amy Edmondson y la medicion de Google. Yo entrego LA PETICION METIDA EN LA AGENDA de tus reuniones a solas ya programadas y anunciada al equipo, con el sitio, la frecuencia, el privado y el momento del enfado. Y LA FRONTERA DE LINEA ESTA ESCRITA Y ES LA QUE SOSTIENE ESTO: cap_13 L111, el habito regular, es MI tramo por P.19 y no viaja a sus pasos, y el ya lo declaro asi antes de que ninguna senial dijera nada." \
 --veredicto "elegir_pregunta_recurrente_pedir_critica|SANO|HERMANOS DE SERIE Y NO MADRE E HIJO, que es lo que la linea 500 de la bitacora ya escribio desde su lado y yo sostengo desde el mio con sus 24 pasos impresos del grafo en esta vuelta. EL SITIO DE CADA UNO EN EL LIBRO ES DISTINTO Y ESO ES LO QUE DECIDE: el es LA PRIMERA de los cuatro elementos que L113 anuncia, a go-to question you can actually imagine asking, y yo soy lo que L237 manda DESPUES de practicar los cuatro. LO QUE LOS ROZA Y POR QUE NO BASTA: mi paso 6 nombra los cuatro elementos y el es uno de ellos, pero nombrarlo no es desplegarlo, y el sentido de la vara va al reves de lo que haria falta para una arista mia hacia el; y su paso 8 y mi paso 13 hablan los dos de la pregunta que vas a hacer, el para animar a pensar y volver a preguntar la semana siguiente, yo para compartirla por adelantado con el equipo al anunciar el cambio de agenda. LO QUE ENTREGA CADA UNO: el, tres o cuatro preguntas recurrentes escritas y probadas con un companiero de confianza y evaluadas por si sacaron critica util y si sonaron naturales. Yo, la peticion metida al final de las reuniones a solas y anunciada. Su procedimiento no pone ninguna reunion en ninguna agenda y el mio no escribe ninguna pregunta." \
 --veredicto "montar_reuniones_solas_mentalidad_frecuencia|SANO|EL PAR QUE MI PROPIA FICHA TRAE MARCADO, Y LO LEO ENTERO ANTES DE JUZGARLO: 22 pasos impresos del grafo en esta vuelta. LO MIRE PARA VER SI ALGUNO DE SUS 22 METE LA PETICION DE CRITICA AL FINAL DE LA REUNION, QUE ES LO UNICO QUE ME HARIA REPETIRLE, Y NO HAY NINGUNO. Sus 22 pasos ponen la mentalidad de comida o paseo, la frecuencia contra el limite de cincuenta minutos de reunion a solas por persona a la semana, el remoto por videoconferencia, los veinticinco minutos cuando son diez y cada dos semanas cuando son veinte, no cancelar con la cuenta de dos o tres de cada trece, y la agenda puesta y poseida por quien te reporta con sus expectativas. SU PASO 15 ES EL QUE MAS SE ME ACERCA Y LO DIGO EN VEZ DE CALLARLO: usa el tiempo de la reunion a solas para tener las conversaciones de carrera y, si toca, para hacer las evaluaciones formales de desempenio. NOMBRA DOS COSAS QUE METER EN ESA REUNION Y LA CRITICA NO ES NINGUNA DE LAS DOS. SOMOS VECINOS DE SEDE Y NO DE OBJETO: el monta la reunion, yo meto una cosa dentro de una reunion que el ya monto. Su entregable son las reuniones puestas, no canceladas y con su agenda; el mio es la peticion de critica metida al final y anunciada al equipo con la pregunta. Ninguno de los dos se puede producir con los pasos del otro." \
 --veredicto "abrazar_incomodidad_silencio_contar_seis|SANO|LO NOMBRO EN MI PASO 6 Y AUN ASI NO SOY SU MADRE NI EL ES LA MIA, y lo digo con la direccion de la vara puesta, que es lo que AUDITOR_FORJA.md 6.1 exige. MI PASO 6 REPITE LA LISTA DE CUATRO QUE EL LIBRO PONE EN L237, y nombrar los cuatro es exactamente lo que hace la cabeza pedir_critica_primero_crear_seguridad_psicologica en su paso 17: LA CABEZA ES ELLA Y NO YO. Yo soy otro hermano de esa misma cabeza, el que entra por L237 con el habito, y el es la segunda de las cuatro partes, embracing the discomfort, que entro en la vuelta 41. EXTRACTOR.md 15.6 escribe que un vecino que no es tu parte es hermano y su veredicto es SANO. LO QUE NOS SEPARA: el aguanta el silencio contando hasta seis en el instante de una conversacion concreta y entrega ese silencio aguantado; yo no aguanto ningun silencio y entrego una agenda cambiada y anunciada. Su activacion es que has pedido critica y se hace el silencio; la mia es que ya has practicado los cuatro elementos por separado y quieres juntarlos y volverlos habito." \
 --veredicto "escuchar_entender_critica_dominar_defensa|SANO|LA TERCERA DE LAS CUATRO PARTES QUE MI PASO 6 NOMBRA, Y ENTRO HOY MISMO POR SU PROPIA PUERTA UNAS HORAS ANTES QUE YO. MISMA RAZON QUE SUS TRES HERMANAS Y NO LA REPITO CON OTRAS PALABRAS PARA QUE PAREZCA OTRA: la lista de cuatro de mi paso 6 es la lista de L237, que es la que la cabeza pedir_critica_primero_crear_seguridad_psicologica ya tiene en su paso 17, asi que la cabeza es ella y yo soy un hermano mas, el de L237. LO QUE NOS SEPARA EN OBJETO: el domina tu propia defensa mientras te estan criticando, con la respuesta de pelea o huida y el ejercicio de los tres minutos, y entrega la critica escuchada entera. Yo no escucho ninguna critica en ninguno de mis 13 pasos: yo pongo el sitio y el momento en que se va a pedir, y entrego la peticion metida en la agenda." \
 --veredicto "premiar_franqueza_hacer_escucha_tangible|SANO|LA CUARTA DE LAS CUATRO PARTES QUE MI PASO 6 NOMBRA, Y ENTRO HOY MISMO MINUTOS ANTES QUE YO. LA RAZON ES LA MISMA DE SUS TRES HERMANAS: nombrar los cuatro en mi paso 6 no me hace su madre, porque esa lista es la de L237 y su cabeza declarada es pedir_critica_primero_crear_seguridad_psicologica por su paso 17. LO QUE NOS SEPARA: el actua DESPUES de que la critica se recibio, arregla el problema deprisa o explica por que no puede, y lo cuenta en publico con la lista de las tres o cuatro criticas recientes. Yo actuo ANTES DE QUE HAYA CRITICA NINGUNA: pongo la peticion al final de la reunion a solas para que exista la ocasion. Su entregable lleva un relato en una reunion de equipo; el mio lleva una agenda y un anuncio." $COMUN
echo "CODIGO DE SALIDA: $?"
} > .v42/informes/n03_integrar_peticion.txt 2>&1 < /dev/null
date '+%H:%M:%S termina insercion candidato 3' >> .v42/informes/_tiempos.txt
