#!/bin/sh
# CANDIDATO 4 de la vuelta 42: dar_elogio_disciplina_igual_critica, pieza 11 de cap_13.
# CINCO veredictos: la madre de la cola 490 (arista 49, D.29), la madre por lectura de
# cap_05, y tres SANO del vecindario del elogio. Y UNA DISCREPANCIA DECLARADA contra el
# resumen del propio candidato, medida hoy contra el grafo.
cd /c/Users/AlexDesk/Documents/forja-nodos
COMUN="--sin-preguntas --censo serie=no --censo caso=no --censo marco_pais=no --censo vigencia=no --censo herramienta=no"
{
echo "\$ python forja.py insertar cuarentena/scott_radical_candor/dar_elogio_disciplina_igual_critica.json [5 veredictos y censos]"
python forja.py insertar cuarentena/scott_radical_candor/dar_elogio_disciplina_igual_critica.json \
 --veredicto "pedir_critica_primero_crear_seguridad_psicologica|CONTINUA|madre=pedir_critica_primero_crear_seguridad_psicologica|LA ARISTA 49 DE LA DEUDA DE LA VUELTA 23, ESCRITA EN LA LINEA 490 DE LA BITACORA Y DEJADA EN COLA PORQUE YO SEGUIA EN LA BANDEJA. SE CABLEA HOY, EN EL ACTO EN QUE ENTRO. EL PASO DE LA MADRE ES EL 2, y lo tengo impreso del grafo en esta vuelta: Dos, da elogio. SON TRES PALABRAS, y es cap_13 L79 entera, give praise. Es el segundo paso de un orden de operaciones de cinco que la madre enumera en sus pasos 1 a 5 y no despliega en ninguno. ES D.29 Y NO D.37, y lo digo con la medida delante: la cuenta escrita de cap_13 L113, four, es la de los cuatro elementos de PEDIR CRITICA y no la del orden de operaciones, asi que aqui no hay cifra escrita por el libro sobre este reparto y la arista la sostiene mi lectura. YO DESPLIEGO ESAS TRES PALABRAS EN 20 PASOS de cap_13 L251 y L267 a L287, bajo los rotulos PRAISE: FOCUS ON THE GOOD STUFF. REALLY. de la linea 247 y APPLY THE SAME DISCIPLINE TO PRAISE THAT YOU DO TO CRITICISM de la 275, con lo que la madre no tiene en ninguna forma: la imagen del freno y el acelerador, por que se resiste la gente a elogiar, el elogio usado como arma, la disciplina de elogiar primero despues del trabajo duro de pedir critica, el rendimiento de las fuerzas contra las debilidades, la pregunta de Karen Sipprell con su respuesta tipica, el gran trabajo vacio que suena condescendiente, y el ejercicio de pareja con sus dos ejemplares literales. MISMA FIGURA Y MISMO VEREDICTO QUE LA 50, LA 51 Y LA 52." \
 --veredicto "elogiar_trabajo_especifico_contexto|CONTINUA|madre=elogiar_trabajo_especifico_contexto|SEGUNDA MADRE, DECLARADA POR LECTURA Y NO POR SENIAL, que es lo que EXTRACTOR.md 11 manda cuando el candidato despliega algo que el libro ya nombro en una linea. EL PASO DE LA MADRE ES EL 6, impreso del grafo en esta vuelta: Se tan concreto y tan a fondo con el elogio como con la critica, y baja al detalle. ES UNA LINEA, Y ES LITERALMENTE MI SEGUNDO ROTULO: cap_13 L275 escribe APPLY THE SAME DISCIPLINE TO PRAISE THAT YOU DO TO CRITICISM, y mi mitad de atras es esa disciplina desplegada. LO QUE YO PONGO DEBAJO DE ESA LINEA Y EL NO TIENE: la pregunta de Karen Sipprell con la respuesta tipica de ninguno en absoluto, que pasa cuando eres vago con el elogio y el gran trabajo vacio que suena condescendiente, para que sirve el elogio concreto como modelo a seguir, las tres pautas que valen igual para elogio y para critica, y el ejercicio de pareja con sus dos ejemplares y con lo que el libro ha medido de el. Y DIGO LO QUE EL TIENE Y YO NO, PARA QUE SE VEA QUE NO LE REPITO: sus siete pasos son el caso del entrenador de un equipo infantil en sus dos versiones, el caso del ingeniero felicitado en publico por trabajo ajeno, y el correo copiado y pegado a setenta personas. SU PROCEDIMIENTO ES COMO SE DICE UN ELOGIO CONCRETO; EL MIO ES LA DISCIPLINA CON QUE SE DA EL ELOGIO EN GENERAL, y por eso su paso 6 me nombra y no me agota." \
 --veredicto "equilibrar_elogio_critica_equipo|SANO|AQUI DISCREPO DE MI PROPIA FICHA Y LO DIGO EN VEZ DE COPIARLO, que es lo que EXTRACTOR.md 5 manda cuando la medicion de hoy y una nota previa no coinciden. MI resumen_teorico, escrito en una vuelta anterior, declara CONTINUA CON ARISTA con este vecino y sostiene que yo traigo lo que el no tiene, nombrando LA PREGUNTA DE KAREN SIPPRELL. LO HE MEDIDO CONTRA EL GRAFO EN ESTA VUELTA Y ESA PARTE ES FALSA: su paso 9 dice pasa el mismo tiempo asegurandote de tener bien los hechos antes de elogiar a alguien que antes de criticarle, son las dos preguntas que el texto recoge de Karen Sipprell, colega suya en Apple. LA TIENE, Y ADEMAS LAS DOS PREGUNTAS DONDE YO TRAIGO UNA. POR ESO NO PUEDE SER MI MADRE: la direccion de la vara exige que la madre NOMBRE y el hijo DESPLIEGUE, y en el unico punto donde nos tocamos el tiene mas escrito que yo. Y TAMPOCO SOY SU MADRE: mi paso 12 aniade la respuesta tipica de ninguno en absoluto y nada mas. EL VEREDICTO ES SANO, CON LOS DOS OBJETOS MEDIDOS: el suyo es el REPARTO, mas elogio que critica sin ratio fijo, sin sandwich de opinion, y la energia puesta al reves de como sale, y su entregable es ninguna proporcion aplicada y ningun elogio de relleno. El mio es la DISCIPLINA DE DAR EL ELOGIO, con el freno y el acelerador, el elogio como arma, el rendimiento de las fuerzas, la vaguedad que suena condescendiente y el ejercicio de pareja, y mi entregable es el elogio dado primero y concreto con los hechos comprobados. VA MARCADO COMO DISCUTIBLE EN MI REPORTE, y lo marco antes de saber si acierto: es el corte que mas me ha costado de este capitulo." \
 --veredicto "elogiar_publico_criticar_privado_sus_tres_matices|SANO|MI PASO 15 LO NOMBRA Y ESO NO ME HACE SU MADRE, y lo digo con la direccion puesta. Mi paso 15 repite las tres pautas que cap_13 L279 recuerda, hazlo con humildad y con utilidad y de inmediato, elogia en publico y critica en privado, y no des guia sobre atributos de personalidad: SON TRES NOMBRES EN UNA LINEA MIA, y el que despliega la segunda es EL, en nueve pasos, con la distincion entre correccion y critica, los ejemplares de la errata de la diapositiva seis, el gusto de cada persona, la frase de no para avergonzar a fulana, y dejar que sea la propia persona quien cuente su error. SI ALGUIEN ES MADRE AQUI SOY YO, Y NO LA DECLARO, y digo por que: la linea que nombra esas tres pautas no es mia, es del libro en L279, y el nodo que la tiene como cabeza declarada es otro, dar_guia_humilde_tres_tecnicas, que vive en el grafo con esa misma familia. Declarar una arista mia hacia el por una lista que los dos heredamos del mismo sitio seria declararla por tema compartido, que es exactamente lo que EXTRACTOR.md 15.6 prohibe. SANO, con los objetos separados: el decide DONDE se dice cada cosa; yo decido CON QUE DISCIPLINA se da el elogio." \
 --veredicto "dar_guia_humilde_tres_tecnicas|SANO|EL TERCER VECINO DE LA MISMA LINEA DEL LIBRO Y LA MISMA RAZON, dicha una sola vez y no tres: cap_13 L279 recuerda tres pautas, y mi paso 15 las nombra las tres sin desplegar ninguna. El despliega la PRIMERA, la humildad, con las tres tecnicas que el texto atribuye una a una; elogiar_publico_criticar_privado_sus_tres_matices despliega la SEGUNDA. YO NO DESPLIEGO NINGUNA DE LAS TRES: las cito de pasada dentro de un procedimiento cuyo objeto es otro, la disciplina del elogio, y mi entregable es el elogio dado primero y concreto con los hechos comprobados y sin comparaciones odiosas, que no se produce con los pasos de ninguno de los dos. SOMOS TRES VECINOS DE UNA LISTA HEREDADA DEL MISMO PARRAFO, que es la figura del hermano de EXTRACTOR.md 15.6, y su veredicto es SANO." $COMUN
echo "CODIGO DE SALIDA: $?"
} > .v42/informes/n04_dar_elogio.txt 2>&1 < /dev/null
date '+%H:%M:%S termina insercion candidato 4' >> .v42/informes/_tiempos.txt
