#!/bin/sh
# CANDIDATO 5 de la vuelta 42: medir_critica_respuesta_oyente_brujula, pieza 12 y ULTIMA
# de cap_13, 33 pasos. SIETE veredictos: CUATRO madres (la de la cola 494 que es la arista
# 51, dos por lectura de cap_05 y cap_06, y la del marco de cap_01 que SI levanta la
# senial) y TRES SANO del vecindario de la emocion y de la critica.
cd /c/Users/AlexDesk/Documents/forja-nodos
COMUN="--sin-preguntas --censo serie=no --censo caso=no --censo marco_pais=no --censo vigencia=no --censo herramienta=no"
{
echo "\$ python forja.py insertar cuarentena/scott_radical_candor/medir_critica_respuesta_oyente_brujula.json [7 veredictos y censos]"
python forja.py insertar cuarentena/scott_radical_candor/medir_critica_respuesta_oyente_brujula.json \
 --veredicto "pedir_critica_primero_crear_seguridad_psicologica|CONTINUA|madre=pedir_critica_primero_crear_seguridad_psicologica|LA ARISTA 51 DE LA DEUDA DE LA VUELTA 23, ESCRITA EN LA LINEA 494 DE LA BITACORA Y DEJADA EN COLA PORQUE YO SEGUIA EN LA BANDEJA. SE CABLEA HOY, EN EL ACTO EN QUE ENTRO. EL PASO DE LA MADRE ES EL 4, impreso del grafo en esta vuelta: Cuatro, mide la critica y ajusta. SON SEIS PALABRAS, y es cap_13 L83 entera, gauge the criticism and adjust. Es el cuarto paso de un orden de operaciones de cinco que la madre enumera en sus pasos 1 a 5 y no despliega en ninguno. ES D.29 Y NO D.37: la unica cuenta escrita de este capitulo, el four de L113, es la de los cuatro elementos de PEDIR critica, y este reparto de cinco no la tiene, asi que la arista la sostiene mi lectura. YO DESPLIEGO ESAS SEIS PALABRAS EN 33 PASOS de cap_13 L291 a L321, bajo el rotulo GAUGE CRITICISM de la linea 289, con lo que la madre no tiene en ninguna forma: que no existen palabras magicas que sirvan a la vez de bisturi y de anestesia, el marco usado como BRUJULA, el inventario de lo que se observa en el otro, LAS TRES RESPUESTAS con lo que se hace con cada una, el guion literal para nombrar la emocion, la humildad al nombrarla, el lema de escuchar y desafiar y comprometer, y el error de las consecuencias prematuras. MISMA FIGURA Y MISMO VEREDICTO QUE LA 49, LA 50 Y LA 52." \
 --veredicto "ajustar_franqueza_oido_oyente|CONTINUA|madre=ajustar_franqueza_oido_oyente|SEGUNDA MADRE, DECLARADA POR LECTURA Y NO POR SENIAL. EL PASO DE LA MADRE ES EL 1, impreso del grafo en esta vuelta: Mide las dos dimensiones en el oido del que escucha y no en la boca del que habla, que es donde el texto dice que se miden. ES MI PRIMERA LINEA ENTERA, Y EL LIBRO LO DICE DE MI MISMO: cap_13 L291 escribe que esa frase era otra linea muy tuiteada del libro, pero que en sus talleres quedo claro que no se explicaba sola, y pregunta como se pone en practica. MI NODO ES LA RESPUESTA A ESA PREGUNTA, y por eso la figura es exacta: la madre tiene la linea y el hijo tiene el procedimiento. LO QUE LA MADRE HACE CON ESA LINEA Y YO NO: la lleva al SALTO DE CULTURA, de una empresa a otra y de un pais a otro, y entrega las dos dimensiones traducidas a la forma local, con el equipo de Tokio educado y persistente y con el nombre cambiado. LO QUE YO HAGO Y ELLA NO: la llevo a LA CONVERSACION QUE ESTAS TENIENDO AHORA MISMO, con las tres respuestas del oyente nombradas una a una, tristeza, enfado y no oirte, y lo que hay que hacer con cada una. Su activacion es que llevas tu forma de ser franco a otro sitio y deja de funcionar; la mia es que tienes delante la respuesta del otro y tienes que decidir que hacer con ella." \
 --veredicto "manejar_enfado_persona_desafiada|CONTINUA|madre=manejar_enfado_persona_desafiada|TERCERA MADRE, Y ES LA QUE MAS ME CUESTA, ASI QUE LA MARCO COMO DISCUTIBLE EN MI REPORTE ANTES DE SABER SI ACIERTO. EL PASO DE LA MADRE ES EL 3, impreso del grafo en esta vuelta: Cuando lo que dices duele, reconoce el dolor de la otra persona. Y sus pasos 4 a 7 siguen en la misma linea: no finjas que no duele, elimina de tu vocabulario no te lo tomes como algo personal, ofrecete a ayudar a arreglar el problema. SON SIETE PASOS CORTOS Y LOS CUATRO DEL MEDIO ESTAN DENTRO DE MI TRAMO DEL ENFADO, y eso es justo lo que me obliga a decir por que NO es REPITE. POR QUE NO LO ES, con los dos lados medidos: yo despliego el reconocimiento del dolor en un procedimiento que ella nombra y no tiene, el guion literal de nombrar la emocion de cap_13 L305, parece que te he disgustado o que te he cabreado o que te he frustrado, no era lo que queria hacer, estoy intentando ayudarte, como puedo decir esto de una manera mejor; la orden de no usar ese guion sino tus palabras; la humildad al nombrarla con el ejemplar de la autora que llora de furia y no de tristeza; y lo que nombrar la emocion consigue frente a fingir que no esta pasando. Y sobre todo: EL ENFADO ES UNA DE MIS TRES RESPUESTAS Y NO MI NODO. Mis otros dos tramos, la tristeza y el no oirte, mas el marco como brujula, mas el lema de escuchar y desafiar y comprometer, mas el error de las consecuencias prematuras, no estan en sus siete pasos en ninguna forma. Y DIGO LO QUE ELLA TIENE Y YO NO, que es lo que me impide llamarla agotada: si nadie se enfada nunca contigo es probable que no estes desafiando bastante a tu equipo. LA MADRE ES PEQUENIA Y AUN ASI ES MADRE: nombra el acto en una linea y yo lo ejecuto." \
 --veredicto "desplegar_marco_franqueza_radical|CONTINUA|madre=desplegar_marco_franqueza_radical|CUARTA MADRE, Y LA UNICA DE LAS CUATRO QUE LEVANTA LA SENIAL: paso_contra_nodo 0.723 sobre un umbral de 0.60, mi paso 4 contra su paso 6, con similitud_texto 0.139 y familia_id 0.000. ES LA COLA ENTERA DE ESTE CANDIDATO Y LA LEO LA PRIMERA. EL PASO DE LA MADRE ES EL 6, impreso del grafo en esta vuelta: Usa el marco como una brujula, para llevar cada conversacion concreta a un sitio mejor. ES UNA LINEA Y NO DICE COMO. Yo soy el COMO, en 33 pasos: a que se mira en el otro, lo que dice y su lenguaje corporal y su mirada, las tres respuestas con lo que se hace con cada una, y en que direccion del eje hay que moverse en cada caso. LO QUE SU PROCEDIMIENTO ES Y EL MIO NO: el suyo es FISICO, recortar el marco del libro, hacer fotocopias, ponerlas en la nevera y repartirlas, con sus dos prohibiciones de no usarlo como test de personalidad y no escribir nombres en las casillas, y su entregable son las copias a la vista. Mi entregable no tiene ni una copia: es la critica ajustada sobre la marcha. Y DIGO LA COSA RARA EN VEZ DE CALLARLA: su paso 6 sale de cap_01 y mi paso 4 sale de cap_13 L295, o sea que el libro escribe la frase de la brujula DOS VECES y en dos unidades distintas. No es un solape de frontera, porque cada nodo cita su propia unidad; es que la brujula es la linea que el libro repite y que nadie habia desplegado. CON ESTA SON CUATRO MADRES PARA UN MISMO HIJO, QUE ES MUCHO, Y LO MARCO COMO DISCUTIBLE EN MI REPORTE: las cuatro se sostienen porque las cuatro NOMBRAN UNA LINEA DISTINTA MIA y ninguna despliega la suya." \
 --veredicto "dominar_reacciones_emociones_ajenas|SANO|EL VECINO MAS PELIGROSO DE ESTA TANDA Y POR ESO LO LEO ENTERO, sus 11 pasos impresos del grafo en esta vuelta. LO QUE COMPARTIMOS ES REAL Y LO DIGO PRIMERO: los dos decimos que no se le dice a nadie como tiene que sentirse, y los dos rechazan la frase de no te lo tomes como algo personal. LO QUE NOS SEPARA ES LA CONVERSACION EN QUE ESTAMOS: el entra cuando alguien reacciona con emocion fuerte delante de ti, llorando, gritando o callandose de golpe, SEA CUAL SEA LA CAUSA, y su objeto es la frontera entre tus emociones y las suyas: no intentar prevenirlas ni controlarlas, no sumarle tu culpa, hacer preguntas hasta entender el problema de verdad, perdonarte si no aguantas, los paniuelos a un paseo corto de tu mesa, las botellas de agua sin abrir, y pasear en vez de sentarse. YO ENTRO EN UN SITIO MUCHO MAS ESTRECHO: estas DANDO UNA CRITICA y tienes delante la respuesta a esa critica, y mi trabajo es decidir con el marco de la franqueza radical si toca importarte mas o desafiar mas claro. Su entregable es la emocion reconocida y el problema de verdad a la vista; el mio es LA CRITICA AJUSTADA SOBRE LA MARCHA y la conversacion devuelta al carril. Y ninguno de los dos entregables se produce con los pasos del otro: el no tiene el eje de desafiar directamente ni las consecuencias prematuras, y yo no tengo ni paniuelos ni paseos." \
 --veredicto "criticar_trabajo_evitar_desanimo|SANO|VECINO DE LA MISMA FAMILIA DE TEMA Y DE OTRO MOMENTO DE LA CONVERSACION, leido entero en sus 14 pasos. EL TRABAJA LO QUE DICES Y COMO LO DICES: critica el trabajo y no a la persona, el error de atribucion fundamental, articular el porque y devolver a la via, averiguar antes por que el otro hace lo que hace, y la lista de humilde, util, en persona e inmediato, en publico el elogio y en privado la critica. YO TRABAJO LO QUE HACES CON LO QUE VUELVE: mi condicion de activacion empieza cuando la critica YA ESTA DICHA y tienes delante la respuesta del oyente. Su entregable es la critica dicha sobre el trabajo con el porque articulado; el mio es la critica AJUSTADA sobre la marcha segun esa respuesta, con la emocion nombrada si la hubo. DONDE NOS ROZAMOS Y POR QUE NO BASTA: su paso 12 dice no personalices y deja claro que el problema no viene de un defecto de personalidad, que es vecino de mi orden de no juzgar la emocion; son dos lineas sueltas de dos procedimientos distintos y ninguna despliega a la otra. SANO." \
 --veredicto "escuchar_entender_critica_dominar_defensa|SANO|ENTRO HOY MISMO POR SU PROPIA PUERTA Y LO JUZGO CON SUS 13 PASOS DELANTE. SOMOS LOS DOS LADOS DE LA MISMA MESA Y ESO ES LO QUE NOS SEPARA: el es EL QUE RECIBE la critica y su trabajo es dominar su propia defensa, con la respuesta de pelea o huida, el ejercicio de respiracion, el trago de agua y los tres minutos de escucha sin interrumpir. YO SOY EL QUE LA DA, y mi trabajo es leer la cara del que la recibe y ajustar. Su entregable es la critica escuchada entera sin respuesta defensiva; el mio es la critica ajustada sobre la marcha. Y DIGO LO QUE PODRIA CONFUNDIRSE: mi paso 6 dice que la manera en que escuchas importa mas que la manera en que hablas, que es cap_13 L297 entera, y suena a su titulo. Pero en mi nodo esa linea manda escuchar LA RESPUESTA A MI PROPIA CRITICA para medirla, y en el suyo manda escuchar LA CRITICA QUE ME ESTAN DANDO A MI. Mismo verbo, distinto objeto y distinto actor: SANO." $COMUN
echo "CODIGO DE SALIDA: $?"
} > .v42/informes/n05_medir_critica.txt 2>&1 < /dev/null
date '+%H:%M:%S termina insercion candidato 5' >> .v42/informes/_tiempos.txt
