#!/bin/sh
# CANDIDATO 6 de la vuelta 42, y PRIMERO de cap_14: montar_equipo_gestion_desempenio_revisar_sistema,
# pieza P1. NO es una de las trece partes de la serie: es lo que va ANTES de la lista, asi
# que su censo de serie va en no. TRES veredictos por lectura del vecindario del desempenio.
cd /c/Users/AlexDesk/Documents/forja-nodos
COMUN="--sin-preguntas --censo serie=no --censo caso=no --censo marco_pais=no --censo vigencia=no --censo herramienta=no"
{
echo "\$ python forja.py insertar cuarentena/scott_radical_candor/montar_equipo_gestion_desempenio_revisar_sistema.json [3 veredictos y censos]"
python forja.py insertar cuarentena/scott_radical_candor/montar_equipo_gestion_desempenio_revisar_sistema.json \
 --veredicto "entregar_evaluacion_formal_desempenio_nueve_consejos|SANO|EL VECINO MAS CERCANO DE TODO EL CATALOGO A ESTE CAPITULO NUEVO, Y POR ESO LO LEO ENTERO ANTES DE JUZGARLO: sus 22 pasos impresos del grafo en esta vuelta. LO QUE NOS SEPARA ES EL ACTOR, Y ES UNA SEPARACION LIMPIA: el suyo es UN JEFE al que le toca dar la evaluacion de alguien de su equipo, y sus 22 pasos son lo que ese jefe hace en esa conversacion, no dar sorpresas, no fiarse de su juicio unilateral, escribirla, decidir cuando entregarla, reservar cincuenta minutos, medio tiempo al diagnostico y medio al plan, y dar la nota y la retribucion despues. EL MIO ES LA EMPRESA QUE REHACE SU SISTEMA: monta un equipo de gestion del desempenio con responsables operativos y directivos de recursos humanos, repasa los elementos clave del proceso actual, acuerda la norma de escuchar y desafiar y comprometerse antes de discutir, explica el desacoplamiento del desarrollo a la plantilla y pone un ciclo de revision cada tres anios. Su entregable es UNA evaluacion dada; el mio es UN EQUIPO MONTADO Y UN CICLO DE REVISION PUESTO. Ninguno de los dos se produce con los pasos del otro, y ninguno nombra al otro en una linea. SANO." \
 --veredicto "ser_honesto_transparente_desempenio|SANO|COMPARTIMOS LA PALABRA DESEMPENIO Y NADA MAS, y lo digo con sus 7 pasos leidos. EL SUYO ES UNA OBLIGACION CONTINUA DE UN JEFE CON UNA PERSONA: partir del desequilibrio de poder, hacer que esa persona sepa en todo momento cuales son tus expectativas y donde esta respecto a ellas, no dar por hecho que lee entre lineas, y decirselo tanto si es la personificacion de lo estupendo como si no. Su activacion es siempre que tengas a alguien a cargo. LA MIA ES UN PROYECTO CON PRINCIPIO: cuando decides que hace falta REHACER EL SISTEMA de gestion del desempenio de tu empresa. El habla de una relacion; yo monto una institucion. Su entregable vive en la cabeza de una persona; el mio es un equipo con dos perfiles y un ciclo de revision cada tres anios. SANO." \
 --veredicto "mantener_proceso_evaluacion_ligero_vigilar_crecimiento|SANO|ESTE SIGUE EN LA BANDEJA MIENTRAS ESCRIBO Y ES EL QUE MAS ME ROZA, asi que lo leo antes de entrar y no despues. MI PASO 2 ENCARGA AL EQUIPO QUE VIGILE QUE EL PROCESO NO SE DESBOQUE Y LO MANTENGA LIGERO, y ese es literalmente su titulo entero. POR QUE NO SOY SU MADRE AUNQUE LO PAREZCA: la cabeza declarada de este capitulo es recorrer_trece_elementos_proceso_evaluacion_formal, y el es el elemento numero 13 de esos trece, con su propia linea en la lista de la cabeza. Mi paso 2 no es la linea que lo enumera: la linea que lo enumera esta en la cabeza, y declarar yo la arista seria ponerle dos madres por la misma enumeracion, que es exactamente la doble compresion que el manual 3.4 prohibe. SOMOS HERMANOS DE CAPITULO Y NO MADRE E HIJO. Y LO QUE ADEMAS NOS SEPARA EN OBJETO: yo monto el equipo y pongo el ciclo de revision; el mide cuanto tiempo se come el proceso, recorta activamente, y deja un impreso que el jefe rellena por empleado en menos de treinta minutos. Mi entregable no tiene ningun impreso y el suyo no monta ningun equipo." $COMUN
echo "CODIGO DE SALIDA: $?"
} > .v42/informes/n06_montar_equipo.txt 2>&1 < /dev/null
date '+%H:%M:%S termina insercion candidato 6' >> .v42/informes/_tiempos.txt
