#!/bin/sh
# CANDIDATO 7 de la vuelta 42: recorrer_trece_elementos_proceso_evaluacion_formal, pieza
# P2 de cap_14 y CABEZA DE UNA SERIE DE TRECE (manual 3.4, D.37). Entra ANTES que sus
# trece partes a proposito: es el orden del libro y es lo que deja que cada parte cite el
# paso de la madre cuando entre. CUATRO veredictos: DOS que levanta la senial y DOS por
# lectura. Uno de los de la senial es una PARTE MIA que sigue en la bandeja, asi que su
# arista queda EN COLA y se cablea el dia que esa parte entre.
cd /c/Users/AlexDesk/Documents/forja-nodos
COMUN="--sin-preguntas --censo caso=no --censo marco_pais=no --censo vigencia=no --censo herramienta=no"
{
echo "\$ python forja.py insertar cuarentena/scott_radical_candor/recorrer_trece_elementos_proceso_evaluacion_formal.json [4 veredictos y censos]"
python forja.py insertar cuarentena/scott_radical_candor/recorrer_trece_elementos_proceso_evaluacion_formal.json \
 --veredicto "elegir_palabras_nota_definirlas_empresa_entera|CONTINUA|madre=recorrer_trece_elementos_proceso_evaluacion_formal|ES UNA PARTE MIA Y LA SENIAL LA LEVANTA: similitud_texto 0.356 sobre 0.35, familia_id 0.000, paso_contra_nodo 0.476. YO SOY LA MADRE Y EL ES EL HIJO, y la direccion la decide el libro y no la senial. ES D.37 Y LA CUENTA ESTA ESCRITA: cap_14 rotula ELEMENTS OF A FORMAL PERFORMANCE REVIEW PROCESS en L35, nombra los trece elementos uno por linea de la L39 a la L63, y despues los despliega numerados del 1 al 13. EL PASO MIO QUE LO ENUMERA ES EL 6: Cinco, cuida el lenguaje, porque el texto dice que las palabras importan. Es cap_14 L47 entera, Language matters, y ahi se acaba: son tres palabras del libro. EL LO DESPLIEGA EN 10 PASOS de cap_14 L117 a L123, con lo que yo no tengo en ninguna forma: elegir palabras y no numeros, definir cada escalon en dos o tres frases, y publicarlas en un sitio muy central de la empresa facil de entender y rapido de leer. SU ARISTA QUEDA EN COLA PORQUE EL SIGUE EN LA BANDEJA MIENTRAS YO ENTRO, y se cablea en el acto en que el entre, que es lo que D.29 manda y lo que la linea 495 de la bitacora hizo con la serie anterior." \
 --veredicto "aprender_resultados_vencer_dos_presiones|SANO|LA SENIAL QUE LO LEVANTA ES LA 3 Y ESTA CLAVADA EN EL UMBRAL: paso_contra_nodo 0.600 contra un umbral de 0.600, con similitud_texto 0.272 y familia_id 0.000. LO LEO Y ES RUIDO DE FRASE CORTA, y lo digo con los dos pasos delante: mi paso 11 es Diez, decide la frecuencia y su paso 4 es Aprende de la experiencia. SON DOS IMPERATIVOS DESNUDOS DE CUATRO PALABRAS, y lo que difflib esta midiendo ahi es la forma de la linea, no su objeto. Mis pasos 2 a 14 son trece rotulos de una linea cada uno porque el libro los escribe asi, y eso me hace vecino de cualquier nodo del catalogo que tenga un paso corto. LO QUE SEPARA A LOS DOS NODOS: el suyo es la ultima vuelta de la rueda de conseguir cosas, mirar un resultado sin negacion y vencer la presion de ser coherente y el agotamiento, y entrega el aprendizaje sacado y la rueda empezada otra vez. El mio es la lista de las trece decisiones de disenio de un proceso formal de evaluacion, y entrega esa lista recorrida con la decision de tu empresa tomada en cada una. Ni el mismo objeto, ni el mismo entregable, ni una linea compartida. SANO." \
 --veredicto "montar_equipo_gestion_desempenio_revisar_sistema|SANO|ENTRO HACE UN RATO POR SU PROPIA PUERTA Y ES MI VECINO DE LINEA EN EL LIBRO: el es la pieza P1 de cap_14 y yo la P2. LO QUE PODRIA CONFUNDIRSE Y POR ESO LO DIGO: su paso 5 dice repasa los elementos clave de tu evaluacion de desempenio actual, que el texto despliega uno a uno mas abajo, y esos elementos son MI LISTA. PERO ESO NO LE HACE MI MADRE, y la razon es la que el manual 3.4 escribe: LA CABEZA DE ESTA SERIE SOY YO. La enumeracion de los trece esta en cap_14 L39 a L63 y la recojo yo entera, un elemento por paso, del P2 al P14. Su paso 5 no enumera ninguno: remite a la lista sin escribirla. Declarar una arista suya hacia mi pondria DOS compresiones sobre la misma numeracion, que es lo que el manual prohibe por su nombre. LO QUE NOS SEPARA EN OBJETO: el monta un equipo con responsables operativos y directivos de recursos humanos, acuerda la norma de escuchar y desafiar y comprometerse, explica el desacoplamiento del desarrollo y pone un ciclo de revision cada tres anios. Yo no monto nada: pongo delante las trece decisiones que hay que tomar antes de decidir ninguna. SANO." \
 --veredicto "entregar_evaluacion_formal_desempenio_nueve_consejos|SANO|LOS DOS SOMOS DE EVALUACION FORMAL Y ESTAMOS EN DOS SITIOS DISTINTOS DEL PROBLEMA, leido con sus 22 pasos delante. EL SUYO ES EL JEFE QUE ENTREGA UNA EVALUACION dentro de un proceso que ya existe: no dar sorpresas, escribirla, decidir cuando entregarla, reservar cincuenta minutos, medio tiempo al diagnostico y medio al plan. EL MIO ES LA EMPRESA QUE DISENIA EL PROCESO: trece decisiones que hay que tomar antes de que exista ninguna evaluacion que entregar, desde si hay nota hasta si el proceso es ligero o pesado. Y LO DIGO CON LA VARA PUESTA: su paso 4 toca mi elemento once y su paso 21 toca mi elemento seis, pero los toca DESDE DENTRO, como conducta del jefe en una conversacion, y no como decision de disenio de la empresa. Mi entregable es la lista recorrida entera con la decision de tu empresa tomada en cada uno; el suyo es una evaluacion dada. SANO." \
 --censo "serie=los trece elementos del proceso formal de evaluacion de desempenio;papel=cabeza;nota=la cuenta esta escrita en el libro y por eso es D.37: cap_14 rotula ELEMENTS OF A FORMAL PERFORMANCE REVIEW PROCESS en L35, nombra los trece uno por linea de la L39 a la L63, y despues los despliega numerados del 1 al 13 en los rotulos de L65, L73, L95, L99, L117, L125, L143, L153, L171, L187, L197, L205 y L221. Esta cabeza recoge la lista y NO el despliegue: cada elemento tiene su nodo propio. Al entrar la cabeza hay 0 de 13 partes en el grafo" $COMUN
echo "CODIGO DE SALIDA: $?"
} > .v42/informes/n07_recorrer_trece.txt 2>&1 < /dev/null
date '+%H:%M:%S termina insercion candidato 7' >> .v42/informes/_tiempos.txt
