#!/bin/sh
# CANDIDATO 8 de la vuelta 42: decidir_poner_nota_comunicar_proposito_limites, pieza P3 de
# cap_14 y ELEMENTO 1 DE LOS TRECE. La arista D.37 con su cabeza se cablea en este mismo
# acto, que es lo que EXTRACTOR.md 15.6 manda. TRES veredictos.
cd /c/Users/AlexDesk/Documents/forja-nodos
COMUN="--sin-preguntas --censo caso=no --censo marco_pais=no --censo vigencia=no --censo herramienta=no"
{
echo "\$ python forja.py insertar cuarentena/scott_radical_candor/decidir_poner_nota_comunicar_proposito_limites.json [3 veredictos y censos]"
python forja.py insertar cuarentena/scott_radical_candor/decidir_poner_nota_comunicar_proposito_limites.json \
 --veredicto "recorrer_trece_elementos_proceso_evaluacion_formal|CONTINUA|madre=recorrer_trece_elementos_proceso_evaluacion_formal|MI CABEZA, Y LA ARISTA ES D.37 CON LA CUENTA ESCRITA POR EL LIBRO. Entro hoy, minutos despues que ella, y la arista se cablea en este mismo acto. LA CUENTA: cap_14 rotula ELEMENTS OF A FORMAL PERFORMANCE REVIEW PROCESS en L35, nombra los trece elementos uno por linea de la L39 a la L63, y despues los despliega numerados del 1 al 13. EL PASO DE LA MADRE ES EL 2: Uno, decide si pones nota o no. Es cap_14 L39 entera, Rating or no rating, y ahi se acaba: son cuatro palabras del libro. YO SOY EL ELEMENTO 1 Y LO DESPLIEGO EN 8 PASOS de cap_14 L65 a L71, bajo el rotulo 1. Rating or no rating de la linea 65, con lo que la cabeza no tiene en ninguna forma: las tres pegas de la escuela que dice que la nota es defectuosa por naturaleza, que revela mas del que califica que del calificado, que desanima a asumir riesgos y que la obsesion con ella estorba las conversaciones de desarrollo; los beneficios enfrentados, la transparencia sobre primas y ascensos y despidos, la empatia ruinosa que se instala si la quitas, la conversacion dura que la nota fuerza, y la correlacion entre jefes que sin nota no se puede hacer; y la comunicacion del proposito y de los limites si decides ponerla. LA CABEZA NOMBRA LA DECISION Y YO LA TOMO: es la figura exacta de la serie. CON MI ENTRADA LA SERIE PASA DE 0 A 1 DE 13 PARTES EN EL GRAFO." \
 --veredicto "entregar_evaluacion_formal_desempenio_nueve_consejos|SANO|EL VECINO DE CATALOGO QUE MAS CERCA ESTA DE LA PALABRA NOTA, leido con sus 22 pasos delante. LO QUE NOS SEPARA ES QUIEN DECIDE Y QUE SE DECIDE: el suyo es UN JEFE dentro de un proceso que ya existe, y su paso 21 dice da la noticia de la nota y de la retribucion despues de la evaluacion, o sea que da por hecha la nota y solo elige CUANDO se cuenta. EL MIO ES LA EMPRESA DECIDIENDO SI VA A HABER NOTA, que es la decision anterior a todas: mis pasos 1 a 5 ponen las pegas y los beneficios enfrentados, y mis pasos 6 a 8 comunican el proposito y los limites si se pone. Su entregable es una evaluacion dada sin sorpresas; el mio es una decision de disenio tomada con las dos listas delante. Y LO QUE NO ESCRIBO NI YO NI EL LIBRO: el texto NO dice como se pesa una pega contra un beneficio ni quien decide, asi que mi entregable dice que la decision se toma con las dos listas delante y no dice cual gana. SANO." \
 --veredicto "ser_honesto_transparente_desempenio|SANO|COMPARTIMOS LA IDEA DE LA TRANSPARENCIA Y LA APLICAMOS A COSAS DISTINTAS, leido con sus 7 pasos delante. EL SUYO ES UNA OBLIGACION CONTINUA DE UN JEFE CON UNA PERSONA: que esa persona sepa en todo momento cuales son tus expectativas y donde esta respecto a ellas, sin dar por hecho que lee entre lineas. EL MIO ES UNA DECISION DE EMPRESA QUE SE TOMA UNA VEZ: si va a haber nota de desempenio o no, y que se comunica sobre ella si la hay. Mi paso 6 habla de transparencia, si, pero de LA TRANSPARENCIA DEL PROPOSITO DE LA NOTA ante toda la plantilla, no de la claridad de un jefe con su persona a cargo. Su entregable vive en la cabeza de una persona; el mio es una decision de disenio comunicada a la empresa entera. SANO." \
 --censo "serie=los trece elementos del proceso formal de evaluacion de desempenio;papel=parte;cabeza=recorrer_trece_elementos_proceso_evaluacion_formal;nota=ELEMENTO 1 de los trece, rating or no rating, cap_14 L39 en la lista y L65 en el despliegue. Con esta entrada la serie pasa de 0 a 1 de 13 partes en el grafo" $COMUN
echo "CODIGO DE SALIDA: $?"
} > .v42/informes/n08_decidir_poner_nota.txt 2>&1 < /dev/null
date '+%H:%M:%S termina insercion candidato 8' >> .v42/informes/_tiempos.txt
