#!/bin/sh
# CADENA E de la vuelta 37: cap_13, pieza 12, la ultima del tramo.
. /c/Users/AlexDesk/Documents/forja-nodos/.v37/correr.sh

echo "cadena E arrancada (cap_13, pieza 12)" >> .v37/informes/_cadena.txt

corre e14_medir_critica.txt medir_critica_respuesta_oyente_brujula \
 --veredicto "desplegar_marco_franqueza_radical|CONTINUA|madre=desplegar_marco_franqueza_radical|ARISTA D.29, LA FILA 53 DE LA DEUDA, Y ES EL PAR QUE LA SENIAL SI LEVANTA: paso_contra_nodo 0.723 entre mi paso 4 y su paso 6. El paso 6 de la madre es Usa el marco como una brujula, para llevar cada conversacion concreta a un sitio mejor, y ahi se acaba. Este pone el COMO en 33 pasos de L289 a L322: los objetos que hay que observar (lo que dice, su lenguaje corporal, su mirada), las TRES respuestas con lo que se hace con cada una (tristeza en L299, enfado en L303, no oirte en L309), los guiones literales de L305, L315 y L321, y el error de las consecuencias prematuras de L319." \
 --veredicto "pedir_critica_primero_crear_seguridad_psicologica|CONTINUA|madre=pedir_critica_primero_crear_seguridad_psicologica|ARISTA D.29, LA FILA 51 DE LA DEUDA, Y LA ACTA 23 3.4 PIDE QUE DIGA POR QUE ESTE HIJO Y NO OTRO DE SU FAMILIA. Lo digo: el paso 4 de la madre es Cuatro, mide la critica y ajusta, que es la linea 83 del libro, y en el grafo la familia de medir tiene tres miembros. Este es el hijo porque LA MISMA UNIDAD que escribe el orden numerado, el epilogo, despliega su propio paso 4 en su propia seccion GAUGE CRITICISM de L289, y eso es exactamente lo que este nodo extrae. medir_guia_propia_pegatinas_marco coge la linea base con pegatinas de colores y ajustar_franqueza_oido_oyente busca la forma local de cada dimension: ninguno de los dos sale del epilogo. Declarado por lectura, ninguna senial lo levanto." \
 --veredicto "ajustar_franqueza_oido_oyente|CONTINUA|madre=ajustar_franqueza_oido_oyente|ARISTA D.29 DECLARADA POR LECTURA: el paso 1 de esa madre es Mide las dos dimensiones en el oido del que escucha y no en la boca del que habla, que es donde el texto dice que se miden, y ahi se acaba de decir COMO se mide. Mi paso 1 es esa misma frase, que L291 trae al epilogo diciendo que era otra linea muy tuiteada del libro y que en sus talleres quedo claro que no se explicaba sola. Este es el nodo que la explica: la brujula, los tres casos y sus guiones. Ninguna senial levanta el par." \
 --veredicto "manejar_enfado_persona_desafiada|CONTINUA|madre=manejar_enfado_persona_desafiada|ARISTA D.29 DECLARADA POR LECTURA: el paso 3 de esa madre es Cuando lo que dices duele, reconoce el dolor de la otra persona, y su paso 5 elimina del vocabulario la frase no te lo tomes como algo personal. Ahi se acaba. Este pone el COMO de reconocerlo: nombrar la emocion que ves con el guion de L305, ser humilde al nombrarla porque puedes estar entendiendola mal, no juzgarla, y la respuesta simple de como puedo ayudar. Mi paso 18 repite la prohibicion de la madre y mis pasos 12 a 19 la despliegan. Ninguna senial levanta el par." \
 --censo "serie=no" $COMUN
