#!/bin/sh
# CADENA B de la vuelta 37: cap_13, piezas 1 a 12, en el orden del libro.
. /c/Users/AlexDesk/Documents/forja-nodos/.v37/correr.sh

echo "cadena B arrancada (cap_13)" >> .v37/informes/_cadena.txt

corre b03_mejorar_consciencia.txt mejorar_consciencia_propia_relacional_dos_practicas \
 --veredicto "desplegar_plan_orden_operaciones_franqueza_radical|SANO|LO QUE LOS JUNTA ES UNA FORMULA MIA Y NO SU OBJETO, paso_contra_nodo 0.601 entre mi paso 11 y su paso 4: los dos nombran la primera parte por su rotulo. Pero la primera de cada uno es otra cosa. La del plan de cap_12 es COMPARTE TUS HISTORIAS (L15), la etapa de explicar la franqueza radical al equipo; la mia es la practica CUAL ES TU HISTORIA (cap_13 L41), el ejercicio de desenterrar tus cuatro historias. Aquel ordena las etapas del despliegue EN TU EQUIPO y entrega el plan recorrido; este ordena DOS PRACTICAS SOBRE TI MISMO y entrega tus dos consciencias trabajadas, que es lo que su L21 anuncia: el hilo comun siempre eres tu. Ninguno despliega al otro." \
 --censo "serie=las dos practicas que el texto desarrolla;papel=cabeza;nota=la cuenta esta escrita en la linea 39 del capitulo, We have developed two practices" $COMUN

corre b04_contar_cuatro.txt contar_cuatro_historias_propias_ver_hueco_intencion \
 --veredicto "evitar_presion_social_actos_equipo|SANO|OTRA VEZ UNA FORMULA MIA, paso_contra_nodo 0.619 entre mi paso 16 y su paso 6: los dos empiezan por Y cuenta con lo que el texto dice. Aquel evita que un acto no obligatorio se sienta obligatorio y entrega el acto sin presion; este desentierra tus cuatro historias del marco y entrega el hueco entre tu intencion y tu impacto visto. Ni el mismo objeto ni la misma activacion, y ninguno nombra el procedimiento del otro." \
 --veredicto "contar_historias_propias_explicar_franqueza_radical|CONTINUA|madre=contar_historias_propias_explicar_franqueza_radical|ARISTA D.29 Y LA DECLARA EL PROPIO LIBRO: cap_13 L43 escribe There's a brief paragraph about this in the final Getting Started section, but we have been asked for more detail about how to do this and why it works. El paso 4 de la madre manda buscar cual es tu version de la historia del um o de la de Bob y ahi se acaba; este pone las CUATRO historias con su pregunta de arranque escrita, la de franqueza radical en L45, la de agresion odiosa en L49, la de empatia ruinosa en L51 y la de insinceridad manipuladora en L53, en 17 pasos que la madre no tiene. Es la fila 42 de la deuda declarada en la vuelta 23." \
 --veredicto "mejorar_consciencia_propia_relacional_dos_practicas|CONTINUA|madre=mejorar_consciencia_propia_relacional_dos_practicas|ARISTA D.37 Y LA CUENTA ESTA ESCRITA: cap_13 L39 dice We have developed TWO practices, storytelling and role plays, o sea que dice CUANTAS y las NOMBRA. El paso 11 de la madre es Haz la primera, contar historias, que el texto despliega bajo el rotulo cual es tu historia, y ahi se acaba. Este es esa primera y la despliega en 17 pasos que la madre no tiene. Es la fila 43 de la deuda declarada en la vuelta 23, y ninguna senial la levanta." \
 --censo "serie=las dos practicas que el texto desarrolla;papel=paso;cabeza=mejorar_consciencia_propia_relacional_dos_practicas" $COMUN

corre b05_triangulo.txt practicar_triangulo_critica_tres_papeles \
 --veredicto "abrazar_incomodidad_silencio_contar_seis|SANO|similitud_texto 0.375 entre mi paso 4 y su paso 5, y lo que la senial ve es que los dos son ejercicios con un companiero. El objeto es otro: aquel practica AGUANTAR EL SILENCIO despues de pedir critica y entrega la respuesta salida de el; este monta un TRIANGULO DE TRES PAPELES para ver el impacto de tus palabras y entrega el recorrido dibujado sobre el marco de dos por dos. Son dos personas contra tres, y ninguno sirve para lo del otro." \
 --veredicto "escuchar_entender_critica_dominar_defensa|SANO|similitud_texto 0.352 entre mi paso 1 y su paso 6. Aquel domina TU defensa cuando la critica te llega a ti, con el ejercicio de escuchar tres minutos sin interrumpir; este te pone a DAR una critica que no diste y a que otros dos vean como aterriza. Comparten que se practica con otros y ni un acto." \
 --veredicto "mejorar_consciencia_propia_relacional_dos_practicas|CONTINUA|madre=mejorar_consciencia_propia_relacional_dos_practicas|ARISTA D.37 Y LA CUENTA ESTA ESCRITA: cap_13 L39 dice We have developed TWO practices, storytelling and role plays. El paso 12 de la madre es Haz la segunda, el juego de papeles, que el texto despliega bajo el rotulo el triangulo de la critica, y ahi se acaba. Este es esa segunda y la despliega en 15 pasos de L59 a L72 que la madre no tiene: el grupo de tres, quien describe la critica, quien hace de destinatario exagerando la defensa, quien observa con el marco, y los cuatro desplomes que hay que cazar. Es la fila 44 de la deuda declarada en la vuelta 23." \
 --censo "serie=las dos practicas que el texto desarrolla;papel=paso;cabeza=mejorar_consciencia_propia_relacional_dos_practicas" $COMUN
