#!/bin/sh
# CADENA D de la vuelta 37: cap_13, piezas 8 a 11.
. /c/Users/AlexDesk/Documents/forja-nodos/.v37/correr.sh

echo "cadena D arrancada (cap_13, piezas 8 a 11)" >> .v37/informes/_cadena.txt

corre d10_escuchar.txt escuchar_entender_critica_dominar_defensa \
 --veredicto "cambiar_forma_trabajar_conservar_plantilla|SANO|PAR ENTRE DOS LIBROS, Y ES LA POBLACION QUE D.38.5 ANIADIO: aquel espera en la bandeja de marquet_turn_the_ship. paso_contra_nodo 0.634 entre mi paso 4 y su paso 2, y lo que los junta es una formula mia, que es lo que el texto pone por encima de lo demas contra que es lo que el texto recomienda por encima de mucha rotacion. Aquel cambia como trabaja la gente que ya tienes en vez de renovarla; este domina tu propia defensa mientras te critican. Ni un objeto compartido." \
 --veredicto "contar_historias_propias_explicar_franqueza_radical|SANO|similitud_texto 0.393 entre mi paso 4 y su paso 3, y otra vez es mi formula de y sobre todo X, que es lo que el texto pone por encima. Aquel explica la franqueza radical a tu equipo con tus historias; este entrega TU PROPIA DEFENSA DOMINADA mientras te critican a ti. Comparten la palabra explicar y ni un acto." \
 --veredicto "abrazar_incomodidad_silencio_contar_seis|SANO|0.446 en este sentido y 0.449 en el otro, LA SENIAL MAS FUERTE DEL TRAMO Y POR ENCIMA DE 0.40. La ACTA 23 2.1 discutible 12 ya la adjudico con los pasos leidos: aquel aguanta el silencio ANTES de que exista respuesta; este domina tu defensa MIENTRAS la critica llega. Ejercicios distintos, contar hasta seis contra hablar tres minutos sin interrumpir, y L237 los enumera por separado." \
 --veredicto "premiar_franqueza_hacer_escucha_tangible|SANO|similitud_texto 0.363 entre mi paso 5 y su paso 8. Son el elemento TERCERO y el CUARTO de los cuatro que L237 enumera por separado, con la misma madre: este escucha sin defenderse, aquel premia lo que oyo haciendo tangible la escucha en una reunion de equipo. Ninguno despliega al otro." \
 --veredicto "practicar_triangulo_critica_tres_papeles|SANO|similitud_texto 0.350 entre mi paso 6 y su paso 1. Aquel monta un triangulo de tres papeles para ver el impacto de una critica que TU DAS; este domina tu defensa cuando la critica te llega A TI. Comparten que se practica con otros y ni un acto." \
 --veredicto "pedir_critica_primero_crear_seguridad_psicologica|CONTINUA|madre=pedir_critica_primero_crear_seguridad_psicologica|ARISTA D.37 Y LA CUENTA ESTA ESCRITA: cap_13 L113 dice each of the FOUR tips. El paso 17 de la madre los enumera y ahi se acaba. Este es el TERCERO, escuchar con intencion de entender, y lo despliega en 13 pasos de L199 a L214 que la madre no tiene: la respuesta de pelea, huida o bloqueo, el ejercicio de respiracion, el trago de agua y el ejercicio de tres minutos sin interrumpir con sus tres prohibiciones. Es la fila 47 de la deuda declarada en la vuelta 23." \
 --veredicto "abrazar_incomodidad_arrancar_critica_equipo|CONTINUA|madre=abrazar_incomodidad_arrancar_critica_equipo|ARISTA D.29 ADJUDICADA POR LA ACTA 23 3.3: L113 dice OFFERED IN THE BOOK y ese libro es cap_09. El paso 12 de esa madre es Escucha con intencion de entender y no de responder, con la frase asi que lo que te oigo decir es, y ahi se acaba. Este pone el por que cuesta y el ejercicio de los tres minutos, que la madre no tiene. Es la fila 56 de la deuda." \
 --veredicto "crear_cultura_escucha_equipo|SANO|Declarado por lectura, ninguna senial lo levanto, y lo leo porque los dos llevan la palabra escuchar. Aquel monta un SISTEMA para que el equipo se escuche entre si, con el equipo de ideas y la vuelta a la mesa en las reuniones; este domina TU defensa mientras te critican a ti. Ni el mismo sujeto ni el mismo entregable." \
 --veredicto "escuchar_callado_equipo_tranquilizar_incomodo|SANO|Declarado por lectura, ninguna senial lo levanto. Aquel reserva diez minutos de cada reunion a solas para escuchar con la cara neutra y tranquiliza a quien ese silencio incomoda; este domina tu defensa cuando la critica llega y entrega la critica escuchada entera. Los dos callan y por motivos distintos: aquel para que le cuenten lo que no quiere oir, este para no ponerse a la defensiva." \
 --censo "serie=los cuatro elementos de pedir critica;papel=paso;cabeza=pedir_critica_primero_crear_seguridad_psicologica" $COMUN

corre d11_premiar.txt premiar_franqueza_hacer_escucha_tangible \
 --veredicto "escuchar_entender_critica_dominar_defensa|SANO|similitud_texto 0.375 entre mi paso 8 y su paso 5, los dos empiezan por Practicalo asi. Son el elemento CUARTO y el TERCERO de los cuatro que L237 enumera por separado, con la misma madre: aquel escucha sin defenderse y entrega la critica escuchada entera; este entrega LA LISTA DE LAS TRES O CUATRO CRITICAS RECIENTES y lo que hiciste con ellas contado en una reunion de equipo." \
 --veredicto "pedir_critica_primero_crear_seguridad_psicologica|CONTINUA|madre=pedir_critica_primero_crear_seguridad_psicologica|ARISTA D.37 Y LA CUENTA ESTA ESCRITA: cap_13 L113 dice each of the FOUR tips. El paso 17 de la madre los enumera y ahi se acaba. Este es el CUARTO, hacer tangible la escucha premiando la franqueza, y lo despliega en 20 pasos de L215 a L234 que la madre no tiene: el sesgo de negatividad con la frase de Rick Hanson, el ejemplar de Sara Blakely, los DOS ejercicios rotulados y el protocolo de la critica con la que no estas de acuerdo. Es la fila 48 de la deuda declarada en la vuelta 23." \
 --veredicto "abrazar_incomodidad_arrancar_critica_equipo|CONTINUA|madre=abrazar_incomodidad_arrancar_critica_equipo|ARISTA D.29 ADJUDICADA POR LA ACTA 23 3.3: L113 dice OFFERED IN THE BOOK y ese libro es cap_09. El paso 14 de esa madre es Premia la critica para conseguir mas, con la goma elastica de la muneca, y ahi se acaba. Este pone la lista de las tres o cuatro criticas, la pesca cuando la lista esta vacia, lo que se cuenta en la reunion y como se premia una critica con la que no estas de acuerdo. Es la fila 57 de la deuda." \
 --veredicto "pedir_critica_equipo_premiarla|SANO|ES EL PAR MAS CARO DE FALLAR DE ESTA PIEZA Y LO DECLARO POR LECTURA, porque ninguna senial lo levanta. Aquel premia la franqueza EN EL ACTO de la conversacion, con la primera queja pequenia agradecida en publico y el caso de Tokio; este entrega la LISTA de las tres o cuatro criticas recientes contada despues en una reunion de equipo, con el sesgo de negatividad, la pesca cuando la lista esta vacia y el protocolo de la critica con la que no estas de acuerdo, que aquel no tiene. Comparten el acto de premiar y los dos tienen procedimiento fuera de el." \
 --censo "serie=los cuatro elementos de pedir critica;papel=paso;cabeza=pedir_critica_primero_crear_seguridad_psicologica" $COMUN

corre d12_integrar.txt integrar_peticion_critica_rutina_existente \
 --veredicto "pedir_critica_primero_crear_seguridad_psicologica|SANO|paso_contra_nodo 0.733 entre mi paso 6 y su paso 17, LA MAS ALTA DEL TRAMO, Y LA ACTA 23 2.1 DISCUTIBLE 5 YA LA ADJUDICO: son dos lineas distintas del libro haciendo dos trabajos distintos. L113 ANUNCIA los cuatro elementos antes de desplegarlos y L237 los RECAPITULA despues para entregarlos al habito. Aquel entrega el porque de pedir primero; este entrega la peticion METIDA EN LA AGENDA de la reunion a solas y anunciada al equipo. No quito la enumeracion de ninguno de los dos y digo el coste de hacerlo: quitarla de su paso 17 deja cuatro aristas sin cita, y quitarla de mi paso 6 rompe el traspaso que L237 escribe." \
 --veredicto "abrazar_incomodidad_silencio_contar_seis|SANO|similitud_texto 0.356 entre mi paso 1 y su paso 1, y otra vez es mi formula de Parte de lo que. Aquel aguanta el silencio de UNA peticion concreta; este mete la peticion en la rutina que ya tienes para que deje de depender de tu acordarte. Son el segundo elemento y el habito que los junta, y L237 los separa." \
 --veredicto "montar_reuniones_solas_mentalidad_frecuencia|SANO|DECLARADO POR LECTURA, ninguna senial lo levanta, y lo leo porque los dos viven en la reunion a solas. Aquel entrega las reuniones a solas montadas y no canceladas con su agenda, y en sus 22 pasos no hay ni uno que meta la peticion de critica al final; este entrega esa peticion metida ahi. Procedimientos vecinos con entregables distintos y ninguno despliega al otro." \
 --censo "serie=no" $COMUN

corre d13_dar_elogio.txt dar_elogio_disciplina_igual_critica \
 --veredicto "pedir_critica_primero_crear_seguridad_psicologica|CONTINUA|madre=pedir_critica_primero_crear_seguridad_psicologica|ARISTA D.29, LA FILA 49 DE LA DEUDA, Y LA ACTA 23 3.4 LA SOSTUVO PIDIENDO QUE EL DIA DEL CABLEADO SE DIGA POR QUE ESTE HIJO Y NO OTRO DE SU FAMILIA. Lo digo: el paso 2 de la madre es Dos, da elogio, que es la linea 79 del libro, y en el grafo hay CINCO procedimientos de elogio. Este es el hijo porque LA MISMA UNIDAD que escribe el orden numerado, el epilogo, despliega su propio paso 2 en sus propias secciones, PRAISE FOCUS ON THE GOOD STUFF de L247 y APPLY THE SAME DISCIPLINE TO PRAISE de L275, y eso es exactamente lo que este nodo extrae. Los otros cinco salen de cap_05, cap_09 y cap_10, y el epilogo no manda a ninguno de ellos. ENTRO CON LA COLA VACIA, que certifica que no tengo gemelo y NO que no tenga madre." \
 --veredicto "equilibrar_elogio_critica_equipo|CONTINUA|madre=equilibrar_elogio_critica_equipo|ARISTA D.29 DECLARADA POR LECTURA Y CON UNA CORRECCION DENTRO: el paso 9 de esa madre dice Pasa el mismo tiempo asegurandote de tener bien los hechos antes de elogiar a alguien que antes de criticarle, son las dos preguntas que el texto recoge de Karen Sipprell, colega suya en Apple, y ahi se acaba. Este despliega esa regla en L275 a L287: la pregunta tal como la hacen en sus talleres con su respuesta tipica de ninguno, lo que pasa cuando eres vago, el elogio concreto como modelo a seguir, las tres pautas de L279 y el ejercicio de pareja con sus dos ejemplares literales. Y CORRIJO AQUI UNA AFIRMACION FALSA DE MI PROPIO RESUMEN, que decia que la pregunta de Karen Sipprell no estaba en ninguno de los dos vecinos: SI ESTA, en el paso 9 de esta madre, y por eso el par es CONTINUA y no SANO. La clase no se mueve: de mis 20 pasos, ese es UNO." \
 --veredicto "elogiar_trabajo_especifico_contexto|CONTINUA|madre=elogiar_trabajo_especifico_contexto|ARISTA D.29 DECLARADA POR LECTURA: el paso 6 de esa madre es Se tan concreto y tan a fondo con el elogio como con la critica, y baja al detalle, que es literalmente el rotulo de mi seccion de L275, APPLY THE SAME DISCIPLINE TO PRAISE THAT YOU DO TO CRITICISM, dicho en una linea. Ahi se acaba. Este pone el COMO en 20 pasos: la imagen del acelerador y el freno, el elogio usado como arma, la vaguedad que deja a la persona tratada con condescendencia, y el ejercicio de pareja. Ninguna senial levanta el par: entre con la cola vacia." \
 --veredicto "elogiar_publico_criticar_privado_sus_tres_matices|SANO|DECLARADO POR LECTURA porque es el tercero de la familia de elogio y la ACTA 23 pide decir por que no es el hijo de la arista 49. Aquel decide DONDE se dice, en publico o en privado, con sus tres matices; este decide CON QUE DISCIPLINA se dice, comprobando los hechos antes y bajando al detalle. Mi paso 15 repite su regla como una de las tres pautas que L279 recoge, y repetir una pauta dentro de una lista no es desplegar el procedimiento de nadie." \
 --censo "serie=no" $COMUN
