#!/bin/sh
# CADENA C de la vuelta 37: cap_13, piezas 4 a 10.
. /c/Users/AlexDesk/Documents/forja-nodos/.v37/correr.sh

echo "cadena C arrancada (cap_13, piezas 4 a 10)" >> .v37/informes/_cadena.txt

corre c06_pedir_critica_primero.txt pedir_critica_primero_crear_seguridad_psicologica \
 --veredicto "integrar_peticion_critica_rutina_existente|SANO|LA SENIAL MAS ALTA DEL TRAMO EN PASO CONTRA NODO, 0.733 entre mi paso 17 y su paso 6, Y LA ACTA 23 2.1 DISCUTIBLE 5 YA LA ADJUDICO: son dos lineas distintas del libro haciendo dos trabajos distintos. L113 ANUNCIA los cuatro elementos antes de desplegarlos, que es la cita de las cuatro aristas D.37 de mi paso 17; L237 los RECAPITULA despues para entregarlos al habito (Now that you've practiced the four elements). Yo entrego el porque de pedir primero, con Edmondson y la medicion de Google; aquel entrega la peticion metida en la agenda de la reunion a solas. Hermanos, y ninguno despliega al otro." \
 --veredicto "empezar_cultura_franqueza_radical|CONTINUA|madre=empezar_cultura_franqueza_radical|ARISTA D.29 QUE DECLARA EL PROPIO LIBRO: cap_13 L87 escribe The first edition describes this order of operations, o sea que nombra por su nombre lo que aquel nodo ya extrajo de cap_05. Ninguna senial levanta el par y lo declaro por lectura. La madre pone el orden EN PROSA en 6 pasos (empieza explicando la idea, despues pide que te critiquen, empieza recibiendo y no repartiendo, cuando des empieza por el elogio) y NO tiene ni la numeracion de los cinco, ni los pasos cuatro y cinco, ni una sola razon medida. Este trae la lista numerada entera de L77 a L85, la definicion de seguridad psicologica de Amy Edmondson, la medicion de Google con sus cinco dinamicas y el circulo virtuoso. ES EL SITIO DONDE MAS CERCA ESTOY DE UN REPITE EN TODO EL CAPITULO y por eso va marcado como discutible en mi reporte, pero lo que aporta no esta en la madre." \
 --veredicto "fomentar_guia_reciproca_companieros|CONTINUA|madre=pedir_critica_primero_crear_seguridad_psicologica|ARISTA D.29, LA FILA 52 DE LA DEUDA, Y LA ACTA 23 3.4 LA SOSTUVO PIDIENDO QUE EL DIA DEL CABLEADO SE DIGA POR QUE ESE HIJO Y NO OTRO DE SU FAMILIA. Lo digo, y aqui la familia tiene UN SOLO MIEMBRO: mi paso 5 es Cinco, fomenta el elogio y la critica entre los demas, que es la linea 85 del libro, y el unico procedimiento del grafo que fomenta la guia ENTRE PARES es ese, con el premio nominado y la metedura de pata contada por uno mismo. Lo declaro por lectura porque ninguna senial lo levanta: mi cola trajo un solo vecino y no era este." \
 --censo "serie=los cuatro elementos de pedir critica;papel=cabeza;nota=la cuenta esta escrita en la linea 113 del capitulo, each of the four tips for soliciting criticism" $COMUN

corre c07_elegir_pregunta.txt elegir_pregunta_recurrente_pedir_critica \
 --veredicto "pedir_critica_primero_crear_seguridad_psicologica|CONTINUA|madre=pedir_critica_primero_crear_seguridad_psicologica|ARISTA D.37 Y LA CUENTA ESTA ESCRITA: cap_13 L113 dice each of the FOUR tips for soliciting criticism y L237 los nombra uno a uno. El paso 17 de la madre los enumera y ahi se acaba. Este es el PRIMERO, dar con una pregunta recurrente, y lo despliega en 24 pasos de L115 a L166 que la madre no tiene: los cuatro atributos con su rotulo propio (sincera, que no se conteste con un si o un no, concreta frente a abierta, frecuencia), las nueve preguntas literales de L141 a L157 y el ejercicio de probarlas con un companiero de confianza. Es la fila 45 de la deuda declarada en la vuelta 23. ENTRO CON LA COLA VACIA, que certifica que no tiene gemelo y NO que no tenga madre (EXTRACTOR.md 11): esta arista la caza la lectura." \
 --veredicto "abrazar_incomodidad_arrancar_critica_equipo|CONTINUA|madre=abrazar_incomodidad_arrancar_critica_equipo|ARISTA D.29 ADJUDICADA POR LA ACTA 23 3.3: L113 dice four tips for soliciting criticism OFFERED IN THE BOOK, y ese libro es el capitulo seis, que en esta casa es cap_09. El paso 7 de esa madre es Ten una pregunta de cabecera, con la que su autora adopto de Fred Kofman, y ahi se acaba. Este pone los cuatro atributos que hacen buena una pregunta y nueve ejemplares literales, que la madre no tiene. Es la fila 54 de la deuda. Ninguna senial la levanta: mi cola salio vacia." \
 --veredicto "exigir_critica_jefe_reticente|SANO|NO SON EL MISMO TRABAJO Y LO DIGO CON LOS DOS LADOS MEDIDOS: aquel se activa cuando es TU JEFE quien no se atreve a criticarte y entrega la critica arrancada hacia arriba, con sus tres frases literales; este se activa cuando eres tu quien va a pedir critica a tu equipo y entrega TRES O CUATRO PREGUNTAS ESCRITAS Y PROBADAS con un companiero de confianza. La primera de las tres frases de aquel (que puedo hacer o dejar de hacer para ponertelo mas facil) es justo la pregunta que MI paso 7 corrige por darle una salida facil a quien teme el conflicto, asi que no es que uno despliegue al otro: es que este REVISA la de aquel, y eso se declara como lectura y no como arista. Declarado por lectura, ninguna senial lo levanto." \
 --veredicto "pedir_critica_equipo_premiarla|SANO|aquel entrega la critica pedida a un equipo que no habla, con el silencio aguantado y la primera franqueza premiada; este entrega las preguntas escritas y probadas. El acto compartido es pedir critica y los dos tienen procedimiento fuera de el. Declarado por lectura, ninguna senial lo levanto." \
 --censo "serie=los cuatro elementos de pedir critica;papel=paso;cabeza=pedir_critica_primero_crear_seguridad_psicologica" $COMUN

corre c08_resolver_dudas.txt resolver_dudas_frecuentes_pedir_critica \
 --veredicto "despedir_persona_franqueza_radical|SANO|paso_contra_nodo 0.621 entre mi paso 5 y su paso 8, y lo que los junta es la palabra ayudar: el mio dice Pregunta si pueden ayudarte a resolver el problema y el suyo Preguntate si puedes ayudar haciendo una presentacion. Aquel prepara y tiene la conversacion de un despido; este contesta cuatro dudas frecuentes de quien empieza a PEDIR critica (cap_13 L167 a L186). Ni el mismo objeto, ni la misma activacion, ni el mismo entregable." \
 --veredicto "resolver_dudas_frecuentes_reuniones_salto_nivel|SANO|familia_id 0.375, la mas alta que me levanta nadie, Y ES LA FORMA Y NO EL TRABAJO: los dos son un bloque de preguntas frecuentes que el libro contesta una a una, y esta casa ya trato esa figura como nodo al insertar aquel. Aquel contesta dudas de las reuniones de salto de nivel; este contesta cuatro dudas de pedir critica, escritas como pregunta en L169, L173, L177 y L181. Comparten la forma y ni un objeto." \
 --censo "serie=no" $COMUN

corre c09_abrazar.txt abrazar_incomodidad_silencio_contar_seis \
 --veredicto "escuchar_entender_critica_dominar_defensa|SANO|ES LA SENIAL MAS FUERTE DE TODO EL TRAMO, similitud_texto 0.449, POR ENCIMA DE 0.40, y EXTRACTOR.md 11 mide que por encima de 0.40 hay 325 gemelos y CERO ajenos en el catalogo de calibracion. AUN ASI SON DOS, y no lo decido yo solo: la ACTA 23 2.1 discutible 12 lo adjudico con los pasos leidos. Momentos distintos: este aguanta el silencio ANTES de que exista respuesta y entrega la respuesta salida de el; aquel domina tu defensa MIENTRAS la critica llega y entrega la critica escuchada entera. Ejercicios distintos y ninguno sirve para lo del otro, contar hasta seis contra hablar tres minutos sin interrumpir. Y L237 los enumera POR SEPARADO como el segundo y el tercero de los cuatro elementos." \
 --veredicto "practicar_triangulo_critica_tres_papeles|SANO|similitud_texto 0.373 entre mi paso 5 y su paso 4, y lo que la senial ve es que los dos son ejercicios con companieros. Este aguanta el silencio despues de PEDIR critica, con dos personas; aquel monta un triangulo de TRES papeles para ver el impacto de una critica que tu DAS. Ni el mismo acto ni el mismo entregable." \
 --veredicto "premiar_franqueza_hacer_escucha_tangible|SANO|similitud_texto 0.353 entre mi paso 7 y su paso 8, y los dos empiezan por Practicalo asi, que es una formula mia. Son el elemento SEGUNDO y el CUARTO de los cuatro que L237 enumera por separado, con la misma madre y sin desplegarse el uno al otro: este aguanta el silencio, aquel premia la franqueza con la lista de las tres o cuatro criticas recientes contada en publico." \
 --veredicto "contar_historias_propias_explicar_franqueza_radical|SANO|similitud_texto 0.376 entre mi paso 1 y su paso 3, otra vez una formula mia. Aquel explica la franqueza radical a tu equipo con tus historias (cap_12 L17); este aguanta el silencio despues de pedir critica (cap_13 L187 a L198). Comparten la etapa del plan y ni un acto." \
 --veredicto "pedir_critica_primero_crear_seguridad_psicologica|CONTINUA|madre=pedir_critica_primero_crear_seguridad_psicologica|ARISTA D.37 Y LA CUENTA ESTA ESCRITA: cap_13 L113 dice each of the FOUR tips. El paso 17 de la madre los enumera y ahi se acaba. Este es el SEGUNDO, abrazar la incomodidad, y lo despliega en 12 pasos de L187 a L198 que la madre no tiene: no dejarle salir del apuro, darle tiempo y espacio, resistir la tentacion de rellenar el silencio, el ejercicio de contar hasta seis y el volver a preguntar. Es la fila 46 de la deuda declarada en la vuelta 23." \
 --veredicto "abrazar_incomodidad_arrancar_critica_equipo|CONTINUA|madre=abrazar_incomodidad_arrancar_critica_equipo|ARISTA D.29 ADJUDICADA POR LA ACTA 23 3.3: L113 dice OFFERED IN THE BOOK y ese libro es cap_09. El paso 8 de esa madre es Abraza la incomodidad, preparate para la respuesta que llega casi siempre y comprometete a seguir hasta tener una respuesta genuina, y ahi se acaba. Este pone el ejercicio con su cuenta escrita, el seis de L193 y L195, y lo que se hace con quien aun asi se calla. Es la fila 55 de la deuda. LA CLASE NO SE TOCA: la ACTA 23 2.1 discutible 8 ya sostuvo que son dos nodos, y LA ARISTA NO EXCULPA ni funde." \
 --veredicto "exigir_critica_jefe_reticente|CONTINUA|madre=exigir_critica_jefe_reticente|ARISTA D.29 QUE LEVANTO YO EN ESTA VUELTA Y QUE NADIE HABIA DECLARADO, y va marcada como discutible en mi reporte: el paso 6 de esa madre es literalmente Cuenta hasta seis en tu cabeza, y su paso 7 Abraza la incomodidad, y ahi se acaba. Este es el nodo que despliega esa cuenta en 12 pasos, con el por que (le metes en una situacion incomoda), el ejercicio con un companiero amistoso, la medida de cuantos segundos aguanta y el que hacer si sigue callado. Ninguna senial lo levanta. DIGO LO QUE TIENE DE DISCUTIBLE: este hijo ya tiene dos madres declaradas y esta es la tercera, y quien lea que tres madres es demasiado tiene donde discutirlo." \
 --censo "serie=los cuatro elementos de pedir critica;papel=paso;cabeza=pedir_critica_primero_crear_seguridad_psicologica" $COMUN
