#!/bin/sh
# CADENA A de la vuelta 37: cap_12 entero, sus dos piezas, en el orden del libro.
. /c/Users/AlexDesk/Documents/forja-nodos/.v37/correr.sh

echo "cadena A arrancada (cap_12)" >> .v37/informes/_cadena.txt

corre a01_desplegar_plan.txt desplegar_plan_orden_operaciones_franqueza_radical \
 --veredicto "bloquear_tiempo_pensar_calendario|CONTINUA|madre=desplegar_plan_orden_operaciones_franqueza_radical|ARISTA D.29 QUE ESPERABA EN COLA DESDE LA LINEA 371 DE LA BITACORA, escrita al insertar el hijo cuando yo todavia estaba en la bandeja. Mi paso 30 es literalmente Pon algo de tiempo para pensar en tu calendario, que es cap_12 L39 (Put some think time in your calendar), y ahi se acaba. El hijo pone el como en 6 pasos de cap_11. Es la fila 40 de la deuda declarada en la vuelta 23, y hoy se cierra porque ya vivo yo." \
 --veredicto "desplegar_tres_conversaciones_carrera|CONTINUA|madre=desplegar_plan_orden_operaciones_franqueza_radical|ARISTA D.29 QUE ESPERABA EN COLA DESDE LA LINEA 429 DE LA BITACORA. Mi paso 12 dice que cuando eso este en marcha ya estas listo para las conversaciones de carrera, empiezalas con tu equipo y empieza por quien lleva mas tiempo contigo, que es cap_12 L25, y ahi se acaba. El hijo pone las tres conversaciones en 12 pasos de cap_10. Es la fila 39 de la deuda de la vuelta 23." \
 --veredicto "armar_plan_anual_crecimiento_equipo|CONTINUA|madre=desplegar_plan_orden_operaciones_franqueza_radical|ARISTA D.29 QUE ESPERABA EN COLA DESDE LA LINEA 438 DE LA BITACORA. Mi paso 32 es Planea el futuro de tu equipo, empieza a hacer un plan de gestion del crecimiento para cada persona, que es cap_12 L41, y ahi se acaba: no digo ni las casillas, ni la mirada de fuera, ni los tres a cinco puntos, ni la equidad entre niveles. El hijo lo despliega en 29 pasos de cap_10 L93 a L125. Es la fila 41 de la deuda de la vuelta 23, y su paso_contra_nodo medido entonces fue 0.741." \
 --veredicto "evitar_obsesion_ascenso_estatus|CONTINUA|madre=desplegar_plan_orden_operaciones_franqueza_radical|ARISTA D.29 QUE ESPERABA EN COLA DESDE LA LINEA 461 DE LA BITACORA, escrita por la vuelta 36 al insertar cap_10. Es la PRIMERA MITAD de mi paso 33: asegurate de que no estas creando una cultura obsesionada con el ascenso, que es cap_12 L41, y ahi se acaba. El hijo pone el como en 10 pasos de cap_10 L229 a L237: el correo de celebracion que no se manda, el cambio de papel que si se anuncia y el elogio apuntado al trabajo y no al estatus." \
 --veredicto "reconocer_excelencia_trayectoria_gradual|CONTINUA|madre=desplegar_plan_orden_operaciones_franqueza_radical|ARISTA NUEVA, LA SEGUNDA REMISION DE cap_12 L41, QUE LA VUELTA 36 NO CABLEO Y QUE LA ACTA 35 DEJA MEDIDA. La misma frase lleva DOS destinos y hasta hoy solo estaba cableado uno. Es la SEGUNDA MITAD de mi paso 33: dedica un pensamiento extra a como estas recompensando a tus estrellas de rock (see chapter seven), y ese destino es la seccion REWARD YOUR ROCK STARS de cap_10 L225. El nodo que pone las vias de recompensar SIN ascender es este: el agradecimiento en persona y por escrito, el papel de experto de referencia con su condicion de honor y no de castigo, y la presentacion publica a los colegas, 13 pasos de L239 a L251 que yo no tengo. Y NO ES EL OTRO NODO DE ESA SECCION: aquel se activa cuando vas a ANUNCIAR un ascenso y ya cuelga de la primera mitad de este mismo paso. NOTA DE FIDELIDAD: mi paso 33 decia superestrellas y lo reescribi en esta misma vuelta contra su linea, porque rock star y superstar son las dos mitades opuestas del marco de este libro (cap_10 L19 y L227)." \
 --veredicto "contar_historias_propias_explicar_franqueza_radical|CONTINUA|madre=desplegar_plan_orden_operaciones_franqueza_radical|ARISTA D.29, LA FILA 38 DE LA DEUDA DECLARADA EN LA VUELTA 23. Mi paso 4 NOMBRA la etapa por su rotulo, comparte tus historias, que es cap_12 L15, y ahi se acaba. El hijo la despliega en 8 pasos de L17 con los seis medios que yo no tengo: explicarlo con tus palabras, darles el libro, ensenarles los videos de la web, tu version de la historia del um, tu version de la de Bob, y mostrar vulnerabilidad. El hijo espera en la bandeja de cap_12, asi que la arista queda EN COLA y se cierra en esta misma vuelta cuando entre, dos insercciones despues." \
 --veredicto "desplegar_marco_franqueza_radical|SANO|LA SENIAL QUE MAS ME SORPRENDE DEL TRAMO, familia_id 0.429, entre mi paso 8 y su paso 1, Y TRAE UNA CONTRADICCION DEL LIBRO QUE DECLARO EN VEZ DE RESOLVER. Mi paso 8 sale de cap_12 L21 y dice: si quieres, copia el marco de la franqueza radical del capitulo dos y lleva ahi la cuenta de quien te dice que. El paso 8 de ese vecino dice: No escribas nombres en las casillas, y su entregable remata sin nombres escritos en las casillas. LAS DOS FRASES SON DEL MISMO LIBRO EN DOS SITIOS DISTINTOS y lo subo como pregunta a mi reporte, sin tocar ninguno de los dos nodos. MI VEREDICTO ES SANO Y NO CONTINUA, y digo por que: lo que mi paso 8 nombra no es el procedimiento de ese vecino. Aquel despliega el marco COMO RECORDATORIO PARA EL EQUIPO, recortado, fotocopiado, en la nevera y repartido entre colegas, con sus dos prohibiciones; el mio propone un uso PRIVADO Y DISTINTO, llevar la cuenta de quien te critica, que es justo el uso que su paso 8 prohibe. Nombrar no es procedimentar, y aqui ni siquiera nombra lo mismo. VA MARCADO COMO DISCUTIBLE EN MI REPORTE, porque mi paso 8 empieza por copia el marco y sus pasos 2 a 5 son literalmente como se copia." \
 --censo "serie=no" $COMUN

corre a02_contar_historias.txt contar_historias_propias_explicar_franqueza_radical \
 --veredicto "escuchar_entender_critica_dominar_defensa|SANO|LO QUE LOS JUNTA ES UNA FORMULA MIA Y NO SU OBJETO, similitud_texto 0.380 entre mi paso 3 y su paso 4: el mio dice explicala sobre todo con tus propias palabras, que es lo que el texto dice que sale mejor, y el suyo Y sobre todo practica con otros, que es lo que el texto pone por encima de lo demas. Este entrega la franqueza radical EXPLICADA a tu equipo con tus historias contadas (cap_12 L17); aquel entrega TU PROPIA DEFENSA DOMINADA mientras te critican a ti (cap_13 L199 a L214). Ni la misma activacion ni el mismo entregable, y ninguno nombra el procedimiento del otro en una linea." \
 --veredicto "contar_cuatro_historias_propias_ver_hueco_intencion|CONTINUA|madre=contar_historias_propias_explicar_franqueza_radical|ARISTA D.29 Y LA DECLARA EL PROPIO LIBRO: cap_13 L43 escribe There's a brief paragraph about this in the final Getting Started section, but we have been asked for more detail about how to do this and why it works, y ese brief paragraph es este nodo. Mi paso 4 manda buscar cual es TU version de la historia del um o de la de Bob y ahi se acaba; el hijo pone las CUATRO historias con su pregunta de arranque escrita, la de franqueza radical en L45, la de agresion odiosa en L49, la de empatia ruinosa en L51 y la de insinceridad manipuladora en L53, en 17 pasos que yo no tengo. Es la fila 42 de la deuda de la vuelta 23. El hijo espera en la bandeja de cap_13, asi que la arista queda EN COLA y se cierra dos insercciones despues, en esta misma vuelta." \
 --veredicto "abrazar_incomodidad_silencio_contar_seis|SANO|OTRA VEZ MI FORMULA, similitud_texto 0.380 en este sentido y 0.376 en el otro, entre mi paso 3 y su paso 1. Este explica la franqueza radical a tu equipo con tus historias; aquel aguanta el silencio DESPUES de pedir critica, contando hasta seis en tu cabeza (cap_13 L187 a L198). Comparten estar los dos en el plan de arranque y ni un acto." \
 --veredicto "empezar_cultura_franqueza_radical|SANO|DECLARADO POR LECTURA Y ES MI PAR MAS CERCANO, porque ninguna senial lo levanta y seria negligente no mirarlo. Aquel entrega el ARRANQUE HECHO EN SU ORDEN (la idea explicada, la critica pedida antes que dada, el elogio antes que la critica, la frontera peligrosa entendida) y NO dice como se explica la idea: su paso 2 es Empieza explicando la idea, y ahi se acaba. Este entrega TUS HISTORIAS CONTADAS y trae los seis medios de hacerlo. Comparten un solo acto, explicar la idea, y los dos tienen procedimiento fuera de el, asi que la vara de manual 4 no tiene bascula. Va marcado como discutible en mi reporte." \
 --censo "serie=no" $COMUN
