mejorar_consciencia_propia_relacional_dos_practicas        17 a 22 y 35 a 40
contar_cuatro_historias_propias_ver_hueco_intencion        41 a 58
practicar_triangulo_critica_tres_papeles                   59 a 72
pedir_critica_primero_crear_seguridad_psicologica          73 a 86
elegir_pregunta_recurrente_pedir_critica                   115 a 120 y 129 a 166
resolver_dudas_frecuentes_pedir_critica                    167 a 186
abrazar_incomodidad_silencio_contar_seis                   187 a 198
escuchar_entender_critica_dominar_defensa                  199 a 214
premiar_franqueza_hacer_escucha_tangible                   215 a 234
integrar_peticion_critica_rutina_existente                 111 a 112 y 235 a 246
dar_elogio_disciplina_igual_critica                        247 a 252 y 267 a 288
medir_critica_respuesta_oyente_brujula                     289 a 322
