echo "nodos en el grafo                        : $(wc -l < dataset/nodos.jsonl)"
echo "veredictos en bitacora                   : $(wc -l < bitacora/VEREDICTOS.jsonl)"
echo "candidatos en bandeja del lote 4         : $(ls cuarentena/scott_radical_candor/*.json | wc -l)"
echo "insertados del lote 4                    : $(ls cuarentena/_insertados/scott_radical_candor/*.json | wc -l)"
echo "candidatos en bandeja del lote 5         : $(ls cuarentena/marquet_turn_the_ship/*.json | wc -l)"
echo "ficheros en _insertados (todos los lotes): $(ls cuarentena/_insertados/*/*.json | wc -l)"
echo "lineas del reporte                       : $(wc -l < docs/loop/REPORTE.md)"
echo "rama                                     : $(git rev-parse --abbrev-ref HEAD)"
echo "commit de apertura                       : $(git rev-parse --short HEAD)"
