python forja.py insertar cuarentena/scott_radical_candor/despedir_persona_franqueza_radical.json \
  --sin-preguntas \
  --veredicto "despedir_persona_respeto_franqueza|SANO|PENDIENTE DE DOCTRINA: es el mismo trabajo escrito por DOS libros (zhuo_manager y scott_radical_candor) y no una madre con su hija. El vecino nombra en su paso 8 ayudar a la persona hacia su capitulo siguiente y yo lo despliego en mis pasos 5, 6 y 8 (imaginar el trabajo concreto antes de la reunion y ofrecer la presentacion), que seria la forma de D.29, PERO la linea que desplegaria es de OTRO autor: dos libros que convergen no son jerarquia, y esta casa no ha cableado ni una arista entre libros (0 de 81, medido hoy en .v26/aristas_entre_libros.txt). Registro lo mejor sostenido, que es SANO, y traigo la pregunta al reporte en vez de estrenar la figura yo" \
  --veredicto "elegir_recolocar_despedir_persona|SANO|PENDIENTE DE DOCTRINA por el mismo motivo que el anterior: otro libro (zhuo_manager). Y ademas el trabajo es distinto dentro del suyo: el vecino elige entre recolocar dentro o dejar ir, y yo empiezo cuando esa eleccion ya esta hecha (mi activacion dice cuando ya has decidido que tienes que despedir a alguien). La señal los junta por familia de id, que comparte la pieza despedir_persona" \
  --veredicto "acompaniar_mejores_equipo_socio|SANO|comparten un hecho y no un procedimiento: mis pasos 9 y 10 dicen que mantener a quien rinde mal castiga a quien rinde bien, y su paso 10 dice que no dediques mas tiempo a quien va mal que a quien va bien. Es la misma observacion del libro usada para dos trabajos opuestos: el suyo es acompaniar como socio a los mejores, el mio es preparar y tener la conversacion de despido. Ninguno de sus once pasos se ejecuta dentro de los mios" \
  --veredicto "empezar_cultura_franqueza_radical|SANO|comparten el nombre de la franqueza radical y no el trabajo: el vecino fija el ORDEN de arranque de la cultura (explicar, pedir, elogiar, criticar) y yo tengo una conversacion concreta de despido. El paso 4 mio que la señal enfrenta es lo que aquella jefa deberia haber hecho en el caso del banco, y su paso 1 es que la gente se pone nerviosa ante la practica: no hay linea comun" \
  --veredicto "equilibrar_elogio_critica_equipo|SANO|comparten el vocabulario de la guia y no el trabajo: el vecino reparte cuanto elogio y cuanta critica dar, y yo preparo un despido. Mi paso 1 que la señal enfrenta dice no te distancies de la persona, y su paso 7 dice que al criticar te concentres en decirlo sin mas: son dos consejos distintos sobre dos actos distintos" \
  --veredicto "elogiar_trabajo_especifico_contexto|SANO|no hay ni un paso comun: el vecino elogia con su porque dentro y averigua quien hizo que antes de elogiar en publico, y yo despido. La señal es similitud de texto 0.386, y lo que se parece es el REGISTRO del libro (los dos nodos cuentan casos de la autora con nombre propio), no el procedimiento. Es la banda justo por encima del umbral, no la banda alta de gemelos que EXTRACTOR.md 11 describe" \
  --veredicto "desplegar_marco_franqueza_radical|SANO|el vecino despliega el marco como objeto fisico (recortarlo, fotocopiarlo, pegarlo, no escribir nombres en las casillas) y yo no lo uso en ningun paso. Su paso 6, usar el marco como brujula para llevar cada conversacion concreta a un sitio mejor, no nombra NINGUNA conversacion en particular, y una linea que dice cada no nombra la mia: eso es exactamente lo que EXTRACTOR.md 9.1 llama nombrar sin procedimentar, y declarar la arista ahi la pondria yo y no el libro"
