python forja.py insertar cuarentena/scott_radical_candor/subir_vara_calidad_equipo.json \
  --sin-preguntas \
  --veredicto "acompaniar_mejores_equipo_socio|SANO|es la cabeza de las DOS partes de L117 (estrella de rock y superestrella) y yo no soy ninguna de las dos: yo trato a quien lleva tiempo haciendo un trabajo solo aceptable, que en el marco del libro no esta en ninguna de esas dos fases. EXTRACTOR.md 15.6 lo escribe para este caso exacto: una cabeza de seis vias y un vecino que no es ninguna de las seis son hermanos, y su veredicto es SANO. Mi paso 9 y su paso 11 se parecen porque los dos dicen lo que el mal desempenio le hace al resto, que es una observacion del libro repetida en varias secciones" \
  --veredicto "retirar_etiquetas_permanentes_equipo|SANO|comparten una conviccion y no un procedimiento: su paso 6 prohibe etiquetar por desempenio y mi paso 9 dice que ser etiquetado permanentemente como mediocre hace mas danio. Pero eso en mi nodo es el ARGUMENTO con el que el libro sostiene la politica, no un paso: mi procedimiento es dar un proyecto donde la persona pueda brillar y, si aun asi el trabajo sigue mediocre, animarla a buscar en otro sitio. Ninguno de sus diez pasos se ejecuta dentro de los mios" \
  --veredicto "despedir_persona_franqueza_radical|SANO|no soy su hijo aunque me lo parezca de lejos: mi paso 7 dice empieza a animar a esa persona a buscar trabajo en otro sitio, que NO es despedirla, y la activacion del vecino dice cuando ya has decidido que tienes que despedir a alguien. Escribir la arista aqui seria cerrar un bucle que el libro deja abierto, que es lo que EXTRACTOR.md 15.4 llama PUENTE, y un puente no se queda callado dentro de un nodo ni dentro de una arista" \
  --veredicto "descubrir_motivacion_sentido_persona|SANO|el vecino averigua de donde saca cada persona el sentido de su trabajo y yo subo la vara de calidad a quien lleva tiempo en aceptable. Mi paso 8 que la señal enfrenta dice lo que la politica de los dos anios costo en estres, y su paso 4 es del descubrimiento del sentido: no hay linea comun" \
  --veredicto "retar_superestrellas_equipo_constantemente|SANO|somos los dos extremos del mismo capitulo y ninguno despliega al otro: el vecino reparte oportunidades a quien ya hace un trabajo excelente y yo levanto a quien lleva dos anios en aceptable. Mi paso 10 dice que lo unico mas cruel que parecer duro es bajar la vara, y su paso 13 dice que cuando la gestion es la unica via a mas retribucion la calidad de la gestion se resiente: dos afirmaciones distintas" \
  --veredicto "cuidar_persona_completa_equipo|SANO|los dos pasos 1 que la señal enfrenta dicen cosas distintas: el suyo es el mandato de mantenerlo profesional como causa de no cuidar personalmente, y el mio es que no existe el jugador de segunda ni el ser humano mediocre. El vecino construye la relacion humana y yo subo una vara de calidad" \
  --veredicto "delimitar_franqueza_radical_cinco_noes|SANO|comparten la palabra empatia ruinosa y no el trabajo: mi paso 4 llama a mantener al mediocre la peor forma de empatia ruinosa, y el vecino delimita que NO es franqueza radical con sus cinco noes. Su paso 2 que la señal enfrenta dice que desafiar cuesta energia y que lo hagas solo por lo que importa, y mi paso 10 dice que tu trabajo es poner y sostener una vara" \
  --veredicto "pedir_critica_equipo_premiarla|SANO|el vecino pide critica para si mismo y premia la primera queja, y yo doy un proyecto donde alguien pueda brillar. Mi paso 1 es que no existe el ser humano mediocre y su paso 7 es no reacciones a la defensiva: ni el mismo acto ni el mismo objeto"
