#!/bin/sh
# CADENA 1 de la vuelta 39: el candidato 1 de 3, que es cabeza de DOS series, con las
# dos aristas que se cablean y las CINCO que van a cola, todo en el mismo acto.
. /c/Users/AlexDesk/Documents/forja-nodos/.v39/correr.sh

echo "cadena 1 arrancada (candidato 1 de 3)" >> .v39/informes/_cadena.txt

corre i01_pedir_critica_primero.txt pedir_critica_primero_crear_seguridad_psicologica \
 --veredicto "empezar_cultura_franqueza_radical|CONTINUA|madre=empezar_cultura_franqueza_radical|ESTE ES EL PAR MAS CARO DEL CAPITULO Y VIENE MARCADO COMO DISCUTIBLE DESDE LA VUELTA 37: la ACTA 36 punto 3.5 lo dejo sostenido en su lectura y con su dato sin existir, y la ACTA 37 punto 4 lo volvio a sostener leyendo los 17 pasos. Hoy el nodo entra y el veredicto se escribe. MI VEREDICTO ES CONTINUA Y NO REPITE, y la razon la escribe el propio libro: cap_13 L87 dice The first edition describes this order of operations, o sea que reconoce que las dos listas son LA MISMA, y aun asi escribe el capitulo entero porque la primera no bastaba. QUE ANIADE EL HIJO A LA MADRE, medido paso a paso: la madre tiene el orden EN PROSA y solo hasta su tercera etapa (explica la idea, pide que te critiquen, empieza por el elogio y no por la critica, entiende la frontera peligrosa); el hijo trae la lista NUMERADA POR EL PROPIO TEXTO de L77 a L85, y con ella los pasos CUATRO y CINCO que la madre no tiene en ninguna forma, mide la critica y ajusta y fomenta el elogio y la critica entre los demas. Y trae ademas todo el porque medido que la madre no tiene ni insinuado: la definicion de seguridad psicologica de Amy Edmondson en L105, la medicion de Google de L107 con sus cinco dinamicas clave, y el circulo virtuoso de L109. LA MADRE ES LA DE cap_05 PORQUE ES LA QUE NOMBRA Y SE ACABA, y el hijo es el que despliega, que es la vara de siempre." \
 --veredicto "fomentar_guia_reciproca_companieros|CONTINUA|madre=pedir_critica_primero_crear_seguridad_psicologica|ARISTA D.29, QUE ES LA 52 DE LA DEUDA DECLARADA EN LA VUELTA 23 Y QUE EL ENCARGO DE LA VUELTA 39 MANDA CABLEAR EN EL ACTO EN QUE ENTRE LA MADRE. Mi paso 5 es el quinto del orden de operaciones y dice Cinco, fomenta el elogio y la critica entre los demas, que es cap_13 L85 entera, encourage praise and criticism between others, y ahi se acaba: mi paso son ocho palabras. El hijo lo despliega en 13 pasos de cap_09 con lo que yo no tengo: la conversacion en persona que no se sustituye por una herramienta, la mecanica de los dos peluches de Dan Woods, la ballena que se nomina en cada reunion general, el peluche de la metedura de pata con su perdon automatico, los veinte dolares para romper el primer silencio, y el limite de donde esa practica NO encaja. ES D.29 Y NO D.37, y lo digo porque decide como se cita: el texto NUMERA los cinco pasos de L77 a L85 pero NO escribe la palabra cinco, asi que no dice CUANTAS partes tiene y la regla que aplica es la que pide razon escrita." \
 --veredicto "dar_elogio_disciplina_igual_critica|CONTINUA|madre=pedir_critica_primero_crear_seguridad_psicologica|ARISTA 49 DE LA DEUDA DE LA VUELTA 23, QUE VA A COLA PORQUE SU HIJO SIGUE EN LA BANDEJA, Y VA ESCRITA AHORA PARA QUE NO SE PIERDA: la linea 469 estuvo sin cablear una vuelta entera por no escribirla, y el encargo de esta vuelta pone estas cuatro por su nombre para que no pase dos veces. Mi paso 2 es el segundo del orden de operaciones y dice Dos, da elogio, que es cap_13 L79 entera, give praise, y ahi se acaba: mi paso son tres palabras. El hijo lo despliega en 20 pasos de cap_13, lineas 247 a 252 y 267 a 288, bajo el rotulo PRAISE: FOCUS ON THE GOOD STUFF. REALLY. de la linea 247, con toda la disciplina del elogio que yo no tengo. ES LA MISMA FIGURA QUE LA 50 Y LA 52, un paso que nombra la etapa por su rotulo y un hijo que la despliega, y por eso su veredicto es el mismo: una vara no puede dar dos respuestas a la misma figura. ES D.29 Y NO D.37, por la misma razon que las otras: el texto numera los cinco pasos sin escribir la palabra cinco. SE CABLEARA EN EL ACTO EN QUE SU HIJO ENTRE." \
 --veredicto "medir_critica_respuesta_oyente_brujula|CONTINUA|madre=pedir_critica_primero_crear_seguridad_psicologica|ARISTA 51 DE LA DEUDA DE LA VUELTA 23, QUE VA A COLA PORQUE SU HIJO SIGUE EN LA BANDEJA. Mi paso 4 es el cuarto del orden de operaciones y dice Cuatro, mide la critica y ajusta, que es cap_13 L83 entera, gauge the criticism and adjust, y ahi se acaba: mi paso son seis palabras. El hijo lo despliega en 33 pasos de cap_13, lineas 289 a 322, bajo el rotulo GAUGE CRITICISM de la linea 289, con la brujula de la respuesta del oyente que yo no tengo en ninguna forma. MISMA FIGURA Y MISMO VEREDICTO QUE LA 49, LA 50 Y LA 52, y ES D.29 Y NO D.37 por la misma razon. SE CABLEARA EN EL ACTO EN QUE SU HIJO ENTRE." \
 --veredicto "abrazar_incomodidad_silencio_contar_seis|CONTINUA|madre=pedir_critica_primero_crear_seguridad_psicologica|ARISTA D.37 QUE VA A COLA PORQUE SU HIJO SIGUE EN LA BANDEJA, Y LA CUENTA ESTA ESCRITA, que es la condicion literal de la regla: cap_13 L113 escribe each of the four tips for soliciting criticism offered in the book, o sea que dice CUANTAS. Mi paso 17 las nombra una a una, dar con una pregunta recurrente, abrazar la incomodidad, escuchar con intencion de entender, y hacer tangible la escucha premiando la franqueza, y ahi se acaba. Este es LA SEGUNDA de las cuatro y la despliega en 12 pasos de cap_13, lineas 187 a 198, bajo el rotulo EMBRACE THE DISCOMFORT de la linea 187, con el silencio que hay que aguantar y la cuenta hasta seis que yo no tengo. D.37 manda declararla en la misma vuelta en que entren las partes, y la parte no entra hoy: por eso queda escrita y en cola en vez de perderse. Y AVISO DE UNA TERCERA MADRE QUE NO ES MIA: la ACTA 36 punto 3.7 sostuvo que exigir_critica_jefe_reticente tambien es madre de este hijo por sus pasos 5 a 7; ese cable va encargado con su candidato y no con el mio." \
 --veredicto "escuchar_entender_critica_dominar_defensa|CONTINUA|madre=pedir_critica_primero_crear_seguridad_psicologica|ARISTA D.37 QUE VA A COLA PORQUE SU HIJO SIGUE EN LA BANDEJA, con la cuenta escrita en cap_13 L113, each of the four tips for soliciting criticism. Mi paso 17 nombra las cuatro y ahi se acaba. Este es LA TERCERA de las cuatro y la despliega en 13 pasos de cap_13, lineas 199 a 214, bajo el rotulo LISTEN WITH THE INTENT TO UNDERSTAND, NOT TO REPLY de la linea 199, con el dominio de la defensa que yo no tengo. SE CABLEARA EN EL ACTO EN QUE SU HIJO ENTRE." \
 --veredicto "premiar_franqueza_hacer_escucha_tangible|CONTINUA|madre=pedir_critica_primero_crear_seguridad_psicologica|ARISTA D.37 QUE VA A COLA PORQUE SU HIJO SIGUE EN LA BANDEJA, con la cuenta escrita en cap_13 L113. Este es LA CUARTA de las cuatro que mi paso 17 nombra, hacer tangible la escucha premiando la franqueza, y la despliega en 20 pasos de cap_13, lineas 215 a 234, bajo el rotulo MAKE LISTENING TANGIBLE: REWARD THE CANDOR de la linea 215, que yo no tengo. LO DIGO PORQUE EL ENCARGO NO LA NOMBRA: la TAREA 3.C dice que los otros DOS elementos siguen en bandeja y son TRES, porque este cuarto tambien esta en la bandeja de cap_13. Declararlo es lo que D.37 manda y dejarlo fuera seria dejar una parte de la serie sin declarar por una cuenta ajena. SE CABLEARA EN EL ACTO EN QUE SU HIJO ENTRE." \
 --veredicto "integrar_peticion_critica_rutina_existente|SANO|SON VECINOS DE LINEA Y NO DE OBJETO, y lo sostengo tras leer sus 13 pasos enteros en esta vuelta, no heredado. Mi propia ficha declara la frontera antes de que la senial dijera nada: el habito regular de cap_13 L111 NO viaja a mis pasos y su sede es este vecino, por P.19, porque es el mismo objeto que L239. LO QUE LA SENIAL CAZA ES UNA CITA LITERAL COMPARTIDA: mi P17 y su P06 transcriben la misma enumeracion de los cuatro elementos, pero son dos lineas distintas del libro haciendo dos trabajos distintos, L113 la ANUNCIA antes de desplegarla y L237 la RECAPITULA despues para entregar al habito, Now that you have practiced the four elements. QUE ENTREGA CADA UNO: yo entrego EL ORDEN DE OPERACIONES RECORRIDO DESDE SU PRIMER PASO, con la critica pedida y respondida bien; aquel entrega LA PETICION METIDA AL FINAL DE TUS REUNIONES A SOLAS ya programadas, anunciada al equipo con la pregunta que vas a hacer. Y SU ACTIVACION LO SEPARA SOLO: aquel arranca cuando YA HAS PRACTICADO LOS CUATRO ELEMENTOS por separado y quieres juntarlos, o sea AGUAS ABAJO de los cuatro que mi paso 17 nombra, no aguas abajo de mi. D.37, apartado lo que NO autoriza: un nodo del mismo dominio que no es ninguna de las cuatro no es hijo, es hermano, y su veredicto es SANO. El vecino sigue en la bandeja, asi que lo levanta la poblacion de D.38.5." \
 --censo "serie=los cuatro elementos de pedir critica;papel=cabeza;nota=la cuenta esta escrita en cap_13 L113, each of the four tips for soliciting criticism, y L237 los nombra uno a uno. Este nodo encabeza ADEMAS una segunda serie, el orden de operaciones de cinco pasos de L77 a L85, que NO es D.37 porque el texto numera sin escribir cuantas son, y por eso ni el id ni el titulo llevan cifra" $COMUN

arista ar_p03_pedir.txt desplegar_plan_orden_operaciones_franqueza_radical pedir_critica_primero_crear_seguridad_psicologica 3 \
"ARISTA D.29 ADJUDICADA POR LA ACTA 36 PUNTO 3.6, CABLEADA EN EL ACTO EN QUE SU HIJO ENTRA, que es lo que aquella adjudicacion dejo encargado con estas palabras: cada una se declara en el acto en que su hijo entre, citando P03. Mi paso 3 remite al epilogo nombrando cuatro cosas, y es cap_12 L13: So for more detailed advice on sharing your stories, soliciting criticism, giving praise, and gauging your criticism see the Afterword. La segunda de las cuatro, pedir critica, tiene destino UNICO dentro del epilogo: la seccion SOLICIT CRITICISM FIRST de cap_13 L73, que es este hijo. Mi paso 3 la nombra y manda al capitulo, y ahi se acaba. La primera de las cuatro, compartir tus historias, se cableo en la vuelta 38. Las otras dos, dar elogio y medir tu critica, NO se cablean aqui porque sus hijos siguen en la bandeja."

arista ar_50_criticar.txt pedir_critica_primero_crear_seguridad_psicologica criticar_trabajo_evitar_desanimo 3 \
"LA ARISTA 50 DE LA DEUDA DE LA VUELTA 23, ADJUDICADA POR MI PREDECESOR EN BC.5.b DE LA VUELTA 38 Y SOSTENIDA POR LA ACTA 37 PUNTO 3, CABLEADA HOY EN EL ACTO EN QUE SU MADRE ENTRA. Mi paso 3 es el tercero del orden de operaciones y dice Tres, da critica, que es cap_13 L81 entera, give criticism, y ahi se acaba: mi paso son cuatro palabras. El hijo despliega la etapa en 14 pasos de cap_05 con lo que yo no tengo: criticar el trabajo y no a la persona, el error de atribucion fundamental, averiguar por que el otro hace lo que hace antes de mandar nada, ser humilde y util, darla en persona e inmediatamente, elogiar en publico y criticar en privado, y las dos carpetas del responsable veterano. LA RAZON QUE DECIDE ES LA DE LA ACTA 36 PUNTO 3.6: una vara no puede dar dos respuestas a la misma figura. Los cinco pasos del orden son la misma figura cinco veces, un paso que nombra la etapa por su rotulo y un hijo que la despliega. Y EL REPARO SIGUE ESCRITO Y NO LO BORRO: este hijo YA TIENE MADRE, empezar_cultura_franqueza_radical, que es la version en prosa del MISMO orden en cap_05, asi que le doy una segunda madre que dice lo mismo. Vale igual porque la ACTA 36 punto 3.7 sostuvo una TERCERA madre para abrazar_incomodidad_silencio_contar_seis, y porque L87 dice expresamente que las dos listas son la misma: la duplicidad esta en el libro y no la invento yo."

echo "cadena 1 terminada" >> .v39/informes/_cadena.txt
