#!/bin/sh
# CADENA 3 de la vuelta 39: el candidato 3 de 3, que cierra el tramo.
. /c/Users/AlexDesk/Documents/forja-nodos/.v39/correr.sh

echo "cadena 3 arrancada (candidato 3 de 3)" >> .v39/informes/_cadena.txt

corre i03_resolver_dudas.txt resolver_dudas_frecuentes_pedir_critica \
 --veredicto "resolver_dudas_frecuentes_reuniones_salto_nivel|SANO|MISMA FIGURA Y CERO OBJETO COMPARTIDO, y la figura es lo unico que la senial puede ver. Los dos son un bloque de preguntas frecuentes que el libro contesta una a una, y esta casa ya trato el otro como nodo, asi que la forma esta juzgada. Pero aquel contesta las cuatro dudas de UNA REUNION DE SALTO DE NIVEL, el equipo que ya no cree en su jefe, los que no hablan, los que no callan y el equilibrio, y entrega la reunion sacada adelante. Este contesta las dudas de PEDIR CRITICA, que son las cuatro de cap_13 L169, L173, L177 y L181, la pregunta que se queda rancia, la respuesta sobre algo que no puedes arreglar, el jefe nuevo con gente mayor que el, y el miedo a recibir critica, y entrega cada duda resuelta con la accion que su respuesta encarga. Ni una de las dudas de uno aparece en el otro." \
 --veredicto "despedir_persona_franqueza_radical|SANO|LO QUE LOS CRUZA ES UNA FORMULA Y NO UN OBJETO. Aquel prepara y tiene la conversacion de UN DESPIDO ya decidido, sin distanciarte de la persona, con el problema reformulado en el puesto y con un trabajo siguiente imaginado antes de la reunion. Este resuelve las dudas frecuentes de PEDIR CRITICA, que es la etapa en que todavia no has dado ninguna. Ni la misma activacion, ni el mismo entregable, ni un acto compartido, y ninguno nombra al otro en ninguna linea." \
 --veredicto "elegir_pregunta_recurrente_pedir_critica|SANO|EL VECINO ES LA PREGUNTA Y YO SOY LAS DUDAS QUE APARECEN AL USARLA, y eso los separa aunque compartan la palabra pregunta en cada linea. Aquel entrega TRES O CUATRO PREGUNTAS RECURRENTES ESCRITAS Y PROBADAS, con los cuatro atributos de L129 a L137 y las nueve preguntas literales de L141 a L157. Yo entrego LAS CUATRO DUDAS DEL BLOQUE FAQ RESUELTAS, cada una con la accion que su respuesta encarga: la pregunta que se queda rancia, la respuesta sobre algo que no puedes arreglar, el jefe nuevo con gente mayor, y el miedo a recibir critica. Mi primera duda NOMBRA su objeto (si tengo que usar la misma pregunta cada semana) pero no despliega ninguna pregunta ni ningun atributo, y el no trae ni una de mis cuatro dudas. NO SOY UNA DE LAS CUATRO PARTES DE LA SERIE D.37 y el tampoco es mi cabeza: los dos salen del mismo tramo del libro y ahi se acaba." \
 --veredicto "pedir_critica_primero_crear_seguridad_psicologica|SANO|NO SOY NINGUNA DE LAS CUATRO PARTES QUE SU L113 CUENTA. La cabeza de la serie es el, y las cuatro estan nombradas una a una en su paso 17 y en L237: dar con una pregunta recurrente, abrazar la incomodidad, escuchar con intencion de entender, y hacer tangible la escucha premiando la franqueza. El bloque FAQ de L167 a L185 no es ninguna de las cuatro: es un bloque de dudas que el libro intercala DENTRO del tramo de la primera, y su entregable son las cuatro dudas resueltas y no un elemento de la serie. D.37, apartado lo que NO autoriza: un vecino del mismo dominio que no es ninguna de las cuatro no es hijo, es hermano, y su veredicto es SANO. Lo que si comparto con el es la razon de fondo, y la digo para que no parezca que la escondo: sus L183 y mi P11 a P13 hablan los dos del miedo a la critica, pero el lo usa para JUSTIFICAR el orden de operaciones y yo lo resuelvo como duda de quien ya lo intenta." \
 --censo "serie=no" $COMUN

echo "cadena 3 terminada" >> .v39/informes/_cadena.txt
