#!/bin/sh
# CADENA 2 de la vuelta 39: el candidato 2 de 3, que es LA PRIMERA de las cuatro partes
# de la serie D.37 cuya cabeza entro en la cadena 1.
. /c/Users/AlexDesk/Documents/forja-nodos/.v39/correr.sh

echo "cadena 2 arrancada (candidato 2 de 3)" >> .v39/informes/_cadena.txt

corre i02_elegir_pregunta.txt elegir_pregunta_recurrente_pedir_critica \
 --veredicto "pedir_critica_primero_crear_seguridad_psicologica|CONTINUA|madre=pedir_critica_primero_crear_seguridad_psicologica|ARISTA D.37 Y LA CUENTA ESTA ESCRITA, que es la condicion literal de la regla: cap_13 L113 escribe each of the four tips for soliciting criticism offered in the book, o sea que dice CUANTAS, y L237 las nombra una a una. El paso 17 de la madre las nombra tambien, dar con una pregunta recurrente, abrazar la incomodidad, escuchar con intencion de entender, y hacer tangible la escucha premiando la franqueza, y ahi se acaba. Este es LA PRIMERA de las cuatro y la despliega en 24 pasos de L119 a L165 que la madre no tiene: los cuatro atributos con su rotulo propio, sincera, que no se conteste con un si o un no, concreta contra abierta, y la frecuencia; la correccion que el propio texto hace a la pregunta que recomendaba la primera edicion; nueve preguntas literales de L141 a L157; y el ejercicio de probarlas con un companiero de confianza de L161. La madre entro hace un momento en esta misma vuelta, asi que la arista se cablea EN EL ACTO, que es lo que D.37 manda. Las otras tres partes de la serie quedaron declaradas y EN COLA al insertar la madre, y sus cables esperan a que entren." \
 --veredicto "abrazar_incomodidad_arrancar_critica_equipo|SANO|COMPARTEN EL ACTO DE PEDIR CRITICA Y NI UN OBJETO. Aquel sale de cap_09, tiene 20 pasos y entrega CRITICA DICHA EN VOZ ALTA POR TU EQUIPO, recibida sin defenderte y premiada de forma visible, con la cuenta semanal de cuanta recibes: su problema es un equipo que no habla. Este entrega TRES O CUATRO PREGUNTAS RECURRENTES TUYAS ESCRITAS Y PROBADAS con un companiero de confianza, evaluadas por si sacaron critica util y por si sonaron naturales: su problema es que no sabes que pregunta hacer. Ninguno de los dos nombra el procedimiento del otro en una linea, y los cuatro atributos de una buena pregunta no estan en aquel." \
 --veredicto "exigir_critica_jefe_reticente|SANO|LA DIRECCION DE LA PETICION ES LA CONTRARIA, y eso los separa solo. Aquel le exige la critica A TU JEFE, que es quien duda en darte una opinion franca, y entrega una valoracion sacada de tu jefe. Este elige las preguntas con las que TU pides critica A TU EQUIPO, y entrega tus preguntas escritas y probadas. Uno mira hacia arriba y otro hacia abajo, y los ejemplares de pregunta de cada uno son distintos: aquel trae las tres frases del texto para un jefe reticente, este los cuatro atributos y las nueve preguntas de cap_13 L141 a L157." \
 --veredicto "pedir_critica_equipo_premiarla|SANO|SON LAS DOS MITADES DISTINTAS DEL MISMO MOMENTO Y NINGUNA DESPLIEGA A LA OTRA. Aquel sale de cap_05 y entrega LA CRITICA PEDIDA ACTIVAMENTE Y NO SOLO CONSENTIDA, recibida sin defenderte, premiada cuando llega por pequenia que sea y con el equipo enterado de que la queja se atendio: su objeto es la CONDUCTA de quien pide. Este entrega LAS PREGUNTAS con las que se pide, escritas, probadas y evaluadas por dos varas: su objeto es la HERRAMIENTA. Aquel no trae ni un atributo de pregunta y este no trae ni una regla de como recibir la respuesta. Comparten el acto de pedir critica y ahi se acaba el parecido." \
 --veredicto "integrar_peticion_critica_rutina_existente|SANO|HERMANOS DE SERIE Y NO MADRE E HIJO. Los dos cuelgan de la misma cabeza, pedir_critica_primero_crear_seguridad_psicologica, pero por sitios distintos: yo soy LA PRIMERA de los cuatro elementos que su L113 anuncia, y aquel es lo que L237 manda hacer DESPUES de practicar los cuatro, meterlos en la rutina que ya tienes. Su P06 recapitula la enumeracion entera y por eso se me parece en la letra, pero lo que entrega es LA PETICION METIDA AL FINAL DE TUS REUNIONES A SOLAS, y lo que entrego yo son TRES O CUATRO PREGUNTAS ESCRITAS Y PROBADAS. Aquel no despliega ninguna pregunta y yo no pongo ninguna rutina. D.37, apartado lo que NO autoriza: dos partes de la misma cabeza son hermanas, y su veredicto es SANO." \
 --censo "serie=los cuatro elementos de pedir critica;papel=paso;cabeza=pedir_critica_primero_crear_seguridad_psicologica" $COMUN

echo "cadena 2 terminada" >> .v39/informes/_cadena.txt
