echo "rama                          : $(git rev-parse --abbrev-ref HEAD)"
echo "commit de apertura            : $(git rev-parse --short HEAD)"
echo "fecha del commit de apertura  : $(git log -1 --format=%ad --date=iso)"
echo "nodos en el grafo             : $(wc -l < dataset/nodos.jsonl)"
echo "candidatos en cuarentena lote4: $(ls cuarentena/scott_radical_candor/*.json | wc -l)"
echo "insertados del lote 4         : $(ls cuarentena/_insertados/scott_radical_candor/*.json | wc -l)"
echo "veredictos en bitacora        : $(wc -l < bitacora/VEREDICTOS.jsonl)"
echo "insertados _insertados (todos): $(ls cuarentena/_insertados/*/*.json | wc -l)"
echo "lineas de REPORTE.md          : $(wc -l < docs/loop/REPORTE.md)"
echo "INFORME_DE_LOTE.txt           : $(test -f docs/loop/INFORME_DE_LOTE.txt && echo PRESENTE || echo AUSENTE)"
echo "SELLOS_INFORME.jsonl          : $(test -f docs/loop/SELLOS_INFORME.jsonl && echo PRESENTE || echo AUSENTE)"
