echo "rama                          : $(git rev-parse --abbrev-ref HEAD)"
echo "commit al cierre              : $(git rev-parse --short HEAD)"
echo "nodos en el grafo             : $(wc -l < dataset/nodos.jsonl)"
echo "candidatos en cuarentena lote4: $(ls cuarentena/scott_radical_candor/*.json | wc -l)"
echo "insertados del lote 4         : $(ls cuarentena/_insertados/scott_radical_candor/*.json | wc -l)"
echo "candidatos en cuarentena lote5: $(ls cuarentena/marquet_turn_the_ship/*.json 2>/dev/null | wc -l)"
echo "veredictos en bitacora        : $(wc -l < bitacora/VEREDICTOS.jsonl)"
echo "insertados _insertados (todos): $(ls cuarentena/_insertados/*/*.json | wc -l)"
echo "lineas de REPORTE.md          : $(wc -l < docs/loop/REPORTE.md)"
