#!/bin/sh
# CADENA 1 de la vuelta 41: el candidato 1 de 3, la SEGUNDA de las cuatro partes de la
# serie de cap_13. SEIS veredictos: los TRES que levanta la senial (los que faltaron en
# la vuelta 40 y costaron la vuelta entera) y las TRES madres declaradas por lectura.
. /c/Users/AlexDesk/Documents/forja-nodos/.v41/correr.sh

cuadra .v41/informes/i01_abrazar_incomodidad.txt .v41/cadena_1.sh >> .v41/informes/_cadena.txt 2>&1 || {
  echo "CADENA 1 NO LANZADA: la guarda cuadra dijo que no" >> .v41/informes/_cadena.txt
  exit 1
}

date '+%H:%M:%S cadena 1 arrancada (candidato 1 de 3)' >> .v41/informes/_cadena.txt

corre n01_abrazar_incomodidad.txt abrazar_incomodidad_silencio_contar_seis \
 --veredicto "escuchar_entender_critica_dominar_defensa|SANO|LA SENIAL MAS ALTA DE MI COLA Y LA LEO LA PRIMERA, COMO MANDA EXTRACTOR.md 11: similitud_texto 0.449, por encima de 0.4, que es la banda donde el catalogo de 3.169 nodos no tiene ni un ajeno. LA LEO Y AUN ASI DIGO SANO, con el motivo medido y no supuesto: los dos somos PARTES HERMANAS de la misma cabeza, no madre e hijo ni gemelos. La cabeza es pedir_critica_primero_crear_seguridad_psicologica y su paso 17 nos nombra a los dos por separado dentro de la misma lista de cuatro, yo como abrazar la incomodidad y el como escuchar con intencion de entender. EXTRACTOR.md 15.6 escribe literalmente que un vecino que no es la parte que te toca es hermano y su veredicto es SANO. LO QUE LA SENIAL VE Y POR QUE NO DECIDE: los dos capitulos comparten el vocabulario entero de pedir critica, incomodidad, companiero y practicalo asi, y los dos traen un ejercicio con otra persona. LO QUE NOS SEPARA ES EL MOMENTO Y EL OBJETO. Yo trabajo el SILENCIO que viene ANTES de que el otro hable, mi condicion de activacion es que has pedido critica y se hace el silencio, y entrego el silencio aguantado hasta el final contando hasta seis. El trabaja TU PROPIA DEFENSA DESPUES de que el otro ya hablo, parte de la respuesta de pelea o huida ante la critica recibida, y entrega la critica escuchada entera sin respuesta defensiva con tu recurso de proceso identificado. Y los ejercicios tampoco son el mismo: el mio es una pregunta a un companiero amistoso y contar hasta seis midiendo cuantos segundos aguanta; el suyo es tres minutos de habla por cada uno, con papeles que se intercambian y sin interrumpir. Procedimiento en los dos lados y ninguno sirve para lo del otro." \
 --veredicto "premiar_franqueza_hacer_escucha_tangible|SANO|OTRO HERMANO DE LA MISMA CABEZA, Y LA MISMA RAZON CON OTRO NUMERO: similitud_texto 0.353, dentro de la banda que EXTRACTOR.md 11 llama ruido de jerarquia, y el paso 17 de pedir_critica_primero_crear_seguridad_psicologica nos nombra a los dos en su lista de cuatro, yo el segundo y el el cuarto. LO QUE NOS SEPARA, leido en los pasos: yo aguanto el silencio mientras el otro todavia no ha dicho nada, y mi entregable es ese silencio aguantado. El actua DESPUES de que la critica ya esta dicha y recibida: arregla el problema deprisa o explica por que no puede, y despues lo cuenta en publico en una reunion de equipo con lo que aprendio y lo que va a hacer. Su entregable lleva la lista de las tres o cuatro criticas recibidas y el relato publico; el mio no tiene ni lista ni publico. La senial mira el paso 7 mio contra el paso 8 suyo y ve dos veces la palabra practicalo asi, que es el rotulo del ejercicio en todo este capitulo: es forma compartida, no objeto compartido." \
 --veredicto "contar_historias_propias_explicar_franqueza_radical|SANO|ESTE NO ES NI HERMANO: ES OTRO CAPITULO Y OTRO TRABAJO, y lo digo con la senial delante, similitud_texto 0.376 y familia_id 0.100. Lo que la levanta es el paso 1 mio contra el paso 3 suyo, y lo que comparten esas dos lineas es el vocabulario de la franqueza radical y nada mas. El explica la franqueza radical A TU EQUIPO con tus propias palabras y con tus historias personales en vez de con teoria de gestion, y entrega esa explicacion dada, con la version tuya de la historia del um y de la historia de Bob. Yo no explico nada a nadie: aguanto un silencio delante de una sola persona que acaba de recibir mi pregunta. El habla en una reunion con su equipo; yo callo. No hay solape de objeto, ni de entregable, ni de condicion de activacion, y ninguno de los dos nombra al otro en una linea." \
 --veredicto "pedir_critica_primero_crear_seguridad_psicologica|CONTINUA|madre=pedir_critica_primero_crear_seguridad_psicologica|LA ARISTA D.37 QUE LA LINEA 489 DEJO EN COLA PORQUE YO SEGUIA EN LA BANDEJA, Y QUE SE CABLEA HOY EN EL ACTO EN QUE ENTRO. LA CUENTA ESTA ESCRITA, que es la condicion literal de D.37 y la separa de las otras dos madres: cap_13 L113 escribe each of the four tips for soliciting criticism offered in the book, o sea dice CUANTAS, y L237 las nombra una a una, coming up with a go-to question, embracing the discomfort, listening with the intent to understand, and making listening tangible by rewarding the candor. El paso 17 de la madre las nombra las cuatro y ahi se acaba. YO SOY LA SEGUNDA, embracing the discomfort, y la despliego en 12 pasos de cap_13 L187 a L198 bajo el rotulo EMBRACE THE DISCOMFORT de la linea 187, con lo que la madre no tiene en ninguna forma: no dejar salir del apuro, dar tiempo y espacio para formular la respuesta, aguantar el silencio aunque sea incomodo para los dos, el ejercicio de hacerle la pregunta a un companiero amistoso y contar hasta seis, la medida de cuantos segundos aguanta antes de saltar con el dato de que la mayoria no llega a seis, y el compromiso de volver a preguntar. CON ESTA ENTRADA LA SERIE PASA DE UNA PARTE A DOS DE CUATRO. Y DIGO POR QUE ESTE VEREDICTO NO CITA UN RANCIO: la linea 489 esta rancia porque el texto de la madre cambio de huella bdf8b8932603d104 a d228fe61d4d02678, asi que NO la cito como vigente; la releo hoy y emito este veredicto nuevo con los 17 pasos de la madre de hoy delante, que es la primera salida de las dos que D.15 da." \
 --veredicto "abrazar_incomodidad_arrancar_critica_equipo|CONTINUA|madre=abrazar_incomodidad_arrancar_critica_equipo|LA ARISTA 55 DE LA DEUDA DE LA ACTA 24, ESCRITA HACE DIECISEIS VUELTAS Y SIN CABLEAR, Y LA PAGO HOY PORQUE HOY ES CUANDO SU HIJO ENTRA. ES D.29 Y NO D.37, y lo medi yo en esta vuelta y no lo heredo: mi grep de six sobre fuentes/scott_radical_candor/cap_09.md da 3 coincidencias y las tres son count to six en L41 y L299 y slide six en L159, ninguna cuenta consejos. La cuenta de seis vive solo en el titulo del nodo, que es campo de esta casa y no del libro, y llevar D.37 a una cabeza que no escribe la cuenta seria ensanchar la regla, cosa que ninguna vuelta hace. QUE NOMBRA LA MADRE Y QUE DESPLIEGO YO: su paso 8 abre con la frase Abraza la incomodidad, que es literalmente mi titulo, y lo que aniade despues es OTRA COSA, prepararse para la respuesta de que todo va bien y comprometerse a seguir en la conversacion; su paso 9 toca la cuenta hasta seis de pasada con la meta de no abusar sino insistir; y su paso 10 dice que si no funciona vuelvas a preguntar. Son tres lineas dentro de un procedimiento de 20 pasos cuyo objeto es otro: arrancarle la critica a un equipo entero. Yo pongo el procedimiento del silencio entero en 12 pasos y traigo lo que sus 20 no tienen: dar tiempo y espacio para formular la respuesta, el ejercicio con un companiero amistoso, la cuenta de cuantos segundos aguanta antes de saltar y el dato de que la mayoria no llega a seis, y decirle que le das mas tiempo pero que vas a volver. LA MADRE TIENE LA LINEA Y EL HIJO TIENE EL PROCEDIMIENTO, que es la vara de siempre, con la direccion puesta como manda AUDITOR_FORJA.md 6.1 linea 575." \
 --veredicto "exigir_critica_jefe_reticente|CONTINUA|madre=exigir_critica_jefe_reticente|LA TERCERA MADRE, SOSTENIDA POR LA ACTA 37 EN SU SECCION 3.7 CON ESTAS PALABRAS: la madre nombra el acto en tres lineas y ahi se acaba, el hijo lo despliega en 12 pasos, es la figura canonica de D.29, sostenido y va encargada con su candidato. HOY ES SU CANDIDATO Y POR ESO VA. Lo releo yo con sus 9 pasos impresos del grafo en esta vuelta: sus pasos 5, 6 y 7 son TRES IMPERATIVOS DESNUDOS, sin contenido propio ninguno, y dicen exactamente Y entonces para, Cuenta hasta seis en tu cabeza, y Abraza la incomodidad. Los tres juntos son quince palabras y son mi titulo entero. Yo los despliego en 12 pasos con todo lo que ahi no hay: por que el silencio es incomodo para los dos, que tu trabajo es soportarlo e incluso abrazarlo, la disciplina enorme que el texto dice que hace falta, el ejercicio con un companiero amistoso, la medida de los segundos que aguanta, que hacer cuando aun asi se queda callado, y el compromiso de volver a preguntar. ES D.29 Y NO D.37: cap_09 no escribe en ningun sitio cuantas partes tiene esta secuencia, medido por el mismo grep de arriba, asi que la arista la sostiene mi lectura y por eso va con su razon. Y DIGO LO QUE CUESTA ADMITIR, igual que lo dijo la vuelta 38 en su discutible 7: con esta son TRES madres para un mismo hijo, que es mucho. Las tres se sostienen porque las tres NOMBRAN Y NINGUNA DESPLIEGA, y porque el libro reparte este material en dos capitulos, cap_09 comprimido dentro de arrancar la critica de un equipo y dentro de exigirsela a un jefe reticente, y cap_13 abierto entero." \
 --censo "serie=los cuatro elementos de pedir critica;papel=parte;cabeza=pedir_critica_primero_crear_seguridad_psicologica;nota=la cuenta esta escrita en cap_13 L113, each of the four tips for soliciting criticism offered in the book, y L237 los nombra uno a uno. Esta es la SEGUNDA de las cuatro, embracing the discomfort. Con ella la serie pasa de 1 a 2 de 4 partes en el grafo" $COMUN

anota an_484.txt 484 "VIGENCIA DECLARADA del 18 sep 2026, vuelta 41, TAREA 3 del encargo: esta lectura SIGUE VALIENDO aunque su huella haya cambiado, y la relectura que lo comprueba se hizo ANTES de insertar al vecino y no despues. La huella contra la que se emitio es eec451c2e48944c6 y hoy es 5aebf76b97831357, y el cambio lo produjo la correccion declarada de la vuelta 39 sobre practicar_triangulo_critica_tres_papeles. QUE CAMBIO, medido campo a campo por la vuelta 40 y firmado por el auditor en la ACTA 39: titulo identico, los 15 pasos identicos uno a uno, entregable, condiciones de activacion, dominio, fuentes y aristas identicos, y SOLO el resumen_teorico de 1951 a 2973 caracteres con prefijo comun de 1951, o sea anexion pura de prosa sobre una cifra publicada. LO QUE SOSTIENE ESTE SANO NO SE MOVIO NI UN CARACTER: la razon descansa sobre el objeto y el entregable, dos personas contra tres y recibir contra dar, y los dos campos que dicen eso son identicos al digito. Y el par acaba de emitirse ademas desde el otro lado en esta misma vuelta, al entrar abrazar_incomodidad_silencio_contar_seis." \
 "D.15, y las DOS salidas a la vez: el par se releyo con el texto de hoy Y se declara por que sigue valiendo, con la medicion de que cambio al lado. Lo que no vale es insertar encima de un veredicto rancio sin decir nada, y la vuelta 40 dejo esta anotacion preparada y no llego a correrla porque su cadena murio antes."

date '+%H:%M:%S cadena 1 terminada' >> .v41/informes/_cadena.txt
