#!/bin/sh
# CADENA 3 de la vuelta 40: el candidato 3 de 4, la CUARTA y ultima parte de la serie
# D.37. CON ESTA ENTRADA LA SERIE DE LOS CUATRO ELEMENTOS QUEDA COMPLETA, 4 de 4.
. /c/Users/AlexDesk/Documents/forja-nodos/.v40/correr.sh

echo "cadena 3 arrancada (candidato 3 de 4, CIERRA LA SERIE D.37)" >> .v40/informes/_cadena.txt

corre i03_premiar_franqueza.txt premiar_franqueza_hacer_escucha_tangible \
 --veredicto "pedir_critica_primero_crear_seguridad_psicologica|CONTINUA|madre=pedir_critica_primero_crear_seguridad_psicologica|ARISTA D.37 QUE LA LINEA 495 DEJO EN COLA PORQUE YO SEGUIA EN LA BANDEJA, Y QUE SE CABLEA HOY EN EL ACTO EN QUE ENTRO. CON ESTA ARISTA LA SERIE QUEDA COMPLETA: la cuenta esta escrita en cap_13 L113, each of the four tips for soliciting criticism offered in the book, L237 las nombra una a una, y las CUATRO partes quedan hoy en el grafo con sus CUATRO aristas cableadas desde la cabeza. El paso 17 de la madre nombra las cuatro y ahi se acaba. YO SOY LA CUARTA, hacer tangible la escucha premiando la franqueza, y la despliego en 20 pasos de cap_13, lineas 215 a 234, bajo el rotulo MAKE LISTENING TANGIBLE: REWARD THE CANDOR de la linea 215, con lo que la madre no tiene en ninguna forma: el riesgo que asume quien te critica y el encargo de premiarlo, arreglar el problema deprisa o explicar por que no puedes, el sesgo de negatividad con la frase de Rick Hanson, el ejemplar de Sara Blakely y su cancion, la lista de las tres o cuatro criticas recientes, la pesca cuando la lista esta vacia, lo que se cuenta en la reunion de equipo, las dos cosas buenas que pasan al ensenar tu trabajo, y el protocolo entero de la critica con la que no estas de acuerdo." \
 --veredicto "abrazar_incomodidad_arrancar_critica_equipo|CONTINUA|madre=abrazar_incomodidad_arrancar_critica_equipo|LA ARISTA 57 DE LA DEUDA DECLARADA EN LA VUELTA 24, CABLEADA HOY PORQUE HOY ES CUANDO SU HIJO ENTRA. ES D.29 Y NO D.37 por lo mismo que la 55 y la 56: cap_09 no escribe la cuenta en ningun sitio. QUE NOMBRA LA MADRE Y QUE DESPLIEGO YO: su paso 14 abre con la frase Premia la critica para conseguir mas, y lo que aniade es una regla corta, si estas de acuerdo haz el cambio cuanto antes y si va a llevar tiempo haz algo visible, mas la ilustracion de la goma elastica en la muneca. Yo traigo en 20 pasos lo que sus veinte pasos no tienen: el sesgo de negatividad y por que la unica vez que respondes a la defensiva es la que recuerdan, la frase de Rick Hanson sobre el velcro y el teflon, el ejemplar de Sara Blakely poniendo su cancion delante de toda la empresa, LA LISTA de las tres o cuatro criticas recibidas recientemente y que hacer si sale vacia, que se comparte exactamente en una reunion de equipo o de pie, las dos cosas buenas que pasan cuando ensenias tu trabajo, y EL PROTOCOLO ENTERO de premiar la critica con la que no estas de acuerdo, buscar la parte con la que si, compartirla, decir despues lo que no, y pedir conversacion mas larga. LA MADRE TIENE LA LINEA Y EL HIJO TIENE EL PROCEDIMIENTO." \
 --veredicto "pedir_critica_equipo_premiarla|SANO|ES EL PAR MAS CARO DE FALLAR DE TODO EL CAPITULO Y POR ESO LO LEI ENTERO ANTES DE QUE NINGUNA SENIAL LO LEVANTARA, sus 11 pasos. AQUEL ENTREGA la critica pedida y premiada DENTRO DE LA CONVERSACION, con su problema declarado, un equipo que no habla: las cuatro razones para pedirla primero, no criticar la critica de quien fue valiente, el caso de Tokio contando hasta diez sin que nadie hablara, el cuadrado rojo de Toyota, la primera queja sobre el te de la oficina premiada en publico. YO ENTREGO EL PROBLEMA ARREGLADO O EXPLICADO Y LA CRITICA CONTADA EN PUBLICO DESPUES, con la lista de las tres o cuatro criticas recientes y lo que hiciste con cada una: mi objeto no es arrancar la primera critica sino hacer VISIBLE lo que pasa con la que ya te dieron. LO QUE NO ESTA EN NINGUNO DE SUS ONCE PASOS: el sesgo de negatividad, la lista escrita, la pesca cuando la lista sale vacia, lo que se comparte en la reunion de equipo, las dos cosas buenas de ensenar tu trabajo y el protocolo de la critica con la que no estas de acuerdo. Y SU P05 NOMBRA MI TITULO EN UNA LINEA, y aun asi digo SANO y no CONTINUA: ese paso suyo esta dentro de un condicional sobre la critica INAPROPIADA, no es una etapa de su secuencia, y la madre de cap_09 que SI nombra mi etapa como etapa es abrazar_incomodidad_arrancar_critica_equipo en su paso 14, que es la arista que cablo arriba. Dos madres de cap_09 para el mismo hijo seria pagar dos veces la misma deuda. VA MARCADO COMO DISCUTIBLE EN MI REPORTE." \
 --censo "serie=los cuatro elementos de pedir critica;papel=parte;cabeza=pedir_critica_primero_crear_seguridad_psicologica;nota=la cuenta esta escrita en cap_13 L113 y L237 los nombra uno a uno. Esta es la CUARTA y ultima, making listening tangible by rewarding the candor. CON ELLA LA SERIE QUEDA COMPLETA: 4 de 4 partes en el grafo con sus 4 aristas cableadas desde la cabeza" $COMUN

echo "cadena 3 terminada" >> .v40/informes/_cadena.txt
