#!/bin/sh
# CADENA 1 de la vuelta 40: el candidato 1 de 4, la SEGUNDA de las cuatro partes de la
# serie D.37. Trae TRES madres, y las tres van cableadas en el mismo acto.
. /c/Users/AlexDesk/Documents/forja-nodos/.v40/correr.sh

echo "cadena 1 arrancada (candidato 1 de 4)" >> .v40/informes/_cadena.txt

corre i01_abrazar_incomodidad.txt abrazar_incomodidad_silencio_contar_seis \
 --veredicto "pedir_critica_primero_crear_seguridad_psicologica|CONTINUA|madre=pedir_critica_primero_crear_seguridad_psicologica|ARISTA D.37 QUE LA LINEA 489 DEJO EN COLA PORQUE YO SEGUIA EN LA BANDEJA, Y QUE SE CABLEA HOY EN EL ACTO EN QUE ENTRO. La cuenta esta escrita, que es la condicion literal de la regla: cap_13 L113 escribe each of the four tips for soliciting criticism offered in the book, o sea que dice CUANTAS, y L237 las nombra una a una. El paso 17 de la madre las nombra las cuatro y ahi se acaba: dar con una pregunta recurrente, abrazar la incomodidad, escuchar con intencion de entender, y hacer tangible la escucha premiando la franqueza. YO SOY LA SEGUNDA de esas cuatro y la despliego en 12 pasos de cap_13, lineas 187 a 198, bajo el rotulo EMBRACE THE DISCOMFORT de la linea 187, con lo que la madre no tiene en ninguna forma: no dejar salir del apuro, dar tiempo y espacio para formular la respuesta, aguantar el silencio, el ejercicio de hacerle la pregunta a un companiero amistoso y contar hasta seis, la cuenta de cuantos segundos aguanta antes de saltar, y el compromiso de volver a preguntar. CON ESTA ENTRADA LA SERIE PASA DE UNA PARTE A DOS DE CUATRO." \
 --veredicto "abrazar_incomodidad_arrancar_critica_equipo|CONTINUA|madre=abrazar_incomodidad_arrancar_critica_equipo|LA ARISTA 55 DE LA DEUDA DECLARADA EN LA VUELTA 24, QUE LLEVA DIECISEIS VUELTAS ESCRITA EN EL REPORTE Y NO CABLEADA, Y QUE PAGO HOY PORQUE HOY ES CUANDO SU HIJO ENTRA. ES D.29 Y NO D.37, y la razon la midio la propia vuelta 24: la cuenta de cuatro vive en cap_13 L113 y L237, que es la unidad de la OTRA cabeza, y cap_09 no escribe la cuenta en ningun sitio; importarla a una cabeza que no la escribe seria estirar D.37, y ninguna vuelta la estrecha ni la ensancha. QUE NOMBRA LA MADRE Y QUE DESPLIEGO YO: su paso 8 abre con la frase Abraza la incomodidad, que es literalmente mi titulo, y lo que aniade despues es OTRA COSA, prepararse para la respuesta de que todo va bien; su paso 9 toca la cuenta hasta seis de pasada, con la meta de no abusar sino insistir; y su paso 10 dice que si no funciona vuelvas a preguntar. Yo pongo el procedimiento entero en 12 pasos, y traigo lo que sus 20 pasos no tienen: dar tiempo y espacio para formular la respuesta, el ejercicio con un companiero amistoso, la cuenta de cuantos segundos aguanta antes de saltar y el dato de que la mayoria no llega a seis, y decirle que le das mas tiempo pero que vas a volver. LA MADRE TIENE LA LINEA Y EL HIJO TIENE EL PROCEDIMIENTO, que es la vara de siempre. Y DIGO POR QUE ESTO NO CONTRADICE LA LINEA 498, donde la vuelta 39 declaro SANO el par de esta misma madre con elegir_pregunta_recurrente: aquella razon dice ninguno de los dos nombra el procedimiento del otro en una linea, y aqui SI lo nombra, con las tres palabras exactas de mi titulo abriendo su paso 8. Es la misma vara dando dos respuestas a dos figuras distintas, no dos respuestas a la misma." \
 --veredicto "exigir_critica_jefe_reticente|CONTINUA|madre=exigir_critica_jefe_reticente|LA TERCERA MADRE, QUE NADIE HABIA DECLARADO HASTA LA VUELTA 38 Y QUE LA ACTA 37 SOSTUVO CON SUS OTROS CINCO DISCUTIBLES. Es el caso mas puro de nombrar no es procedimentar que tiene este capitulo: los pasos 5, 6 y 7 de la madre son TRES IMPERATIVOS DESNUDOS, sin contenido propio ninguno, y dicen exactamente Y entonces para, Cuenta hasta seis en tu cabeza, y Abraza la incomodidad. Los tres juntos son quince palabras. Yo los despliego en 12 pasos con todo lo que ahi no hay: por que el silencio es incomodo para los dos, que tu trabajo es soportarlo e incluso abrazarlo, el ejercicio con un companiero amistoso, la medida de cuantos segundos aguanta, y que hacer cuando aun asi se queda callado. ES D.29 Y NO D.37: cap_09 no escribe en ningun sitio cuantas partes tiene esta secuencia, asi que la arista la sostiene mi lectura y por eso va con su razon. Y DIGO LO QUE CUESTA ADMITIR: con esta son TRES madres para un mismo hijo, que es mucho, y asi lo marco la vuelta 38 en su discutible 7. Las tres se sostienen porque las tres nombran y ninguna despliega, y porque el propio libro repite este material en dos capitulos: cap_09 lo da comprimido dentro de arrancar la critica de un equipo, cap_13 lo abre entero porque su epilogo dice que a muchos participantes no les bastaba." \
 --veredicto "practicar_triangulo_critica_tres_papeles|SANO|LO QUE LA SENIAL VE ES QUE LOS DOS SON EJERCICIOS CON OTRA PERSONA, Y EL OBJETO ES OTRO. Este par ya se juzgo desde el otro lado en la linea 484 y lo vuelvo a emitir hoy desde el mio, con el texto de hoy de aquel nodo delante, porque la correccion de la vuelta 39 lo dejo RANCIO y D.15 no deja citar un rancio como vigente. QUE CAMBIO EN AQUEL NODO, medido campo a campo entre el arbol a41fc11 de su huella vieja eec451c2e48944c6 y el de hoy: titulo identico, sus 15 pasos identicos uno a uno, entregable, condiciones, dominio, fuentes y aristas identicos, y solo el resumen_teorico de 1951 a 2973 caracteres con prefijo comun de 1951, o sea prosa anexada sobre una cifra publicada. NADA DE LO QUE SOSTIENE ESTE VEREDICTO SE MOVIO. Y LO QUE LO SOSTIENE: yo aguanto EL SILENCIO despues de que TU hayas pedido critica, contando hasta seis en tu cabeza, y entrego el silencio aguantado hasta el final con la respuesta del otro salida de el; aquel monta un TRIANGULO DE TRES PAPELES para que TU DES una critica que no diste, y entrega el recorrido de esa conversacion dibujado sobre el marco de dos por dos por un observador. Son dos personas contra tres, es recibir contra dar, y ninguno de los dos sirve para lo del otro." \
 --censo "serie=los cuatro elementos de pedir critica;papel=parte;cabeza=pedir_critica_primero_crear_seguridad_psicologica;nota=la cuenta esta escrita en cap_13 L113, each of the four tips for soliciting criticism, y L237 los nombra uno a uno. Esta es la SEGUNDA de las cuatro, embracing the discomfort. Con ella la serie pasa de 1 a 2 de 4 partes en el grafo" $COMUN

anota an_484.txt 484 "VIGENCIA DECLARADA del 18 sep 2026, vuelta 40, TAREA 1.B del encargo: esta lectura SIGUE VALIENDO aunque su huella haya cambiado, y la relectura que lo comprueba se hizo antes de insertar al vecino, no despues. La huella contra la que se emitio es eec451c2e48944c6 y vive en el arbol a41fc11; cambio a 5aebf76b97831357 en el arbol 0dda2e3, que es el commit de la correccion declarada de la vuelta 39 sobre practicar_triangulo_critica_tres_papeles. QUE CAMBIO EXACTAMENTE, medido campo a campo con .v40/que_cambio_triangulo.py y no recordado: titulo identico de 139 caracteres, los 15 pasos identicos uno a uno, entregable de 213 caracteres identico, condiciones de activacion, dominio, fuentes, nodos_previos y nodos_siguientes identicos, y SOLO resumen_teorico de 1951 a 2973 caracteres con un prefijo comun de 1951, o sea anexion pura. Lo anexado es prosa sobre una cifra publicada, la correccion de 318 a 321 nodos y los dos caracteres acentuados. LO QUE SOSTIENE ESTE SANO NO SE MOVIO NI UN CARACTER: la razon descansa sobre el objeto y el entregable, son dos personas contra tres y es recibir contra dar, y los dos campos que dicen eso son identicos al digito. El par se ha vuelto a emitir ademas desde el otro lado en esta misma vuelta, al entrar abrazar_incomodidad_silencio_contar_seis." \
 "D.15 segunda salida, y la primera tambien: el par se releyo con el texto de hoy Y se declara por que sigue valiendo, con la medicion de que cambio pegada al lado. El encargo de la vuelta 40 dice que la que no vale es insertar encima de un veredicto rancio sin decir nada."

echo "cadena 1 terminada" >> .v40/informes/_cadena.txt
