#!/bin/sh
# CADENA 4 de la vuelta 40: el candidato 4 de 4, que NO es parte de la serie D.37 sino
# lo que L237 manda hacer DESPUES de practicar las cuatro. Su veredicto es SANO y ya
# estaba razonado dos veces.
. /c/Users/AlexDesk/Documents/forja-nodos/.v40/correr.sh

echo "cadena 4 arrancada (candidato 4 de 4)" >> .v40/informes/_cadena.txt

corre i04_integrar_peticion.txt integrar_peticion_critica_rutina_existente \
 --veredicto "pedir_critica_primero_crear_seguridad_psicologica|SANO|SON VECINOS DE LINEA Y NO DE OBJETO. Este par ya esta razonado DOS VECES, en mi linea 488 desde el otro lado y en la apertura sellada del auditor de la ACTA 38, que lo adjudico igual por separado; el encargo de la vuelta 40 me dice que no lo pelee, que lo escriba y siga, y que si al leer mis 13 pasos discrepo lo diga. HE LEIDO MIS 13 PASOS ENTEROS EN ESTA VUELTA CONTRA SU LINEA DEL LIBRO Y NO DISCREPO. D.37, apartado lo que NO autoriza: una cabeza de cuatro partes y un vecino que no es ninguna de las cuatro son HERMANOS, y su veredicto es SANO. Y la prueba de que no soy ninguna de las cuatro la escribe el propio libro en L237: Now that you have practiced the four elements, o sea que yo soy lo que se hace DESPUES de las cuatro, no una de ellas. LO QUE LA SENIAL CAZA ES UNA CITA LITERAL COMPARTIDA: su P17 y mi P06 transcriben la misma enumeracion de los cuatro elementos, pero son dos lineas distintas del libro haciendo dos trabajos distintos, L113 la ANUNCIA antes de desplegarla y L237 la RECAPITULA despues para entregar al habito. QUE ENTREGA CADA UNO: aquel entrega el orden de operaciones recorrido desde su primer paso; yo entrego LA PETICION METIDA AL FINAL DE TUS REUNIONES A SOLAS YA PROGRAMADAS, anunciada al equipo con la pregunta que vas a hacer." \
 --veredicto "elegir_pregunta_recurrente_pedir_critica|SANO|HERMANOS DE SERIE Y NO MADRE E HIJO, y este par tambien esta ya razonado desde el otro lado, en la linea 500 de la vuelta 39. Los dos colgamos de la misma cabeza, pedir_critica_primero_crear_seguridad_psicologica, pero por sitios distintos: aquel es LA PRIMERA de los cuatro elementos que L113 anuncia, y yo soy lo que L237 manda hacer DESPUES de practicar los cuatro, meterlos en la rutina que ya tienes. Mi P06 recapitula la enumeracion entera y por eso me parezco a el en la letra, pero lo que aquel entrega son TRES O CUATRO PREGUNTAS ESCRITAS Y PROBADAS con un companiero de confianza, y lo que entrego yo es LA PETICION METIDA AL FINAL DE LA REUNION A SOLAS Y ANUNCIADA AL EQUIPO. Aquel no despliega ningun sitio ni ninguna rutina, y yo no despliego ninguna pregunta: mi P13 dice que compartas la pregunta que piensas hacer y no dice cual, porque el libro no la pone aqui." \
 --veredicto "montar_reuniones_solas_mentalidad_frecuencia|SANO|LO DIGO CON LOS DOS LADOS MEDIDOS Y SUS 22 PASOS LEIDOS ENTEROS EN ESTA VUELTA. Aquel entrega LAS REUNIONES A SOLAS MONTADAS Y NO CANCELADAS, con su mentalidad, su frecuencia contada contra el limite del jefe, su agenda puesta por quien reporta, y su cuenta de cuantas se caen de cada trece programadas. Yo entrego LA PETICION DE CRITICA METIDA AL FINAL DE ESA REUNION. En sus 22 pasos NO HAY NI UNO que meta la peticion de critica al final: su P15 usa el tiempo de la reunion para las conversaciones de carrera y las evaluaciones de desempenio, y ahi se acaba lo que le mete dentro. Somos procedimientos vecinos con entregables distintos y ninguno despliega al otro: el sitio no es el procedimiento, y aquel pone el sitio mientras yo pongo lo que se hace en el. VA MARCADO COMO DISCUTIBLE EN MI REPORTE, porque compartir la reunion a solas es justo la clase de vecindad que invita a cablear sin que haya nada que desplegar." \
 --veredicto "abrazar_incomodidad_silencio_contar_seis|SANO|HERMANO DE SERIE POR PARTIDA DOBLE, Y ENTRO EN ESTE MISMO ACTO Y EN ESTA MISMA VUELTA, tres candidatos antes que yo. Aquel es LA SEGUNDA de los cuatro elementos que L113 anuncia y yo soy lo que L237 manda hacer DESPUES de practicar los cuatro: colgamos los dos de la misma cabeza y por sitios distintos. Aquel entrega EL SILENCIO AGUANTADO HASTA EL FINAL contando hasta seis, y su condicion de activacion es que ya has preguntado y se hizo el silencio; yo entrego LA PETICION METIDA EN LA AGENDA y mi condicion es que ya has practicado los cuatro por separado y quieres juntarlos. Mi P06 lo nombra en cuatro palabras, abrazar la incomodidad, porque recapitulo la enumeracion de L237, y nombrar no es desplegar: el despliegue esta en sus 12 pasos y no en mi linea. Y NO CABLEO NADA HACIA EL por lo mismo que D.37 dice en su apartado de lo que no autoriza: la madre de esa parte es la cabeza, no yo, que soy su hermano." \
 --veredicto "escuchar_entender_critica_dominar_defensa|SANO|HERMANO DE SERIE, Y ENTRO EN ESTA MISMA VUELTA dos candidatos antes que yo. Aquel es LA TERCERA de los cuatro elementos y entrega TU PROPIA DEFENSA DOMINADA mientras te critican, con el ejercicio de escuchar tres minutos sin interrumpir; yo entrego la peticion metida al final de tus reuniones a solas. Mi P06 lo nombra en seis palabras, escuchar con intencion de entender, porque recapitulo la enumeracion de L237, y ahi se acaba: no tengo ni la respuesta de pelea, huida o bloqueo, ni el ejercicio de respiracion, ni el turno de tres minutos. Colgamos los dos de la misma cabeza por sitios distintos y ninguno de los dos despliega al otro." \
 --veredicto "premiar_franqueza_hacer_escucha_tangible|SANO|HERMANO DE SERIE, Y ENTRO EN ESTA MISMA VUELTA justo antes que yo, cerrando la serie de los cuatro. Aquel es LA CUARTA de los cuatro elementos y entrega el problema criticado arreglado o explicado y la critica contada en publico, con la lista de las tres o cuatro criticas recientes; yo entrego la peticion metida en la rutina que ya tienes. Mi P06 lo nombra en siete palabras, hacer tangible la escucha premiando la franqueza, porque recapitulo la enumeracion de L237, y no tengo ni la lista, ni la pesca, ni el protocolo de la critica con la que no estas de acuerdo. Colgamos los dos de la misma cabeza por sitios distintos." \
 --censo "serie=los cuatro elementos de pedir critica;papel=resto;cabeza=pedir_critica_primero_crear_seguridad_psicologica;nota=NO es una de las cuatro partes y por eso se registra como resto: L237 escribe Now that you have practiced the four elements, o sea que este es lo que se hace DESPUES de practicarlas. D.37, lo que no autoriza: un vecino que no es ninguna de las cuatro es hermano y su veredicto es SANO" $COMUN

echo "cadena 4 terminada" >> .v40/informes/_cadena.txt
