#!/bin/sh
# CADENA 2 de la vuelta 40: el candidato 2 de 4, la TERCERA de las cuatro partes de la
# serie D.37, con sus DOS madres cableadas en el mismo acto.
. /c/Users/AlexDesk/Documents/forja-nodos/.v40/correr.sh

echo "cadena 2 arrancada (candidato 2 de 4)" >> .v40/informes/_cadena.txt

corre i02_escuchar_entender.txt escuchar_entender_critica_dominar_defensa \
 --veredicto "pedir_critica_primero_crear_seguridad_psicologica|CONTINUA|madre=pedir_critica_primero_crear_seguridad_psicologica|ARISTA D.37 QUE LA LINEA 492 DEJO EN COLA PORQUE YO SEGUIA EN LA BANDEJA, Y QUE SE CABLEA HOY EN EL ACTO EN QUE ENTRO. La cuenta esta escrita en cap_13 L113, each of the four tips for soliciting criticism offered in the book, y L237 las nombra una a una. El paso 17 de la madre nombra las cuatro y ahi se acaba. YO SOY LA TERCERA de esas cuatro, escuchar con intencion de entender, y la despliego en 13 pasos de cap_13, lineas 199 a 214, bajo el rotulo LISTEN WITH THE INTENT TO UNDERSTAND, NOT TO REPLY de la linea 199, con lo que la madre no tiene en ninguna forma: la respuesta de pelea, huida o bloqueo que dispara recibir critica aunque la hayas pedido, que la critica justa cuesta tanto como la injusta cuando toca algo que ya no te gusta de ti, el inventario de medios propios para procesarla sin caer en la defensa, y el ejercicio de escuchar tres minutos sin interrumpir con una pareja. CON ESTA ENTRADA LA SERIE PASA DE DOS PARTES A TRES DE CUATRO." \
 --veredicto "abrazar_incomodidad_arrancar_critica_equipo|CONTINUA|madre=abrazar_incomodidad_arrancar_critica_equipo|LA ARISTA 56 DE LA DEUDA DECLARADA EN LA VUELTA 24, CABLEADA HOY PORQUE HOY ES CUANDO SU HIJO ENTRA. ES D.29 Y NO D.37 por lo mismo que la 55: cap_09 no escribe la cuenta en ningun sitio, y la cuenta de cuatro vive en cap_13 L113 y L237, que es la unidad de la otra cabeza. QUE NOMBRA LA MADRE Y QUE DESPLIEGO YO: su paso 12 abre con la frase Escucha con intencion de entender y no de responder, que es literalmente mi titulo, y lo que aniade son dos avisos cortos, no empieces a criticar la critica, repite lo que dijo para asegurarte de haberlo entendido, mas una frase de ejemplo. Yo traigo en 13 pasos lo que sus 20 pasos no tienen: el nombre de lo que te pasa por dentro, la respuesta de pelea, huida o bloqueo; que la critica justa tambien cuesta; el inventario de medios que el libro pone para procesarla, el ejercicio de respiracion y el trago largo de agua; y sobre todo LA PRACTICA DE ESCUCHAR TRES MINUTOS SIN INTERRUMPIR con su pareja, sus papeles, su turno y su regla de no preguntar ni dar consejo, que no esta en ninguno de sus veinte pasos. LA MADRE TIENE LA LINEA Y EL HIJO TIENE EL PROCEDIMIENTO." \
 --veredicto "practicar_triangulo_critica_tres_papeles|SANO|MISMA FAMILIA DE CAPITULO Y NI UN ACTO COMPARTIDO. Este par ya se juzgo desde el otro lado en la linea 485 y lo vuelvo a emitir hoy desde el mio, con el texto de hoy de aquel nodo delante, porque la correccion de la vuelta 39 lo dejo RANCIO y D.15 no deja citar un rancio como vigente. QUE CAMBIO EN AQUEL NODO, medido campo a campo y no recordado: solo el resumen_teorico, de 1951 a 2973 caracteres con prefijo comun de 1951, o sea anexion pura de prosa sobre una cifra; titulo, los 15 pasos, entregable, condiciones, dominio, fuentes y aristas identicos. Y LO QUE SOSTIENE EL VEREDICTO: yo domino TU PROPIA DEFENSA cuando la critica te llega a ti, con el ejercicio de escuchar tres minutos sin interrumpir, y entrego la critica escuchada entera sin respuesta defensiva; aquel te pone a DAR una critica que no diste y a que otros dos vean como aterriza, y entrega el impacto real de tus palabras devuelto por quien la recibio. Compartimos que los dos se practican con otra gente, que es forma y no objeto." \
 --veredicto "crear_cultura_escucha_equipo|SANO|LO QUE COMPARTIMOS ES LA PALABRA ESCUCHAR Y NADA MAS, y lo digo tras leer sus 17 pasos enteros en esta vuelta. Aquel monta UN SISTEMA para que la gente genere ideas y de voz a sus quejas, con su equipo de ideas, sus limites de tiempo, su obligacion de explicar los rechazos y la vuelta a la mesa en las reuniones: entrega UNA CULTURA DE ESCUCHA MONTADA EN EL EQUIPO y su sujeto es el jefe organizando a otros. Yo entrego TU PROPIA DEFENSA DOMINADA mientras te critican a ti, con el ejercicio de los tres minutos hecho con una pareja y tu recurso de proceso identificado: mi sujeto es quien recibe la critica y mi problema es lo que le pasa por dentro. Ninguno de los dos nombra el procedimiento del otro en una linea, y ninguno de sus 17 pasos toca la respuesta de pelea, huida o bloqueo. VA MARCADO COMO DISCUTIBLE EN MI REPORTE, porque dos nodos que comparten el verbo escuchar en el titulo son justo la figura que la vara de 15.2 avisa que suele ser el mismo nodo dos veces." \
 --veredicto "escuchar_callado_equipo_tranquilizar_incomodo|SANO|LOS DOS CALLAN Y CALLAN POR COSAS DISTINTAS, y lo digo tras leer sus 11 pasos enteros en esta vuelta. Aquel reserva diez minutos de cada reunion a solas para escuchar SIN REACCIONAR, con la cara neutra, y su objeto son los TRES COSTES de ese estilo, que la gente pierda tiempo adivinando lo que piensas, que alguno use tu nombre en vano y que el silencio incomode: entrega UN ESTILO DE ESCUCHA CALLADA con las medidas para tranquilizar a quien incomoda. Yo entrego LA CRITICA ESCUCHADA ENTERA SIN RESPUESTA DEFENSIVA, y mi silencio no es un estilo sino la regla de un ejercicio de tres minutos con una pareja. Aquel no tiene ni la respuesta de pelea, huida o bloqueo, ni el ejercicio de respiracion, ni el trago de agua, ni el turno de tres minutos. Y yo no tengo sus diez minutos de cada reunion ni sus tres costes. VA MARCADO COMO DISCUTIBLE, por la misma razon que el anterior." \
 --censo "serie=los cuatro elementos de pedir critica;papel=parte;cabeza=pedir_critica_primero_crear_seguridad_psicologica;nota=la cuenta esta escrita en cap_13 L113 y L237 los nombra uno a uno. Esta es la TERCERA de las cuatro, listening with the intent to understand. Con ella la serie pasa de 2 a 3 de 4 partes en el grafo" $COMUN

anota an_485.txt 485 "VIGENCIA DECLARADA del 18 sep 2026, vuelta 40, TAREA 1.B del encargo: esta lectura SIGUE VALIENDO aunque su huella haya cambiado, y la relectura que lo comprueba se hizo antes de insertar al vecino, no despues. La huella contra la que se emitio es eec451c2e48944c6 y vive en el arbol a41fc11; cambio a 5aebf76b97831357 en el arbol 0dda2e3, que es el commit de la correccion declarada de la vuelta 39 sobre practicar_triangulo_critica_tres_papeles. QUE CAMBIO EXACTAMENTE, medido campo a campo con .v40/que_cambio_triangulo.py y no recordado: titulo identico de 139 caracteres, los 15 pasos identicos uno a uno, entregable de 213 caracteres identico, condiciones de activacion, dominio, fuentes, nodos_previos y nodos_siguientes identicos, y SOLO resumen_teorico de 1951 a 2973 caracteres con un prefijo comun de 1951, o sea anexion pura. Lo anexado es prosa sobre una cifra publicada, la correccion de 318 a 321 nodos y los dos caracteres acentuados. LO QUE SOSTIENE ESTE SANO NO SE MOVIO NI UN CARACTER: la razon descansa sobre el objeto y el entregable, aquel domina tu propia defensa y este te pone a dar una critica que no diste, y los dos campos que dicen eso son identicos al digito. El par se ha vuelto a emitir ademas desde el otro lado en esta misma vuelta, al entrar escuchar_entender_critica_dominar_defensa." \
 "D.15 segunda salida, y la primera tambien: el par se releyo con el texto de hoy Y se declara por que sigue valiendo, con la medicion de que cambio pegada al lado. El encargo de la vuelta 40 dice que la que no vale es insertar encima de un veredicto rancio sin decir nada."

echo "cadena 2 terminada" >> .v40/informes/_cadena.txt
