python forja.py insertar cuarentena/scott_radical_candor/crear_obligacion_disentir_equipo.json --sin-preguntas \
 --veredicto "parar_debate_emocion_agotamiento|SANO|Hermanos del mismo rotulo DEBATE y no madre e hijo: el libro los pone como dos tecnicas al mismo nivel bajo la misma lista (L231 el mio, L235 el suyo). Ninguno nombra el procedimiento del otro. El mio ARRANCA discrepancia donde no la hay y su entregable es una voz discrepante puesta en cada acuerdo unanime; el suyo PARA un debate que ya existe cuando la gente esta agotada y su entregable es el debate aplazado. Lo levanta similitud_texto 0.411 entre mi paso 3 (haz que alguien tome la voz discrepante) y su paso 4 (aplaza el debate), y lo que comparten es el objeto reunion, no el acto." \
 --veredicto "pedir_hechos_decision_evitar_recomendaciones|SANO|Distinta etapa de la rueda y distinto objeto: el suyo vive en DECIDE y trata de que informacion pides para decidir (hechos y no recomendaciones); el mio vive en DEBATE y trata de que nadie calle cuando todos asienten. Lo levanta similitud_texto 0.474, que es alta, y la causa esta medida: los dos usan la formula resiste la tentacion y los dos hablan de lo que la gente mete de suyo en una reunion. Pero su entregable es informacion reunida en forma de hechos y el mio es una voz discrepante: ninguno de mis 5 pasos pide informacion y ninguno de sus 5 pide disentir." \
 --veredicto "crear_cultura_escucha_equipo|SANO|Ya adjudicado por la ACTA 27 2.3 en el sentido contrario (aquel candidato contra este vecino) y SOSTENIDO, y hoy lo firmo en esta direccion con la misma vara. Etapas distintas de la rueda: el suyo declara LISTEN y monta un SISTEMA de ideas y quejas con quien las atiende y quien explica los noes; el mio declara DEBATE y declara una OBLIGACION con un objeto que pasa el turno. Ni uno de sus 17 pasos hace lo que hace ninguno de mis 5, ni al reves. La señal que lo levanta es familia_id 0.333, que mira el id y no el objeto: compartimos crear y equipo en el nombre." \
 --veredicto "proteger_tiempo_equipo_jefe|SANO|Distinto trabajo y distinta etapa: el suyo vive en EXECUTE y despeja el tiempo del equipo (obstaculos, reuniones sobrantes, mandatos de arriba); el mio vive en DEBATE y mete discrepancia en la sala. Lo levanta similitud_texto 0.357 entre mi paso 2 (trata como bandera roja que todos esten de acuerdo) y su paso 8 (para los mandatos ridiculos antes de que lleguen al equipo), y lo comun es la figura de parar algo, no el objeto que se para: uno para un mandato de fuera, el otro para un consenso de dentro." \
 --veredicto "compartir_logica_mostrar_razonamiento|SANO|Etapas distintas y actos opuestos: el suyo vive en PERSUADE y ENSEÑA el razonamiento entero de quien ya decidio; el mio vive en DEBATE y pide que alguien defienda lo contrario de lo que se ha decidido en la sala. Su entregable es el razonamiento compartido para que le encuentren un fallo; el mio es la voz discrepante puesta. Lo levanta similitud_texto 0.368, y el parecido es de forma: los dos piden que en la sala se diga en voz alta algo que se estaba callando. El objeto no es el mismo." \
 --veredicto "reservar_calendario_tiempo_ejecutar|SANO|No comparten ni etapa ni objeto: el suyo vive en EXECUTE y trata del calendario (bloquear el tiempo solitario de ejecutar); el mio vive en DEBATE y trata de quien habla en una reunion. Lo levanta similitud_texto 0.393 entre mi paso 3 y su paso 1, y lo comun es el vocabulario de reunion. Ninguno de sus 4 pasos toca el contenido de una discusion y ninguno de mis 5 toca un calendario." \
 --veredicto "cambiar_posicion_hechos_explicar_cambio|SANO|Distinto sujeto: el suyo va de que TU cambies de posicion cuando cambian los hechos y lo expliques en voz alta; el mio va de que OTRO tome la posicion contraria porque la sala esta demasiado de acuerdo. Lo levanta similitud_texto 0.399 y la causa es que los dos hablan de defender una posicion distinta a la sostenida. Pero el suyo lo hace por conviccion cambiada y el mio por encargo del jefe, y sus entregables no se tocan: un cambio de rumbo explicado contra una voz discrepante puesta." \
 --veredicto "aprender_resultados_vencer_dos_presiones|SANO|Etapas distintas y extremos opuestos de la rueda: el suyo vive en LEARN y trata de mirar un resultado ya producido sin negacion; el mio vive en DEBATE y trata de que una decision no se tome por unanimidad falsa. Lo levanta similitud_texto 0.402 entre mi paso 1 y su paso 6, y lo comun es la figura de la presion que empuja a callar. Pero la suya es la presion de ser coherente con lo que ya dijiste y la mia es la presion de estar de acuerdo con la sala." \
 --veredicto "evitar_presion_social_actos_equipo|SANO|Objeto distinto: el suyo trata de un ACTO SOCIAL no obligatorio que se siente obligatorio, y su entregable es que vaya quien quiera ir; el mio trata de una REUNION DE TRABAJO donde todos asienten, y su entregable es una voz discrepante. Lo levanta similitud_texto 0.393 y la causa es que los dos nombran la presion social. Pero el suyo la QUITA de una invitacion y el mio la INVIERTE dentro de una discusion: ninguno de sus 6 pasos pide disentir y ninguno de mis 5 organiza nada." \
 --veredicto "crear_plan_creible_equipo|SANO|Ni el mismo trabajo ni la misma etapa: el suyo construye una ESTRATEGIA con posibilidades reales de funcionar; el mio pone una norma de conducta en las reuniones. La señal que lo levanta es familia_id 0.333, que mira el id y no el objeto: compartimos crear y equipo en el nombre, igual que con crear_cultura_escucha_equipo. Es exactamente el ruido que D.19 mide en la banda media, y no una jerarquia." \
 > .v28e/insercion_04_disentir.txt 2>&1
