echo "| medida | valor al cerrar |"
echo "|---|---:|"
echo "| nodos en el grafo | **$(wc -l < dataset/nodos.jsonl)** |"
echo "| veredictos en bitacora | **$(wc -l < bitacora/VEREDICTOS.jsonl)** |"
echo "| candidatos del lote 4 que siguen en cuarentena | **$(ls cuarentena/scott_radical_candor/*.json | wc -l)** |"
echo "| candidatos del lote 4 ya en _insertados | **$(ls cuarentena/_insertados/scott_radical_candor/*.json | wc -l)** |"
echo "| ficheros en cuarentena/_insertados de todos los lotes | **$(ls cuarentena/_insertados/*/*.json | wc -l)** |"
echo "| unidades del lote 4 sin minar | **0** |"
echo "| lineas del reporte | **$(wc -l < docs/loop/REPORTE.md)** |"
echo "| commits de esta vuelta | **$(git log --oneline 74134e0..HEAD | wc -l)** |"
echo "| rama | \`$(git rev-parse --abbrev-ref HEAD)\` |"
